### ISSUE TITLE
Conjure spams error logs during a long-running eval if I switch to other types of buffers

### ISSUE THREAD

**Issue by daveyarwood** [Olical/conjure#100]
The background here is that I have a UI (browser automation) test suite that takes a really long time to run, so I often like to kick off the tests and then go do other things inside Vim to keep myself busy. The browser tests frequently print a line to stdout to tell me what test step they're running (clicking this button, entering "foo" in this text input, etc.)

I just noticed that if I happen to open a buffer type that Conjure doesn't support (diff, magit, gina, etc.), then every time the Conjure log gets appended, I get interrupted by an error. Here's an extreme example (output is `:messages` run after the fact):

![2020-06-15-140643_1675x1082_scrot](https://user-images.githubusercontent.com/4909079/84691071-86da9c00-af11-11ea-948b-f626c6d16994.png)

**Comment by Olical** [comment]
Oh no, that's awful! I'll take a dig into why this happens.

**Comment by Olical** [comment]
Can reproduce and I've found the offending code (it's for debugging) - digging deeper.

**Comment by Olical** [comment]
Should be fixed on develop! Also, congratulations on issue #100 :D

**Comment by daveyarwood** [comment]
Nice, lucky roll on my part! :game_die: 

Thanks, I can confirm that it's fixed on `develop` :100:
