### ISSUE TITLE
Quick way to get an nREPL going?

### ISSUE THREAD

**Issue by gunar** [Olical/conjure#102]
This is not necessarily a conjure question. Just wondering. I want to run eval some code, and test some snippets. I would prefer not having to bootstrap a whole project for that. Is there an easy way to get an nREPL going, like a default one? Thanks in advance!

**Comment by Olical** [comment]
Of course! It can all be started from one command, even with CIDER middleware 😄 (assuming you have the Clojure CLI installed)

```bash
clojure -Sdeps '{:deps {nrepl {:mvn/version "0.7.0"} cider/cider-nrepl {:mvn/version "0.25.2"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'
```

(taken from the [CIDER docs](https://docs.cider.mx/cider/basics/up_and_running.html))

**Comment by Olical** [comment]
I've added this to the [Clojure on the JVM](https://github.com/Olical/conjure/wiki/Quick-start:-Clojure) quickstart guide too.

**Comment by gunar** [comment]
POIFECT! Thank you very much for the prompt reply. I have just added the alias below to my `.bashrc`.
```sh
alias nrepl=clojure -Sdeps '{:deps {nrepl {:mvn/version "0.7.0"} cider/cider-nrepl {:mvn/version "0.25.2"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'
```

By the way. What do you think about this feature. Conjure could "run" the command above on the background, in case it doesn't find any active nREPL instances. What do you think?

**Comment by Olical** [comment]
Nice! Glad it was what you were looking for 😄

And yeah, that's what I would call "jack in" and I'm still kind of avoiding it at the moment because as soon as I add it it becomes "could ya just add this config to make it do this" and before you know it you have a Clojure environment manager built into Conjure. Something that I _may_ get around to one day.

I was hoping someone would step in before me and write a great plugin for this before I had to do it 😅

**Comment by gunar** [comment]
Thank you for your help. And for the insight into the implication of such a design change. My problem is solved! Closing the issue now. Thank you!

**Comment by Olical** [comment]
Not a problem! I would love to have a one button setup in the future, it's just something that opens up a can of question and config worms that I don't want to tackle just yet. Too many bigger fish to fry!

A plugin to start various REPL servers (not even just Clojure!) to pair with Conjure would be amazing, maybe I'll do it one day or write up enough help and outline that it'll be easy for someone else to implement and maintain.

**Comment by chopptimus** [comment]
There is the [vim-jack-in](https://github.com/clojure-vim/vim-jack-in) plugin that I find very useful.

**Comment by Olical** [comment]
Oh neat! Thank you @chopptimus I need to have a look at it! It seems pretty generic, I had a feeling it'd be tied to fireplace but nope, it just starts a REPL. Then I guess if it created a `.nrepl-port` file you could just hit `<prefix>cf` and away you go. I'll have to try it out! Thanks for creating it @SevereOverfl0w!

**Comment by Olical** [comment]
I'll give it a trial run and probably recommend vim-jack-in from the docs if it works well for me 😄

**Comment by SevereOverfl0w** [comment]
I use vim-jack-in all the time, let me know if you need a hand.   I'm on slack all day.
