### ISSUE TITLE
Disable K and gd mappings

### ISSUE THREAD

**Issue by patrickpichler** [Olical/conjure#103]
Is there any way to disable the mappings for `K` and `gd`?

I checked the documentation, but besides using `:ConjureConfig` (which did not work) didn't found any way.

**Comment by Olical** [comment]
You should be able to set their mappings to `nil` and they won't be applied? Or another combination of keys other than those defaults.

I've actually rewritten the config system on develop to be released some time soon, it replaces it all with regular `let g:conjure#debug = v:true`, for example. You may want to swap early and check that out 😄

**Comment by patrickpichler** [comment]
I might be doing something wrong, but `:ConjureConfig mappings.def-word nil` has no effect on the keymappings. 

I might give the develop-branch a shot then :)

**Comment by Olical** [comment]
Oh no, that sucks! It should work and I'm sorry about the issue. You could remap them to other keys on master or use `unlet` on them on `develop`. You'd need to migrate to the new simpler style at some point anyway, so develop may be a good bet 🤔

**Comment by patrickpichler** [comment]
No worries and thanks for the fast answer :+1:

**Comment by Olical** [comment]
Oh, were you running `:ConjureConfig ...` _before_ you entered a Clojure etc buffer? Because it won't unset a mapping that's already made, it's intended to be set in your vimrc.

**Comment by patrickpichler** [comment]
Thanks I just found my issue. I somehow missed that there is the `conjure_config` variable to configure the plugin when it is loaded lazy.

**Comment by patrickpichler** [comment]
I got it to work by configuring an empty string for `mappings.doc-word` and `mappings.def-word`

**Comment by Olical** [comment]
That's great! Glad it works, sorry it was a little difficult. I hope my new
config system will make it easier.

It'd be this instead.

unlet g:conjure#mapping#doc_word
