### ISSUE TITLE
Feature Request: Support virtual text?

### ISSUE THREAD

**Issue by davidsierradz** [Olical/conjure#112]
Hi, impressive what you got here!

I was checking the legacy branch and there was support for virtual text, is to hard to support it again in the new branch?

Feel free to close if this is too hard or not desirable/feasible (floating windows are ok too).

Thanks!

**Comment by Olical** [comment]
Hmm not too hard to implement but were you thinking for eval results? I personally found that cramped and pretty unworkable unless all you're ever returning are small atomic values, anything bigger than that just became a vague notion of what type it was.

My original plan was to use virtual text (at some point in the future) to display arg lists etc of the form you're hovering over, but I'm not fully sold into that just yet. (just like how cider/emacs display it in the bottom of the buffer, the minibuffer?)

Maybe this could be configurable / pluggable, I'll have a think about the UX of this. Inline results could be nice although that + HUD would be noisy, so you'd want one or the other, not both.

And then there's the question of: Could I display the arg lists as well as some results from evals if you opt into it. I'll give it some hammock time :smile: 

I suppose in the spirit of "add a feature that benefits all clients", opting into inline results could work for every client out of the box.

**Comment by davidsierradz** [comment]
Yeah, for sure. Take all the time you need. Honestly, I don't have a picture as big like you of how can this be. Thanks!

**Comment by tami5** [comment]
Hay, just switched to conjure. Wow it just gets out of your way and does exactly what you want. Thank you @Olical. Although I miss virtual text so much, no that I don't like the popup, but I'm used to having result apper on the buffer as I'm editing. conjure buffer I believe would work for me as repl.

Here's some implementations I liked: [codi](https://github.com/metakirby5/codi.vim) has an amazing expereience live eval lines or blocks as you type (far cry from what we actually want) but it has a great syntax highlighting for the results [preview](https://www.youtube.com/watch?v=iGrUvcQyfhc), [acid.nvim 'virtual text implementation in lua'](https://github.com/clojure-vim/acid.nvim/blob/3de79a37808c3cf172a383ad64bef77f78876f01/lua/acid/middlewares/virtualtext.lua) and [iced-vim 'vimL'](https://github.com/liquidz/vim-iced/search?q=virtual+text&unscoped_q=virtual+text)

**Comment by Olical** [comment]
Thanks for the support! And references! Virtual text is definitely on my todo list, I'll bear these ideas in mind when I get around to it. I'll share my plan for how it'll work here before it's implemented as a sort of RFC too :smile: hopefully it won't be too far away, I just wish I had more time!

**Comment by tami5** [comment]
Looking forward, Thank you. PS: getting my way around aniseed and configuring my nvim with it, hopefully soon I can contribute.

**Comment by Olical** [comment]
It's been a _long_ time coming but I'm working on `conjure.inline` which is all about virtual text hints for things like documentation and eval results :eyes:

**Comment by Olical** [comment]
![Screenshot_2020-12-27_13-26-48](https://user-images.githubusercontent.com/315229/103171843-32609380-4847-11eb-87e0-cec2b328e2d3.png)

Initial pass working on the `develop` branch! No configuration or docs yet, so all evals end up in virtual text as well as the HUD. Need to work out something clever so you can have the following cases:

 * Only virtual, no HUD ever (unless requesting docs etc)
 * Only HUD, no virtual ever.
 * Hybrid, virtual for small eval results, HUD for multi line and docs / view source.

Requires time and experimentation!

The really neat thing is that this one implementation works for _every_ Conjure client, so Racket, Fennel, Janet and Clojure all get the same feature :tada:

**Comment by tami5** [comment]
Oh thats really nice

**Comment by Olical** [comment]
Going to mark this as done and release it early even though I have more to do. I'll create a separate issue for the smart behaviour of when to use inline and when to use the HUD, for now both will appear on every eval result. I just want to get it released and in the user's hands so I can get feedback and confirmation that everything is working okay :blush:
