### ISSUE TITLE
Feature Request: Highlight evaluation

### ISSUE THREAD

**Issue by davidsierradz** [Olical/conjure#113]
Hi, I'm enjoying playing with Conjure!

I was trying to add a brief highlight when evaluating an expression, I hacked something in Lua (My fennel and Lua knowledge is almost non-existent) 

It looks something like this. Here I'm evaluating this root-form:

![image](https://user-images.githubusercontent.com/9190258/90339741-72218f80-dfb8-11ea-95cf-83606216b847.png)

Or check this asciinema:

[![asciicast](https://asciinema.org/a/353693.svg)](https://asciinema.org/a/353693)

I got:

```patch
diff --git a/lua/conjure/eval.lua b/lua/conjure/eval.lua
index ed21063..f27b746 100644
--- a/lua/conjure/eval.lua
+++ b/lua/conjure/eval.lua
@@ -128,11 +128,35 @@ do
   client_exec_fn = v_0_
 end
 local eval_str = nil
+local function highlight_range(opts)
+  if not (type(opts.start) == "table" and type(opts.finish) == "table") then
+    print("arguments start or finish: expected table")
+    return nil
+  end
+  local start = opts.start
+  local finish = opts.finish
+  local start1 = {}
+  start1[1] = start[1] - 1
+  start1[2] = start[2]
+  local finish1 = {}
+  finish1[1] = finish[1] - 1
+  finish1[2] = finish[2] + 1
+  local bufnr = opts.bufnr or 0
+  local higroup = opts.higroup or "IncSearch"
+  local timeout = opts.timeout or 500
+  local NAMESPACE = vim.api.nvim_create_namespace "conjure_highlight"
+  vim.highlight.range(bufnr, NAMESPACE, higroup, start1, finish1)
+  vim.defer_fn(
+    function() vim.api.nvim_buf_clear_namespace(bufnr, NAMESPACE, 0, -1) end,
+    timeout
+  )
+end
 do
   local v_0_ = nil
   do
     local v_0_0 = nil
     local function eval_str0(opts)
+      highlight_range({start=opts.range["start"], finish=opts.range["end"]})
       local function _3_()
         if opts["passive?"] then
           return opts
```

The function accepts a range (Conjure range and Neovim range have an offset, nothing difficult), a buffer number, a highlight group and a duration.

Is this something you think would be valuable in Conjure (Maybe behind a config flag)? The problem is: I don't know how to write the fennel code that outputs this Lua.

Thanks!

**Comment by Olical** [comment]
This is released! The help text for it can only be found on `develop` at the moment though.
