### ISSUE TITLE
Fail gracefully if NeoVim version < required.

### ISSUE THREAD

**Issue by harryvederci** [Olical/conjure#114]
Oliver, you're awesome. Thanks for your work! I'm considering moving from Vim to NeoVim because of your [Conversational Software Development](https://www.youtube.com/watch?v=RU28xy9JXxs) video.

On my work laptop (Macbook) Conjure works fine but I can't seem to get it to work on one of my crappier machines (Chromebook with a Linux container). There, I get the following error when running the `curl -fL conjure.fun/school | sh` command from the readme:

```
Error detected while processing /tmp/conjure-school/conjure-master/plugin/conjure.vim:
line    2:
E5105: Error while calling lua chunk: ...ool/conjure-master/lua/conjure/aniseed/deps/nvim.lua:67: validation_failed: "set": expected function, received nil
```

I'm not sure, but I guess this is because I'm stuck on version 0.3.4 of NeoVim.
Maybe the error could be handled in a more informative way?

Also, the readme file mentions Conjure requires the latest version of NeoVim somewhere. Maybe that statement could be moved to a "Requirements" section at the top of the file?

**Comment by Olical** [comment]
Ah an excellent point! I think you need 0.4+, I'll work out which versions it works with and add something to the code / readme. Thank you so much for pointing this out! It's a pretty gross error to hit :sob:

I think you can download a standalone binary from the nvim repo from the latest stable version that can be run in place, that might help you get newer versions onto some machines.

**Comment by harryvederci** [comment]
Thanks for the super fast response!

I managed to install Neovim. For anyone interested, I created a [script](https://github.com/lua-dipa/tools/blob/master/neovim-builder-chromebook.sh)

Now it's working!
```
(module user.conjure-school
  {require {school conjure.school
            nvim conjure.aniseed.nvim}})

;; Welcome to Conjure school!
;; Grab yourself a nice beverage and let's get evaluating. I hope you enjoy!
```

I will enjoy this for sure!
