### ISSUE TITLE
Add border to floating window

### ISSUE THREAD

**Issue by tami5** [Olical/conjure#123]
Hey @Olical, it would be more visible if conjure's floating window had boarders or at least an option to one. I struggle to read output specially when I have a split open.

Thanks

**Comment by Olical** [comment]
Hmm would be nice although not sure how it could be implemented right now. I think it'd require layering floating windows up? There's no support in Neovim for this, the only issue is https://github.com/neovim/neovim/issues/9718 which was closed :cry:

I guess it'd be restricted to changes in `conjure.config` and `conjure.log` which is nice, so it'd be a very specific change.

**Comment by tami5** [comment]
Yes, it's possible but with workaround I guess. I think having window related thing in window.fnl make things easier to change no?

**Comment by tami5** [comment]
Here a snippet of code I managed with it to add border to any-jump.vim in neovim

``` vim
  let top = '╭' . repeat('─', width - 2) . '╮'
  let mid = '│' . repeat(' ', width - 2) . '│'
  let bot = '╰' . repeat('─', width - 2) . '╯'
  let lines = [top] + repeat([mid], height - 2) + [bot]
  let s:border_buf = nvim_create_buf(0, 1)
  call nvim_buf_set_lines(s:border_buf, 0, -1, v:true, lines)
  call nvim_open_win(s:border_buf, v:false, opts)

  let opts.row += 1
  let opts.height -= 2
  let opts.col += 2
  let opts.width -= 4
```

**Comment by Olical** [comment]
Thanks for putting in the research for this, I'll have a dig into the feature ASAP! My current project is supporting STDIO REPLs, initially for Racket but it'll also allow us to do Fennel/Lua in other processes such as the LOVE game engine :eyes: I think.

**Comment by jlesquembre** [comment]
neovim 0.5 added an option to create borders. There are some pre-defined borders, it's explained on the `nvim_open_win` docs

**Comment by jlesquembre** [comment]
@Olical I think you can close this one :)

**Comment by Olical** [comment]
Oh nice! Thank you!
