### ISSUE TITLE
Support/Feature request: Does conjure support jumping?

### ISSUE THREAD

**Issue by NickeZ** [Olical/conjure#125]
Hello,

One feature I think is pretty useful is `CTRL-]` to jump to definition and then `CTRL-T` to jump back. Is this something I can enable with conjure?

Cheers

**Comment by Olical** [comment]
This is something that works in Clojure with CIDER middleware enabled but no other language, it's under `<prefix>gd` for "go to def". I didn't override the built in Neovim mapping because that'd be used for tag jumping etc and I don't want to hide that feature behind a Conjure mapping.

If you would like go to def in other languages, it can be implemented in the Conjure language client module but it requires the language itself to have some way to describe where a symbol is defined. Clojure has this, Racket may do, Janet does not to my knowledge and neither does Fennel / Lua.

I hope this clears things up?

**Comment by dharrigan** [comment]
I do something approximating what is required (seems to work fine...)

```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Santatize Tag (Strip off a symbol's namespace - for Clojure)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! SanitizeTag(word) abort
  return (split(a:word, '/')[-1])
endfunction
```

```
augroup clojure_aug
  autocmd!
  " When editing a Clojure(Script) buffer, make C-] smarter about jumping to
  " tags when the symbol is namespace-qualified.
  autocmd FileType clojure
        \ nnoremap <buffer> <C-]>
        \ :exe ":tag ".SanitizeTag(expand("<cword>"))<cr>

  autocmd BufNewFile,BufRead *.edn              setf clojure
augroup END
```

Hope that helps!

-=david=-

**Comment by NickeZ** [comment]
> This is something that works in Clojure with CIDER middleware enabled but no other language, it's under `<prefix>gd` for "go to def". I didn't override the built in Neovim mapping because that'd be used for tag jumping etc and I don't want to hide that feature behind a Conjure mapping.
> 
> If you would like go to def in other languages, it can be implemented in the Conjure language client module but it requires the language itself to have some way to describe where a symbol is defined. Clojure has this, Racket may do, Janet does not to my knowledge and neither does Fennel / Lua.
> 
> I hope this clears things up?

I'm using vim for many languages and I would prefer if all worked the same/similar. I'll try to remap things so that I can reuse my vim knowledge. Thanks!

**Comment by NickeZ** [comment]
> I do something approximating what is required (seems to work fine...)
> 
> ```
> """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> " => Santatize Tag (Strip off a symbol's namespace - for Clojure)
> """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> function! SanitizeTag(word) abort
>   return (split(a:word, '/')[-1])
> endfunction
> ```
> 
> ```
> augroup clojure_aug
>   autocmd!
>   " When editing a Clojure(Script) buffer, make C-] smarter about jumping to
>   " tags when the symbol is namespace-qualified.
>   autocmd FileType clojure
>         \ nnoremap <buffer> <C-]>
>         \ :exe ":tag ".SanitizeTag(expand("<cword>"))<cr>
> 
>   autocmd BufNewFile,BufRead *.edn              setf clojure
> augroup END
> ```
> 
> Hope that helps!
> 
> -=david=-

I guess you also have ctags setup in this case? ctags doesn't really cut it for clojure since the namespace is needed to solve name conflicts. I was hoping conjure with some better knowledge about clojure would be able to jump to the correct tag.

**Comment by Olical** [comment]
@NickeZ You can always configure Conjure to use a mapping of your choice. See `:help conjure` for all of the mappings and how to configure them.

```vim
let g:conjure#mapping#def_word = ["<c-]>"]
```
