### ISSUE TITLE
Smart comment block evals

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#132]
Eval root form shouldn't count comment as a root form, it should instead hunt one level below that. This would mean that "eval root form" in a comment block would eval the root - below the comment, allowing you to eval forms inside comments a lot easier.

**Comment by emilaasa** [comment]
This would be a great quality of life improvement for me, either as having `<leader>er` be context aware enough to do it, or having a separate binding. It's the most common for of evaluation for me, and the work around that I use for now is putting things in the root and then (hopefully remember to) clean them up before comitting.
:+1:

**Comment by dharrigan** [comment]
Hi,

At the moment, what I'm tending to do is wrap things inside the `comment` block with a `do`, then eval the do. Whilst not ideal, it does mitigate the issue a little bit.

-=david=-

**Comment by Olical** [comment]
About time I addressed this in the next update I think 😄

**Comment by Olical** [comment]
![Screenshot_2021-05-22_12-28-36](https://user-images.githubusercontent.com/315229/119225022-414b2980-baf9-11eb-891a-18337da14800.png)

👀

**Comment by Olical** [comment]
`:helpg conjure#eval#gsubs` on `develop` to check out the current idea.

Set `let g:conjure#eval#gsubs = {'do-comment': ['^%(comment[%s%c]', '(do ']}` and you can now evaluate comment blocks like they were do blocks!

So `<prefix>er` where the cursor is the pipe will evaluate both prints. `<prefix>ee` would be just the first print.

```clojure
(comment
  (print| "hello")
  (print "world"))
```

And `<prefix>ee` here would evaluate both prints.

```clojure
(comm|ent
  (print "hello")
  (print "world"))
```

I know it's not perfect, we really want `<prefix>er on one of the prints to evaluate one of the prints, so to kind of ignore the comment form, not treat it like a `do`. This is however EXTREMELY difficult to implement without full tree-sitter support since it requires an understanding of the AST, it's not doable with simple string modifications.

I think parsing all Conjure supported languages myself to understand and walk the AST is out of scope for now. This is exactly what tree-sitter is good for though.

So, I thought I'd add a generic tool that can be used for SO many more things than just evaluating comments. It lets you do that one thing but it also lets you get creative, it's kinda like pre-eval Conjure string manipulation macros? So you can add all sorts of _fun_ transforms if you so choose. It's a double edged sword of course, you could break your code spectacularly too.

**Comment by emilaasa** [comment]
Looks like a good start! Will try it out at work on monday.

**Comment by emilaasa** [comment]
I like it but I'd honestly give you $100 if I could get it to work in the really good way. :-)

**Comment by Olical** [comment]
Done on develop! Like, properly this time. You need tree sitter though.
