### ISSUE TITLE
Initial Python client support

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#134]
A non-Lisp! I think this will be easier to select forms when Neovim 0.5 is stable and we have tree-sitter everywhere but @sotte has already got some hax working for Conjure + Python support! Exciting! :tada: 

![image](https://user-images.githubusercontent.com/315229/99907361-53781680-2cd4-11eb-8929-192703c4f8bf.png)

**Comment by russtoku** [comment]
Some improvement has been made to the Python client through the use of Tree-sitter. See [Release v 4.44.0](https://github.com/Olical/conjure/releases/tag/v4.44.0).

Apologies for the self-promotion. :grin:

**Comment by Olical** [comment]
Oh yeah, this is working really well now! I'd still like to rewrite the entire stdio based REPL support to massively improve stability and structure, but this is in a good enough place to close this issue now I think. Thanks!
