### ISSUE TITLE
Use a different language for Racket REPL?

### ISSUE THREAD

**Issue by poga** [Olical/conjure#140]
Hi! Thanks for the great work on Conjure. 

Racket REPL can supports different language readers with `-I` parameter.  ([doc](https://beautifulracket.com/explainer/repl.html))

Is there a way to force conjure to start a REPL with a different `-I` params to evaluate different languages?

**Comment by Olical** [comment]
Hey there! Thank you and you're more than welcome :smile:

You can alter the command Conjure uses to start the Racket REPL with the `g:conjure#client#racket#stdio#command`, which defaults to just `"racket"`.

I've just realised it's missing from `:h conjure-client-racket-stdio`, so I'll get that updated.

**Comment by Olical** [comment]
I've made sure this option is in the help file and I've added a mention about it to the quickstart wiki page: https://github.com/Olical/conjure/wiki/Quick-start:-Racket-(stdio)
