### ISSUE TITLE
Cannot evaluate regex

### ISSUE THREAD

**Issue by patrickpichler** [Olical/conjure#143]
I encountered a strange bug with some regex.

When trying to evaluate the following form, I get no result, nor any logs. 

```clojure
  (re-seq #"(?:((\d+|(?!no)\w{2,})) )?(\w+ \w+) bags" "drab coral bags contain no other bags.")
```

Note: When selecting the line in visual mode and pressing `\E` I get a result. 

I'm running neovim 0.4.4 and conjure 4.9.0

**Comment by Olical** [comment]
Hmm I'll investigate! Not sure why this would happen, Conjure doesn't care about the code, it just grabs strings and sends them off to the nREPL, so it's probably something surprising and maybe unrelated to Conjure but worth getting to the bottom to.

**Comment by Olical** [comment]
Oh yeah, I can repro! I have a hunch it's to do with the paren matching / searching, I think I need to add a special case for regex that contain parens like I do strings. I thought they'd be under the same part of the nvim syntax tree but I guess not!

**Comment by Olical** [comment]
Should be alleviated / fixxed on `develop` :slightly_smiling_face:

**Comment by Olical** [comment]
It still behaves weird if you try to eval from within the parens inside the regex, maybe that can be improved, although I think this allows you to eval commented out forms if you need to, which is kinda useful?

**Comment by patrickpichler** [comment]
Thanks for the fast response!

I will give the `develop` branch a shot.

**Comment by Olical** [comment]
Closing because I think this should be enough for now, further improvements to not getting confused by parens in strings will come with tree-sitter soon (tm).
