### ISSUE TITLE
Integrate clj-kondo / babashka etc to supplement the REPL

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#145]
A few people in Clojurians Slack were wondering if we could use these tools when not connected to a REPL or if the go to def lookup fails for whatever reason. I think relying on these tools as a supplement is a really good idea!

**Comment by rafaeldelboni** [comment]
[clojure-lsp](https://github.com/snoe/clojure-lsp) is my default conjure supplement when I don't want to use repl I don't have time to wait an entire huge project evaluation, it's backend is using now clj-kondo, maybe you could use some inspiration, but I think this supplement could go in a separated plugin or as a config where you can set another plugin alternative to repl.

**Comment by tami5** [comment]
This would be a great idea. I could have personal scratch buffer like emacs if something like this can workout.

**Comment by glyh** [comment]
Isn't this done already?

**Comment by Olical** [comment]
Not in the way I originally envisioned, but yes I guess. Babashka autorepl is very handy and LSP sort of handles everything else I could ever imagine with kondo. Agreed.
