### ISSUE TITLE
Trying to get working with Janet

### ISSUE THREAD

**Issue by cmaughan** [Olical/conjure#146]
When I start the janet repl I see this:

```
λ janet -e "(import spork/netrepl) (netrepl/server)"
Starting networked repl server on 127.0.0.1, port 9365...
```
Is it stuck?  Or is this the only message?

When trying to do :ConjureConnect in neovim, I see this:
client.lua:273: No Conjure client for filetype: ''

I have janet installed, I have the Conjure plugin, and ConjureSchool works just fine....

**Comment by Olical** [comment]
Do you have a `janet` filetype? I.e. a Janet syntax plugin? Because it sounds like "*.janet" files aren't being recognised as Janet in your setup.

**Comment by cmaughan** [comment]
That was it, thanks :)
