### ISSUE TITLE
Improve client / filetype configuration

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#148]
The current dictionary / table based configuration under `g:conjure#filetype_client` complects "enabling" and "configuring" a filetype -> client relationship. Other issues are:

 * It's hard to document since this is the only table based config item in the system, so it breaks expectations.
 * You can't just mutate the table due to the oddities of vim / lua data structures (I think?). You have to change a key then reassign the `g:` variable which is really awkward.
 * It doesn't merge easily with the defaults, the rules on which keys should be overridden by my config merge system break down around it.
 * It behaves differently and requires different considerations depending on _when_ you write the configuration. If it's before Conjure loads it's one way, after it's another.

So I propose the following:

```vim
" This list configures which filetypes work with Conjure, by default it's all of the default clients.
let g:conjure#filetypes = ["clojure", "janet"]

" And this is how you override a client to use a different one for a filetype.
let g:conjure#filetype#fennel = "conjure.client.fennel.stdio"
```

So you won't need to set these, but if you need to use a different client for a filetype you can set that with a regular flat `g:` variable. If you want to change which filetypes Conjure enables for, you set the `filetypes` list.

This separates the concepts of configuring and enabling, makes it easy to document, fits with how every other option works and doesn't complicate the implementation.

This is a small *breaking change* for those that are already using `g:conjure#filetype_client`, but it'll be very easy to swap, I think users can delete whatever workarounds they've had to do and rely on this instead very easily.

**Comment by Olical** [comment]
This is completed on develop. Any thoughts? It's documented already too, hopefully it all makes sense! I think it's a LOT more readable and useful.

**Comment by BerkeleyTrue** [comment]
Does this configuration need to be in vim? Could be more useful and flexible as a lua function call

**Comment by Olical** [comment]
It's vim global variables, but you can set these from Lua no problem. I think there's already functions in the `conjure.config` module that you could call though if you want to do bulk merging.

**Comment by Olical** [comment]
Yeah, see `conjure.config` for functions around this, there's `assoc-in` which allows you to set nested config values.

There's also `merge` which recursively merges a table of config into the existing config, by default not overriding anything that's already set (used by Conjure internally to overlay defaults on startup). You can set `opts.overwrite?` in the second arg to `merge` to merge recursively _and_ overwrite though, if you so choose.

So yeah, it's vim options mainly because that's the standard vim way and it can be configured from the `:` command prompt easily, but you can totally require Conjure's config module and call those functions from Lua if you want :D

Closing this issue since I'm happy with it and I'm moving onto the next feature of this release. I should probably cut a release soon before I continue with the next tickets tbh... this is why I don't like deciding what will be in the next release, I'd rather just release early and often whenever the next thing is done. Oh well!
