### ISSUE TITLE
Error when trying to run test with metadata under cursor

### ISSUE THREAD

**Issue by callum-oakley** [Olical/conjure#161]
e.g. `<localleader>tc` in

```clojure
(deftest ^:kaocha/skip test-bar
  (is (= (+ 1 2) 3)))
  ```
  
results in

```
; run-current-test: ^:kaocha/skip
; (err) Syntax error reading source at (REPL:1:57).
; (err) Unmatched delimiter: )
```

Runs okay when running all the tests for the namespace.

(p.s. thanks so much for conjure! having a great time with it)

**Comment by Olical** [comment]
Good catch! I'll get this fixed :slightly_smiling_face:

_/me wishes tree-sitter was stable and common place so this parsing would be trivial_

**Comment by Olical** [comment]
Should be fixed on the `develop` branch, let me know if that looks okay to you! :smile:

**Comment by callum-oakley** [comment]
Works like a charm, thanks! :)
