### ISSUE TITLE
Some completions are missing (Clojure + nrepl + coc-conjure)

### ISSUE THREAD

**Issue by lkyhfx** [Olical/conjure#162]
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3

Some builtin functions such as `contain?` , `zipmap` are missing in the completion list.
![截屏2021-01-09 下午10 36 49](https://user-images.githubusercontent.com/30225731/104094310-2b1b9a00-52cb-11eb-874e-575c3404b83e.png)

**Comment by Olical** [comment]
This appears to be working fine for me :thinking: do you have the CIDER middleware for nREPL set up? Although sometimes I need to use `<c-x><c-o>` to trigger my completions early if I'm typing 2-3 characters without a `/` or `.` which triggers my completion plugin early.

![Screenshot_2021-01-09_14-43-04](https://user-images.githubusercontent.com/315229/104094478-01da1a00-5289-11eb-9c00-6e78c956a8d6.png)

**Comment by lkyhfx** [comment]
Oh 😅, I put `cider-nrepl` in `:dependencies`.  After set up CIDER middleware for nREPL correctly, everything works fine.
