### ISSUE TITLE
Allow goto definition when connected to a remote nREPL

### ISSUE THREAD

**Issue by tomgeorge** [Olical/conjure#164]
When connected to a remote nREPL server, executing `<localleader>gd`  takes me to the remote file path, which (usually) is empty.  

Ideally, I would like to be able to pass in a map of remote -> local paths to the conjure configuration, e.g. 

```edn
{"/root/.m2" "/home/tgeorge/.m2"
 "/src/app" "."}
````

Or something like that.  I think this would be valuable to people that work in a docker container or other remote development environment.

I'd be willing to try and take this on (I'm not very experienced in fennel but I can try).  I think the function I want is `fnl/conjure/client/clojure/nrepl/action.fnl`, `(nrepl->nvim-path)`.  If I added the above map to `config.fnl` and modified `nrepl->nvim-path` to take the possible path translation into account, would that be acceptable?

**Comment by Olical** [comment]
Does this help you out at all? It's what it was designed for and I use it to eval within docker containers, it's not designed for multiple configured paths, but I can have a think about this feature.

https://github.com/Olical/conjure/blob/e966ef58720fa0a2739aa33e9307809925b36597/doc/conjure.txt#L443-L454

**Comment by tomgeorge** [comment]
Ah! I tried to scour the docs before opening this issue, but I guess I missed it.  This is certainly helpful, but as you point out it is only  for the project root.  It'd be nice if I want to go to the definition of a symbol defined in a library.

**Comment by Olical** [comment]
I just pushed this feature to `develop`, it's under the `g:conjure#path_subs` config which can be found in `:h conjure`. Let me know what you think!

**Comment by tomgeorge** [comment]
Dumb question but I'm not sure how I set this, I tried:

```
:let g:conjure#path_subs = '{"/home/tgeorge" = "/home/tom"}'
```

but I can't get it to work.  I am looking at the develop branch and see the path-subs commit, but don't see `path_subs` in docs.

**Comment by Olical** [comment]
It's definitely got the docs for this in the commit https://github.com/Olical/conjure/commit/d3f9e6ee3ea13cc0bfe17a1b66c37f4239aa0e93, it should be in `:h conjure`? If not then I suspect your local copy of the repo isn't up to date :thinking:

**Comment by tomgeorge** [comment]
oh ok I got it, I had to `helptags ~/git/conjure/doc`.

Then setting it like this `let g:conjure#path_subs={"/home/tgeorge": "/home/tom"}`

Looks good to me!

**Comment by Olical** [comment]
Awesome! Sorry, I was thinking of suggesting that but it slipped my mind :grimacing: and yeah, that config looks good to me! :smiley:
