### ISSUE TITLE
new fennel completion throws when declaring a module

### ISSUE THREAD

**Issue by BerkeleyTrue** [Olical/conjure#165]
when starting a new file, conjure throws errors as completion try's to find the module in memory.

![image](https://user-images.githubusercontent.com/6775919/104495403-9647c380-558c-11eb-8394-f7f5eafa40c0.png)

A work around for now is to eval the module expression as soon as you right it to quell the error messages but you still have to get through the initial errors

**Comment by Olical** [comment]
Should be fixed on develop :slightly_smiling_face: did you have issues with specific suffixes to the string you're completing too? Like if you were trying to complete `foo.` compared to just `foo`? Because I try to strip trailing punctuation like that, but maybe I need to harden it some more.
