### ISSUE TITLE
No such namespace: shadow.cljs.devtools.api

### ISSUE THREAD

**Issue by knubie** [Olical/conjure#168]
When running `:ConjureShadowSelect memo` this error occurs occasionally:
```
; --------------------------------------------------------------------------------
; localhost:9000 (connected)
; --------------------------------------------------------------------------------
; Assumed session: Vizsla (ClojureScript)
; --------------------------------------------------------------------------------
; shadow-cljs (select): memo
; (err) ------ WARNING - :undeclared-ns ------------------------------------------------
; (err)  Resource: <eval>:1:2
; (err)  No such namespace: shadow.cljs.devtools.api, could not locate shadow/cljs/devtools/api.cljs, shadow/cljs/devtools/api.cljc, or JavaScript source providing "shadow.cljs.devtools.api"
; (err) --------------------------------------------------------------------------------
; (err) 
; (err) ------ WARNING - :undeclared-var -----------------------------------------------
; (err)  Resource: <eval>:1:2
; (err)  Use of undeclared Var shadow.cljs.devtools.api/nrepl-select
; (err) --------------------------------------------------------------------------------
; (err) 
nil
```

Restarting shadow-cljs seems to resolve the issue.

**Comment by Olical** [comment]
Like the other issue, I think this is a shadow-cljs timing thing :thinking: I'm really not running much code at all, just a require and a function call so there's not much else I can do? Might be worth asking about these issues on the shadow-cljs channel in Clojurians Slack? Like is there a period of time where these functions won't exist yet.

On second thought, this error looks like you tried to use `ConjureShadowSelect` when the nREPL session you were connected to was _already_ ClojureScript / Shadow: `Assumed session: Vizsla (ClojureScript)`.

So it looks like you reconnected to a running shadow-cljs nREPL that you'd already configured for shadow-cljs (this is persistent in Conjure, unlike most other tools!). So you don't need to run `ConjureShadowSelect` in this case, if you've run it once in a REPL and you don't restart it or kill the session you can just start evaluating ClojureScript!

If you want to refresh the sessions you can use `<prefix>sQ` to kill all sessions and start a new one, then you can select your shadow build again. It might be worth having a read about nREPL sessions and Conjure's tooling for them in `:help conjure-client-clojure-nrepl`.

**Comment by knubie** [comment]
Hey @Olical thanks for the follow up.

> On second thought, this error looks like you tried to use ConjureShadowSelect when the nREPL session you were connected to was already ClojureScript / Shadow: Assumed session: Vizsla (ClojureScript).

Yep, this turned out to be the situation. Thanks for the help, and thanks for making such an awesome tool!
