### ISSUE TITLE
Ensure initial make compile works

### ISSUE THREAD

**Issue by jorinvo** [Olical/conjure#17]
Hi, I just installed conjure and the `make compile` step failed.
I tried it manually then and got this:

```
$ make compile
rm -r classes
rm: classes: No such file or directory
make: *** [clean] Error 1
```

After running `mkdir classes`, I could compile without any issues.
Should be a quick fix.
Thank you for starting this projects! Great to see innovation in vim tooling for Clojure happening :)

**Comment by Olical** [comment]
Fixed in `v0.7.1`, thank you very much for reporting this! I just had a brain fart I guess. It's only noticeable on fresh installs.

**Comment by Olical** [comment]
Now I'm off to work, I did this while eating cereal and making coffee :laughing:

**Comment by jorinvo** [comment]
Thank you :)
