### ISSUE TITLE
Execution error (NullPointerException) at nrepl.middleware.interruptible-eval/evaluate$fn (interruptible_eval.clj:91)

### ISSUE THREAD

**Issue by knubie** [Olical/conjure#170]
Sometimes when `:ConjureShadowSelect memo`, this error occurs:
```
; shadow-cljs (select): memo
; (err) Execution error (NullPointerException) at nrepl.middleware.interruptible-eval/evaluate$fn (interruptible_eval.clj:91).
; (err) null
```

**Comment by Olical** [comment]
This sounds like a timing thing in shadow-cljs to me? I don't _think_ there's anything I can do from Conjure for this.

Is it only on the first call just after you started it all up? Is your browser connected to the other side of shadow-cljs before you run it?

**Comment by Olical** [comment]
Is this still happening? Or was it related to the other issue? :thinking: #168 I'm guessing still happening to some extent? If so, I'm really sorry! I hope I can work it out for you soon!

**Comment by knubie** [comment]
@Olical Thanks for following up. It could very well be related to #168. I was waiting until I saw the error again before I updated the issue so I could provide more information, but haven't seen it since I created this ticket. I do remember not being able to eval things after I got this message, so I'm not sure.

I will close the issue for now. I just wonder if this *is* due to something simple like trying to connect to a session you're already connected to, could there be a more helpful error message, and if that should be implemented by conjure, or shadow-cljs or who?

**Comment by Olical** [comment]
Hmm I hope it's something simple, but yeah, I think you're right. This is kind of something that could be put into the "user error" bucket (maybe) but at the same time it's _really_ easy to make this mistake. And the tool should help the user avoid this whole situation! So maybe just preventing using "shadow select" if you're already in a CLJS REPL would be the way to go :thinking: and printing a message that explains this whole thing, or links to an FAQ.
