### ISSUE TITLE
Odd interaction between eval-at-mark and vim-repeat 

### ISSUE THREAD

**Issue by arthropodSeven** [Olical/conjure#172]
Howdy! 

Ran into this while running conjure-school: At lesson 5, when I attempt to invoke the evaluate-at-mark command, I type `<LL>em` and before I can supply the mark, some evaluation happens immediately. This string gets inlined at the cursor position: 

```
ilent! call repeat#set('\em', v:count)
```

In gif form:
![2021-02-08 18 50 40](https://user-images.githubusercontent.com/36243137/107296038-9aa5b600-6a3e-11eb-962f-f705f83ecb99.gif)

If difficult to reproduce, I can come up with a minimal init.vim. 

Cheers!

**Comment by Olical** [comment]
Fixed this bug on `develop`! Thank you for pointing it out, so sorry it impacted your `ConjureSchool` :disappointed: that's the literal worst time for this sort of thing to happen. Just having a poke around to see how hard it would be to get `vim-repeat` actually repeating your "eval at mark" with the mark you selected.

**Comment by Olical** [comment]
Did it :slightly_smiling_face: so you can now use eval at mark again _and_ it actually works with vim-repeat. Releasing!

**Comment by arthropodSeven** [comment]
Thanks a ton!
