### ISSUE TITLE
How can I configure the HUD so that it appears at the bottom of the screen?

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#176]
I'm trying to configure conjure so that it looks like the  docked preview window in the plugin [float-preview.nvim](https://github.com/ncm2/float-preview.nvim).

This is because sometimes the result of some evaluation is pretty long, and a HUD on the top right corner is not enough. 

However, there seems no way I can config it. 

Could you help me figure out how to do this?

Thanks, man!

**Comment by dharrigan** [comment]
Hi,

Does `let g:conjure#log#botright = v:true` with `let g:conjure#log#hud#width = 1.0` not work for you?

**Comment by glyh** [comment]
> Hi,
> 
> Does `let g:conjure#log#botright = v:true` with `let g:conjure#log#hud#width = 1.0` not work for you?
> 
> https://github.com/Olical/conjure/blob/master/doc/conjure.txt#L386 onwards...

setting width works for HUD, but it seems the location of the HUD can't be change(not the log buffer)

**Comment by Olical** [comment]
Yep, setting the position isn't an option I have right now but I'm happy to add it! With the caveat of: It might cover your cursor if it's at the bottom of the screen! Any thoughts on that?

The current mechanism is designed to be simple yet effective at never covering what you're looking at. I haven't iterated on that design much since I first wrote it though, so there's almost definitely a lot of room for improvement.

So you want it to _always_ appear at the bottom of the editor? Regardless of where your cursor happens to be?

**Comment by glyh** [comment]
@Olical  Maybe it's better if the HUD take care of your cursor position, so it never cover the cursor.

**Comment by Olical** [comment]
Isn't that what it does already? Like the HUD tries to avoid covering your cursor? Maybe instead, I could make it so it prefers the bottom first, but will move to the top if it'll cover your cursor?

**Comment by Olical** [comment]
Working on adding more config here to make it possible to say "prefer the bottom but move to the top if required" etc :)

**Comment by glyh** [comment]
It's not. I tried to set the width of HUD to 1.0, and put my cursor in the first row, and conjure HUD will cover my code in the first few lines.

**Comment by Olical** [comment]
Ah yeah, aware of that one, actually working on a solution for it right now :smile: while giving you the choice of which position you want it to default to.

**Comment by glyh** [comment]
@Olical Great, thank you!

**Comment by Olical** [comment]
Done on `develop`! It's muuuuuch smarter now. Try out this config :smile:

```viml
let g:conjure#log#hud#width = 1
let g:conjure#log#hud#anchor = "SE"
```

**Comment by glyh** [comment]
Great, thanks! I'm closing this.
