### ISSUE TITLE
Difficult to configure which client to use for dotted filetypes

### ISSUE THREAD

**Issue by taw10** [Olical/conjure#177]
Following on from the initial mention in #129:

It seems difficult to set configuration options for "dotted filetypes", as used for example in this [Guile mode for Vim](https://gitlab.com/HiPhish/guile.vim).  The idea is that you can make small subtype-specific changes to another mode.  For example, filetype "scheme.guile" takes all the settings for filetype "scheme", then adds the settings for "guile" (in that order).  That way, Guile mode doesn't need to replicate all of the contents of Scheme mode, and also benefits from any updates to Scheme mode.

Unfortunately, it seems to be impossible to choose a client for this kind of mode.  For example, the following does not work because the dot has a special meaning in VimL:
```
let g:conjure#filetype#scheme.guile = "conjure.client.guile.socket"
----> E121: Undefined variable: g:conjure#filetype#scheme
```
The closest I could get was the following, which suggests that it will never be possible from VimL because the variable name is invalid:
```
let {"g:conjure#filetype#scheme.guile"} = "conjure.client.guile.socket"
----> E461: Illegal variable name: conjure#filetype#scheme.guile
```
The only way to select the client seems to be by modifying config.fnl, which is obviously unacceptable for general users.

I think the best way to address this would be for Conjure to behave essentially the same way as Vim, splitting the mode into its parts, then work from right to left, taking the first match.  The following configuration would then work for filetype 'scheme.guile' or 'guile':
```
let g:conjure#filetype#guile = "conjure.client.guile.socket"
```
If one never used any other type of Scheme, one could also just choose the client for filetype 'scheme'.

**Comment by Olical** [comment]
Ah that sucks, something I didn't think about at the time, I didn't even know this dotted notation was a thing. The more you know! :rainbow: :star2:

I kinda like the idea of walking through to find a match... I'll have a think!

**Comment by Olical** [comment]
At the moment I kinda agree that just specifying `guile` then matching against `guile` or `scheme.guile` makes the most sense. We could default `scheme` to use `guile` too since it's a decent default which is easy to switch out when there's other Schemes. Not sure if that's worth it though.

**Comment by Olical** [comment]
I've added partial dotted filetype matching on `develop`, let me know what you think! So now the `scheme.guile` filetype will first check for a `guile` client then `scheme`.

**Comment by taw10** [comment]
Works for me!  Thanks!

**Comment by HiPhish** [comment]
Sorry to open this old issue, but has the commit for supporting dotted file types been reverted? It is not working for me neither on `master`, `develop`, nor `4.21.0`. The manual is not mentioning dotted file types either.

**Comment by taw10** [comment]
The behaviour was changed with [release 4.16.0](https://github.com/Olical/conjure/releases/tag/v4.16.0) due to some nasty issues with determining the file type.  See the 6th, 7th and 9th points in the release notes.  You have to choose a client for overall filetype 'scheme' instead.  Here's what I have in my init.lua, because I only use Guile: `vim.g['conjure#filetype#scheme'] = 'conjure.client.guile.socket'`

**Comment by HiPhish** [comment]
I see, thank you.
