### ISSUE TITLE
Persistent REPL State

### ISSUE THREAD

**Issue by hendersonreed** [Olical/conjure#180]
I've been reading through the documentation and poking at Conjure, and I wanted to say thanks for developing this! It's super cool, and a great user-interface achievement - much more interactive than say, vim-slime (not to denigrate vim-slime, which I still love for languages and purposes that Conjure can't yet handle.)

I was curious though about specifically how state is handled inside Conjure. In all my testing (with Fennel exclusively so far, though I'm curious about Racket as well), it looks like I need to evaluate everything in one go, i.e. I can't define a function, evaluate it with `<leader>er`, write a line that calls the defined function, and then evaluate _just the new code_. Every time I do so, I get a compile error due to not being able to locate the defined function.

Just so I'm being totally clear, here's a simple example:

```
(fn add3 [ a b c ]
  (+ a b c))

(add3 1 2 3)
```

With the above code, I can evaluate `add3` with one command, but when I go to evaluate `(add3 1 2 3)` on its own I get a compile error. Evaluating the entire buffer works fine and as expected.

I'm assuming then that each evaluation is one-and-done, unless I've uncovered some kind of bug?

**Comment by taw10** [comment]
```:help conjure-client-fennel-aniseed``` should answer all your questions.  It definitely does work the way you expect/want it to, but there's a subtlety when running Fennel code within Neovim (the default).  You have to use some special functions for declaring functions - use ```defn``` instead of ```fn``` to make your example work.
Alternatively, switch to the "stdio" Fennel client, which uses an external Fennel process rather than running within Neovim.  Put the following in your init.vim: ```let g:conjure#filetype#fennel = "conjure.client.fennel.stdio" ``` (except.. hmm.. on a brief test just now, it seems like something is rather horribly broken with the stdio client on my system.  Stand by for more details...)

**Comment by Olical** [comment]
Took the words right out of my mouth :smile:

Aniseed comes with it's own module macros and ways to define things in the style of Clojure. This gave me farrrr more control than vanilla Fennel or Lua allows. I designed it to make it easier for me to build larger Fennel programs (Conjure itself), so I hope those macros will be sufficient!

The only difference is using the `(module ...)` macro at the top of your file, `(def ...)` to export values and `(defn ...)` to export functions. `def-` and `defn-` define private functions and `defonce` allows you to define stateful things you don't want blown away on each eval. Just for a few examples of what it gives you.

Treat the vanilla `(local ...)` and `(fn ...)` as ephemeral things you can rely on _within_ your functions.

And the stdio client requires you to have `fennel` installed on your system already (you can configure the command it executes to start it). You'll also need to make sure you don't have any special readline hooks until we find a way around in #166.

**Comment by hendersonreed** [comment]
Thanks so much for the info - this answers my question exactly.

I think I'll stick with the default - I'm encountering exactly the kind of issues mentioned in #166, so it's good to know there's work being done on it.

Thanks so much for the help!

**Comment by Olical** [comment]
Hooray! Glad to hear that!

The default ([Aniseed](https://github.com/Olical/aniseed)) is designed for building Neovim plugins (which is how Conjure is built) and configuring your editor (as a replacement for viml or lua). The stdio client is for working on Fennel projects outside of Neovim that stand alone. I hope that clarifies things!

I'll close this now but feel free to reopen or report other issues if you're struggling with something. Might also be worth hopping into https://conjure.fun/discord too if you want to chat about things or ask questions :smile:
