### ISSUE TITLE
Ensure Clojure sets are evaluated as sets, not maps, when unwrapped

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#190]
If you eval `(first #{1 2 3})` in Clojure you'll get... I mean... something. Order in sets isn't defined.

If you however eval `#{1 2 3}` you'll get an error because conjure actually evaluated `{1 2 3}`, an uneven map!

The Conjure client should check for a proceeding `#` when the first character in the evaluated string is a `{`. If there's a `#` just before it in the buffer (hopefully I can work this out!) then it should prepend the string with a `#` before sending it off for eval.

This isn't great and it's kinda awkward to be hunting for things like this. My hope is that, once again, tree-sitter support will make all of these hacks magically go away because I won't need to perform ad-hoc parsing, tree-sitter will have done it for me!

Another approach may be to add a hook for clients to define that the extract module talks to. It could ask that function if it should expand a given string or not to solve this problem in a more general way.

**Comment by Olical** [comment]
I suppose this probably applies to `#(...)` functions too! Maybe a more general solution of "no, expand more to the left` predicate functions would make a lot of sense.

**Comment by glyh** [comment]
Maybe consider embrace treesitter as the default config for future? 

These selection can be better recognized, with out adding edge cases. 

![image](https://user-images.githubusercontent.com/12870742/129285839-3120b367-c409-43ea-827f-dec507f1baec.png)

**Comment by Olical** [comment]
This is fixed in Clojure when you use tree sitter! All of these work now although the quoted forms have to be evaluated from the first character to be actually quoted.

```clojure
#{:a :b :c}
#?(:clj :hi-clojure :cljs :hi-cljs)
#(+ 1 %)
'(+ 10 20)
`(+ 10 20)

```
