### ISSUE TITLE
Create a Neovim starter kit for people who are interested but have no config yet

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#191]
I'm thinking of calling it `magic-kit` or something like it. It'll basically be a starter pack you fork and clone into your Neovim configuration directory.

It'll come with everything you need to work with every Conjure supported language as well as a few other essentials I think are important such as plugin management and Aniseed based configuration.

So this might not be something I add to this repo, but it'll be another sister to the Conjure and Aniseed projects. It's basically a starter kit that I can point people who are unfamiliar with Neovim at.

The only thing I worry about is people relying on it then constantly adding things through PRs. I would like it to be minimal and a starter pack, you can fork it to add what you want, it's not supposed to be a Doom Emacs / Spacemacs. Just a ground floor that will let you work with Clojure et al.

**Comment by jcmkk3** [comment]
Arne was doing something similar to this for Emacs ([called corgi](https://github.com/plexus/corgi)). Maybe you could get some ideas through his approach there.

**Comment by semperos** [comment]
FWIW, as someone with a lot of Clojure experience using Emacs but no existing Vim or Neovim config, I opted to [nab this directory](https://github.com/Olical/dotfiles/tree/master/stowed/.config/nvim) from your dotfiles repo @Olical and it has been a solid but not overwhelming starting point.

**Comment by aleksandersumowski** [comment]
Just to point to existing projects: https://github.com/NTBBloodbath/doom-nvim looks very interesting! There is also https://github.com/SpaceVim/SpaceVim but it's not Neovim specific

**Comment by Olical** [comment]
For clarification, this would be a starter kit for Conjure + Aniseed, so all the Fennel based configuration is there and some essentials for autocompletion etc but not much else. The idea being that you fork / copy it and modify, it wouldn't be the kind of IDE like experience you get from doom / spacemacs etc. Just an opinionated starting point.

**Comment by Olical** [comment]
Still need to work on this, but progress is here: https://github.com/Olical/magic-kit

**Comment by Olical** [comment]
A few of my colleagues use this day to day now instead of Doom Emacs or Spacemacs, so I'm happy to close this!
