### ISSUE TITLE
Eval in stdio fennel should preserve local values

### ISSUE THREAD

**Issue by TravonteD** [Olical/conjure#192]
When using conjure with plain fennel (no aniseed), I define my requirements at the top of the page and eval it like this.

```fennel
(local yaml (require :yaml)) ; => nil
```

This executes correctly returning `nil`, however when evaluating a form that uses that locally declared value I get an error.

For Example, when evaluating this code after the line above
```fennel
(λ get-config []
  (with-open [file (io.open "test.yml")]
    (yaml.load file))) ; => Compile error...
```

I receive this error from conjure's repl:

`unknown global in strict mode: yaml`

The ideal behavior is that declared locals would remain available for future evaluations.
Currently the workaround to this is wrapping everything in a `do` form, but this isn't hdeal sense I need to remove it again before committing whatever progress I've made.

**Comment by Olical** [comment]
This does work for me, are you sure you're using the correct Fennel client? You should see the following at the top of the log if so:

```fennel
; "fennel" (started)
Welcome to Fennel 0.8.1 on Lua 5.2!
Use ,help to see available commands.
Try installing readline via luarocks for a better repl experience.
```

**Comment by TravonteD** [comment]
Yep, you're right. I was using the neovim internal client. That one doesn't work without aniseed correct?

**Comment by Olical** [comment]
Correct, the default client is all about modifying your current Lua state inside Neovim through Aniseed/Fennel. So the default Fennel client is very tied to Neovim and my Aniseed tooling. Glad you got it working though! :smile:
