### ISSUE TITLE
Error while opening Clojure(Script) files

### ISSUE THREAD

**Issue by mharju** [Olical/conjure#195]
Thanks so much for your efforts in this project. I've been using this a long time and I've been very happy with it!

Recently I've seem to have gotten this error (reproduces on both of my macs with the latest Conjure)

```
Error executing vim.schedule lua callback: ....local/share/nvim/plugged/conjure/lua/conjure/buffer.lua:86: 
Vim(lua):E5105: Error while calling lua chunk: ....local/share/nvim/plugged/conjure/lua/conjure/bridge.lua:42: attempt to concatenate local 'f' (a nil value)
```

Evaluation and all other features seem to be working anyhow. Any ideas where to start looking for the problem – is it my configuration or has this occurred to someone else as well?

Thanks!

**Comment by Olical** [comment]
Thank you for bringing this to my attention and I'm sorry for the error! I'll have a look now and see if I can spot anything.

I can't reproduce this so far though, I'm connected to a shadow-cljs REPL and I haven't seen any errors, working as expected 🤔

**Comment by Olical** [comment]
So a couple of questions:

 1. When does this error occur? Is it when you open your first Clojure file or when you try to piggieback into the ClojureScript session?
 2. Does pinning to an older version help? This will help you carry on working with a version that doesn't error while also helping me narrow down the possible problem, win win 😄 

Thank you for taking the time to report this, I hope to get it fixed soon!

**Comment by mharju** [comment]
OK, since you were not able to replicate it, it became certain that this has to do with my own doings... And sure enough, when I disabled my own CLJS helper plugin (that piggybacks Conjure), the issue disappeared.

So, aplologies for shifting the blame!

**Comment by Olical** [comment]
Oh nice! I'm glad you found it! I'd be happy to help with your helper plugin though at some point, I may have made an internal breaking change if you were relying on something inside Conjure's modules?

I did change the `mapping.buf` function at one point, which I suspected was where the error was coming from but wasn't sure. I really need to get it to print the full stack trace somewhere, the current errors aren't that helpful IMO. Maybe nvim is just cutting the rest of the info off but it's in the original string 🤔

**Comment by mharju** [comment]
https://github.com/mharju/clj-helpers/blob/master/fnl/clj-helpers/main.fnl#L16 There's the failing line, I think? I'm a complete beginner in fennel, nvim scripting et al. so aplologies in advance for any odd things in there :)

**Comment by Olical** [comment]
Ah yeah, I think it's from my buf change when I introduced commands for every mapping.

```
(defn mappings []
  (mapping.buf :n "js" :clj-helpers.main :jump-to-current-kw-symbol))

;; should be

(defn mappings []
  (mapping.buf :n nil "js" :clj-helpers.main :jump-to-current-kw-symbol))
```

Which says "I don't want a command automatically generated for this mapping". There's always going to be _some_ risk to internals changing, but not much and the pay off of leaning on Conjure's internals is worth the risk most of the time I think 😅 sorry for breaking your code!

**Comment by mharju** [comment]
> sorry for breaking your code!

I think it's always the caller to blame for relying on iternals of another tool ;)

Thanks for your help!
