### ISSUE TITLE
ConjureCljRunCurrentTest fails when deftest has non-trivial metadata

### ISSUE THREAD

**Issue by semperos** [Olical/conjure#196]
Thanks for your contributions to Clojure/Lisp tooling!

When invoking `ConjureCljRunCurrentTest` with metadata like this:

```clj
(deftest
  ^{:alpha [:beta :gamma]}
  test-my-test
  ,,,)
```

Conjure [appears](https://github.com/Olical/conjure/blob/df50b5ed59eb3505e7832895605156a89dddbdfd/fnl/conjure/client/clojure/nrepl/action.fnl#L405) to extract the whole form, split on whitespace, skip an item starting with `^`, but then assumes the next form is the name of the test. For simple `^:integration` or similar metadata, this works fine; for something like the above, one gets an error like:

```
; run-current-test: [:beta
; (err) Syntax error reading source at (REPL:1:50).
; (err) Unmatched delimiter: )
```

A general solution would be to have `ConjureCljRunCurrentTest` have Clojure `read` the whole extracted test form, and then Conjure could consistently rely on the second form being the name of the test.

(Aside: You've mentioned a desire to try out tree-sitter. There's also the Clojure-specific [sci](https://github.com/borkdude/sci) tool, which is performant enough to be invoked in a case like this, but is not a full Clojure implementation and obviously doesn't support the other Lisps that Conjure does.)

I've cobbled together the following, which leverages the nREPL connection to do the reading. This successfully extracts the name, but then fails when trying to continue with running the test. I've not familiarized myself deeply with Conjure+nREPL internals, so there are likely wild mistakes here:

```clj
;; Naively escapes double quotes
(defn escape-as-clojure-string
  [form]
  (form:gsub "\"" "\\\""))

(defn run-current-test-attempt []
  (try-ensure-conn
    (fn []
      (let [form (extract.form {:root? true})]
        (when form
          (server.eval
            {:code (.. "(clojure.core/read-string (quote \"" (escape-as-clojure-string (a.get form :content)) "\"))")
             :context (extract.context)}
            (fn [read-msg]
              (let [test-name (extract-test-name-from-form (a.get read-msg :value))]
                (when test-name
                  (print (.. "NAME: " test-name))
                  (log.append [(.. "; run-current-test: " test-name)]
                              {:break? true})
                  (require-ns "clojure.test")
                  (server.eval
                    {:code (.. "(clojure.test/test-vars"
                               "  [(doto (resolve '" test-name ")"
                               "     (assert \"" test-name " is not a var\"))])")
                     :context (extract.context)}
                    (nrepl.with-all-msgs-fn
                      (fn [msgs]
                        (if (and (= 2 (a.count msgs))
                                 (= "nil" (a.get (a.first msgs) :value)))
                          (log.append ["; Success!"])
                          (a.run! #(ui.display-result
                                     $1
                                     {:simple-out? true
                                      :ignore-nil? true})
                                  msgs))))))))))))))
```

Happy to contribute if there's a particular direction you'd like this to go.

**Comment by Olical** [comment]
Ah that's frustrating! Sorry about the issue, indeed I'd like to be able to query tree-sitter for this sort of information in the future, but I'm only relying on tree-sitter for optional things so far, nothing in the critical path can rely on it until Neovim 0.5 is the stable version released everywhere.

The "get Clojure to read it" approach seems like it'll work fine in most cases (not sure about CLJS) but the added complexity is something I'd like to avoid if possible. I'll see if I can write some more robust Fennel parsing first, I'm pretty sure I addressed this exact issue elsewhere at some point. Or maybe that was just the `^:keyword` syntax.

Let's see if some slightly better string fudging can be good enough for now. It might just be that it's almost working but the current Lua pattern just needs to account for more new lines or something simple like that.

**Comment by Olical** [comment]
Ah! I think I did similar parsing to extract the namespace name! I'll see if I can extract and reuse that1

**Comment by Olical** [comment]
Should be fixed on develop, let me know how it works for you! And thanks for reporting!

**Comment by semperos** [comment]
Thank you for fixing this! Works as advertised with the metadata-riddled tests I'm writing.
