### ISSUE TITLE
stdio REPLS ignore error return status

### ISSUE THREAD

**Issue by enderger** [Olical/conjure#197]
In the current version of Conjure, it is possible for certain stdio REPLS to silently fail to start without any indication in the log buffer. This can lead to a large amount of tedious debugging to find why the REPL is misbehaving.

**Comment by Olical** [comment]
Hi there, which client / filetype is this? And could I have a little more context, such as did you have the target REPL installed on your system?

**Comment by Olical** [comment]
Confirmed on Discord, this weird silent death happens when `mit-scheme` (or whatever REPL you're trying to start) isn't installed. Need to ensure that error bubbles up.

**Comment by Olical** [comment]
```scheme
; Sponsored by @jkrasnay ❤
; --------------------------------------------------------------------------------
; mit-schem (ENOENT: no such file or directory)
```

Should do the trick 😄 this is on develop.

**Comment by enderger** [comment]
Cool, thanks!
