### ISSUE TITLE
Document the 'prompt-pattern' option

### ISSUE THREAD

**Issue by enderger** [Olical/conjure#198]
Currently, there is no mention of the `prompt-pattern` option anywhere in the documentation. This can lead to a large amount of confusion, especially when trying to use different Scheme implementations to MIT/GNU.

**Comment by Olical** [comment]
Ah, I thought that was already there, I'll get something added to the clients that use it and replace the hyphen with an underscore.

**Comment by Olical** [comment]
Added to all help text files and the scheme wiki entry
