### ISSUE TITLE
add user configurable config to kaocha test runner

### ISSUE THREAD

**Issue by Pancia** [Olical/conjure#201]
I would like to be able to pass a custom config map to the kaocha runner. 
In my case, the projects I'm working on have standardized to using `tests.edn` for the CI configuration, and `tests.local.edn` for developer specific config that is not committed to git.

To add a slight monkey wrench, there is not always a `tests.local.edn` file in every project, so I'd like to be able to set something like this: `(if (.exists (new java.io.File \"tests.local.edn\")) {:config-file \"tests.local.edn\"} {})`

**Comment by Olical** [comment]
I've added a way to do this to `develop` you can try something like this!

```viml
let g:conjure#client#clojure#nrepl#test#call_suffix = "{:kaocha/color? false, :config-file (when (.exists (new java.io.File \"tests.local.edn\")) \"tests.local.edn\")"
```

Let me know what you think, not sure if I'm fully happy with it, maybe I should merge these maps and make it slightly more opinionated so you don't need to add that `:kaocha/color? false` 🤔

**Comment by Olical** [comment]
Oops, misclick. But I think this will be closed when I release, probably tomorrow morning?
