### ISSUE TITLE
Babashka eval exceptions not showing properly

### ISSUE THREAD

**Issue by victorb** [Olical/conjure#206]
**Versions used**

- Ubuntu 18.04.5 LTS
- Clojure deps 1.10.1.536
- nrepl/nrepl 0.8.3
- babashka v0.4.0
- NVIM v0.5.0-dev
- Conjure v4.18.0

**In Short**

When getting an exception from Babashka (started with `bb --nrepl-server`), it shows `; (err) clojure.lang.ExceptionInfo: ` without any further details. nrepl started via Clojure Deps shows `; (err) Execution error (IndexOutOfBoundsException) at user/eval1795 (REPL:6).` for the same error.

**To Reproduce**

The following test script:

```clojure
(def test-vector [1 2 3])
;; This should obviously work
(nth test-vector 2)
;; This should obviously not work
(nth test-vector 3)
```

Starting a nrepl server with `bb --nrepl-server` and evaluating the test script:

```
; eval (buf): ...nrep/test-bb-error.clj
#'user/test-vector
3
; (err) Execution error (IndexOutOfBoundsException) at user/eval1829 (REPL:5).
; (err) null
```

While evaluating the same test script with Clojure Deps connected to Conjure instead of Babashka produces the following output:

```
; eval (buf): ...nrep/test-bb-error.clj
#'conjure.internal/test-vector
3
; (err) clojure.lang.ExceptionInfo: 
```

If we run the test script directly with Babashka, we get a nice exception instead:

```
$ bb test-bb-error.clj
----- Error --------------------------------------------------------------------
Type:     java.lang.IndexOutOfBoundsException
Location: /test-bb-error.clj:5:1

----- Context ------------------------------------------------------------------
1: (def test-vector [1 2 3])
2: ;; This should obviously work
3: (nth test-vector 2)
4: ;; This should obviously not work
5: (nth test-vector 3)
   ^---

----- Stack trace --------------------------------------------------------------
clojure.core/nth - <built-in>
user             - /test-bb-error.clj:5:1
```

**Comment by Olical** [comment]
So it looks like (with debug mode on) that's actually all babashka is sending, so I'll probably go check for issues on that side before trying to patch around them in Conjure.

```clojure
; --------------------------------------------------------------------------------
; eval (current-form): (nth test-vector 3)
; debug: send
{:code "(nth test-vector 3)"
 :column 1
 :file "/home/olical/repos/Olical/conjure/dev/clojure/src/dev/bb-sandbox.clj"
 :id "6572bf58-45c9-4654-8bf0-2fc01422ea19"
 :line 7
 :nrepl.middleware.print/options {:associative 1 :length 500 :level 50}
 :nrepl.middleware.print/print "conjure.internal/pprint"
 :ns "bb-sandbox"
 :op "eval"
 :session "d0540c9c-f3eb-4356-b5cf-5f15a47fe1b9"}
; debug: receive
{:err "clojure.lang.ExceptionInfo: 
"
 :id "6572bf58-45c9-4654-8bf0-2fc01422ea19"
 :session "d0540c9c-f3eb-4356-b5cf-5f15a47fe1b9"}
; (err) clojure.lang.ExceptionInfo: 
; debug: receive
{:ex "class clojure.lang.ExceptionInfo"
 :id "6572bf58-45c9-4654-8bf0-2fc01422ea19"
 :root-ex "class clojure.lang.ExceptionInfo"
 :session "d0540c9c-f3eb-4356-b5cf-5f15a47fe1b9"
 :status ["eval-error"]}
; debug: receive
{:id "6572bf58-45c9-4654-8bf0-2fc01422ea19"
 :session "d0540c9c-f3eb-4356-b5cf-5f15a47fe1b9"
 :status ["done"]}
```

**Comment by Olical** [comment]
To enable debug, for future reference, you can use `:let g:conjure#debug = v:true` and it'll log all nREPL messages in either direction.

**Comment by Olical** [comment]
I've asked about this in the babashka clojurians channel but I suspect some more will need to be added to https://github.com/babashka/babashka.nrepl/blob/d9b63bbadce04799ef791c02a7066dd3197aa1b9/src/babashka/nrepl/impl/utils.clj#L26 to pass through different parts of the exception depending on what kind of exception it is. Although I haven't given this much thought yet, so I'll see!

**Comment by Olical** [comment]
Babashka side issue here: https://github.com/babashka/babashka.nrepl/issues/40

**Comment by Olical** [comment]
Babashka v0.4.5+ will now print the actual error and where it occurred! It's not as rich as the full STDIO based REPL errors, but it's enough to let you know what's wrong. I'd love the full errors that you get in the CLI in Conjure's output but that's something that has to be implemented in the bb.nrepl repo separately.
