### ISSUE TITLE
Clojure "Namespace not found" if `)` appears before ns name

### ISSUE THREAD

**Issue by frenchy64** [Olical/conjure#207]
Evaluating a form with `<leader>ee` throws an error `; Namespace not found: ;` on the following namespace:

```clojure
(ns ;)
   foo)
```

This is a minimal example, I narrowed it down from something like this and I think the closing paren is the commonality.

```clojure
(ns ^{:doc "...... (....) ....."}
   foo)
```

**Comment by Olical** [comment]
Oh yikes, that's not good... and not that easy to fix 🤔 if only tree-sitter was supported in everyone's setup... maybe one day. Almost all of my current larger issues revolve around not being able to parse and understand code well enough from the raw source alone. I'll add another test for this and see if I can find a way around.

Luckily Lua's string pattern system has support for matching pairs of things. Maybe I can ignore "quoted" things entirely. Won't fix comments with unbalanced parens though.

Maybe I can strip all comments too...

**Comment by Olical** [comment]
Should be fixed on develop, let me know what you think! I just stripped line comments before attempting to parse the namespace name out.

**Comment by frenchy64** [comment]
I guess that was a different bug, because this is the new minimal case! (It was a very long docstring!).

```clojure
(ns ^{:doc "






















"}
  fr.jeremyschoffen.prose.alpha.reader.grammar
  (:require
    [instaparse.core :as insta]
    [instaparse.combinators :as instac]

    [fr.jeremyschoffen.prose.alpha.reader.grammar.utils :as gu :include-macros true]))
```

**Comment by Olical** [comment]
Ah that's probably to do with https://github.com/Olical/conjure/blob/5d3b1afe96d11f059016d0b556f2797b54af916e/doc/conjure.txt#L516-L524

**Comment by frenchy64** [comment]
Fixed, thanks!
