### ISSUE TITLE
Use of parentheses as character literals breaks ConjureEvalRootForm

### ISSUE THREAD

**Issue by Diskriminantti** [Olical/conjure#209]
Using ConjureEvalRootForm to evaluate the lines with "evaluate-this" doesn't work properly.  It will also evaluate lines up to and including the line with the bracket character literal. I've only tested this with Clojure.

```clojure
(def evaluate-this (range 3))
(def a \))

(def b \()
(def evaluate-this-v2 (range 3))
```
Depending on the order of the bracket character literals, everything in between can also get evaluated.

```clojure
(def b \()
(def evaluate-any-of-the-lines (range 3))

(println "Everything evaluates.")

(def evaluate-any-of-the-lines-v2 (range 3))
(def a \))
````
There are also some issues with using ConjureEvalCurrentForm on a line with a bracket character literal, but hopefully fixing the underlying issue fixes it too.

**Comment by Olical** [comment]
Should be fixed on `develop`!
