### ISSUE TITLE
Allow user to hide the babashka buffer when babashka is launched

### ISSUE THREAD

**Issue by dharrigan** [Olical/conjure#210]
Since the awesome-0 9000 auto jack in to babashka came in, what happens now is that a new buffer is automatically created that contains the output of the nrepl start, i.e.,

![babashka1](https://user-images.githubusercontent.com/427150/119966997-6e855500-bf9b-11eb-9e59-663349257297.png)

and `:buffers` shows this:

![babashka2](https://user-images.githubusercontent.com/427150/119967034-780ebd00-bf9b-11eb-8888-07e0abb16fd6.png)

This is pretty neat, however, I normally have only the buffers open in my editor that contains code that I'm working on, so having this new buffer appear is jarring when I move between the buffers using buffer previous and buffer next.

Please can you add in an configuration option that will hide this buffer from being opened so that I can opt-in to not have it appear.

Thank you.

-=david=-

**Comment by Olical** [comment]
`let g:conjure#client#clojure#nrepl#connection#auto_repl#hidden = v:true` should do the trick 🙂

**Comment by Olical** [comment]
I think it'll be useful for some to not hide it so I don't want to _always_ hide it, and I think it's only noticeable by people who are sensitive to their buffer list. So I'll default to displaying for now with an option for people who don't want or don't need to see it. Will reevaluate if people say that's not a good default though!

**Comment by dharrigan** [comment]
Sounds good to me! :+1

**Comment by dharrigan** [comment]
Works great! Thank you.
