### ISSUE TITLE
Vim:E731 error when slurping gzipped file in clojure

### ISSUE THREAD

**Issue by Akeboshiwind** [Olical/conjure#212]
# Description
When using the below reproduction steps I get the following error:
```clojure
; eval (root-form): (->> "/Users/oliverm/pro...
; --------------------------------------------------------------------------------
; localhost:64309 (Vim:E731: using Dictionary as a String): .nrepl-port
```

I'm not sure of the route cause of this, but I was at least able to reproduce :D

# Steps to reproduce

```bash
$ lein new gzip_bug
$ cd gzip_bug
$ echo "hi" > resources/my_file
$ gzip resources/my_file
$ cat > src/test/core.clj
(ns test.core)

(->> "./resources"
     clojure.java.io/file
     file-seq
     (remove #(.isDirectory %))
     (map slurp))
# NOTE: press Ctrl-D here 
$ nvim src/test/core.clj

# (in another shell)
$ cd gzip_bug
$ lein repl

# Then finally execute the form using :ConjureEvalBuf
```

The full session log is:
```clojure
; Sponsored by @Aljendro ❤
; --------------------------------------------------------------------------------
; localhost:64309 (connected): .nrepl-port
; --------------------------------------------------------------------------------
; Assumed session: Bernese Mountain Dog (Clojure)
; --------------------------------------------------------------------------------
; eval (buf): ...j/test/src/test/core.clj
nil
; --------------------------------------------------------------------------------
; localhost:64309 (Vim:E731: using Dictionary as a String): .nrepl-port
```

**Comment by Olical** [comment]
I don't _think_ this will happen any more 🤔 I think it was a temporary bug from when I was adding a notification about what nREPL port file was used for the connection. I'll investigate but if you could check again and see if you can reproduce it that'd be super helpful! Thanks for the thorough report!

**Comment by Olical** [comment]
I _can_ repro! Investigating.

**Comment by Olical** [comment]
I've worked out it's when this null byte is in the output string.

```edn
{:id "130d6fe2-db52-45b7-97d2-a246c4a9a006"
 :ns "test.core"
 :session "fcba79ee-903c-4543-b4da-5e3e7fcfc1ff"
 :value "((\\\031 \\� \\backspace \\backspace \\� \\� \\� \\` \\\000))"}
```

Now to work out why and get around it...

**Comment by Olical** [comment]
Minimal repro: `:ConjureEval "\0"`.

**Comment by Akeboshiwind** [comment]
That's amazing, thanks for the hard work 😁

**Comment by Olical** [comment]
I've realised you can also reproduce it in Janet! And I've narrowed it down to the line that causes it! This is probably the trickiest bug I've ever hit with Conjure, so congratulations 😅 

https://github.com/Olical/conjure/blob/643ae9bf5f08e752a22027628b69a31ce271f1b5/fnl/conjure/eval.fnl#L66

My current hunch is that the null byte is hitting a bug in Neovim's Lua to VimL interop layer. I'll have to see if I can work around it for now and get a repro for the Neovim team to address at some point.

**Comment by Olical** [comment]
Minimal repro without Conjure involved at all.

```fennel
(vim.fn.setreg "x" "\0")
```

**Comment by Olical** [comment]
I've pushed a workaround for this to `develop`, I'll raise a bug with Neovim or at least find an existing one.

**Comment by Olical** [comment]
I couldn't find a related bug so I've opened one: https://github.com/neovim/neovim/issues/14801

**Comment by Akeboshiwind** [comment]
That's amazing, thanks so much for figuring it out!
