### ISSUE TITLE
Forcing Clojure client on files with none standard extensions

### ISSUE THREAD

**Issue by xllora** [Olical/conjure#215]
I have some Clojure files that have a non standard file extension (e.f. `file.foo` instead). I was looking for a way to make Conjure Clojure client recognize them without much success. `ConjureConnect` fails with the error below when editing one of those non standard extension files. Any hints? 😄 

```
E5105: Error while calling lua chunk: .../home/xllora/.vim/plugged/conjure/lua/conjure/client.lua:349: attempt to concatenate a nil value   
```

**Comment by dharrigan** [comment]
Can you try doing `:filetype clojure` then retrying to connect?

**Comment by xllora** [comment]
It does not seem to like it.

```
E475: Invalid argument: clojure      
```

**Comment by xllora** [comment]
Also, for completion. I have this on my `.vimrc`

```
autocmd BufNewFile,BufRead *.EXTENSION set syntax=clojure    
```

Which does the setting (coloring etc.). My guess is that `Conjure` is missing the client https://github.com/Olical/conjure/blob/31820e386ce7a32488ad6b19033c17a8f05c36bf/lua/conjure/client.lua#L349

**Comment by xllora** [comment]
Silly me. 

```
:setfiletype clojure   
```

Thanks @dharrigan. This did it 😄
