### ISSUE TITLE
Hide the sponsor message?

### ISSUE THREAD

**Issue by HiPhish** [Olical/conjure#219]
I am really glad for you that you have people who support your project financially, but for me it's just annoying, especially with the big bright red heart emoji that stands out like a sore thumb. Is there a way to turn that message off or replace with with something of my own? You can put the list of sponsors at the end of the documentation if you really need them somewhere I guess.

I think a general information about the Conjure backend would be more useful, like "Conjure client using Fennel (Neovim) backend" or something like that. I'm sure your sponsor won't mind.

![Screenshot_20210621_231821](https://user-images.githubusercontent.com/4954650/122830883-4c0c0080-d2e9-11eb-83b7-a1ab1d6f30ce.png)

**Comment by emilaasa** [comment]
It's a vim buffer, dgg deletes the contents.

**Comment by taw10** [comment]
This isn't really a solution, but the appearance of the heart depends on your font and terminal settings.  For me (Fedora 33, Konsole, Cousine 10pt font), the heart appears the same colour as the surrounding text, quite small and unobtrusive.  I wouldn't know how to set things up for colour emojis in the terminal, even if I wanted them (which, like you, I don't).
![Screenshot_20210626_104241](https://user-images.githubusercontent.com/25135057/123507719-4c9af300-d66b-11eb-84dc-7b9c254a8b51.png)

**Comment by Olical** [comment]
Yep, mine has always been small, faint and grey. I've never seen it render as an actual emoji character.

I'm reluctant to add options for this since I don't want to encourage removal of that concept, I like the people that have put their own money forward to support me getting recognition. However, in the spirit of customisation, here's an autocmd that would do it for you.

```fennel
(do
  (nvim.ex.augroup :ConjureRemoveSponsor)
  (nvim.ex.au_)
  (nvim.ex.autocmd :BufWinEnter "conjure-log-*" "silent s/; Sponsored by @.*//e")
  (nvim.ex.augroup :END))
```

Requires a liiiitle translation to viml but still. I hope that helps!

**Comment by HiPhish** [comment]
The autocommand is good enough for me. I intentionally set up my fontconfig to have vibrant emoji because I use them for things like diagnostic symbols and debugger markers, I want those things to pop out.

**Comment by toniz4** [comment]
I think this could be a option, I apreciate the sponsors and love this project, but that message is a litte bit anoying IMO.

Displaying something like "Clojure (nREPL)" or "Racket (stdio)" would be more usefull.

And I don't mind the default beeing the sponsor message.

I came up with this:
```fennel
(defn- on-new-log-buf [buf]
  (set state.jump-to-latest.mark
       (nvim.buf_set_extmark buf state.jump-to-latest.ns 0 0 {}))

  (nvim.buf_set_lines
    buf 0 -1 false
    [(str.join [(client.get :comment-prefix) (client.get :repl-message)])]))
```
And in the client files: 
```fennel
(def repl-message "Clojure (nREPL)")
```

It would be simple to make a if statement deciding to show the sponsor message or not.

**Comment by kyleterry** [comment]
This message is really in your face every time I load and unload fennel and scheme files. I appreciate the workaround above, but this really should be smaller or even configurable to disable it. I occasionally work on a 720p display and this message damn-near covers the whole thing. I understand why you want to show off the sponsors, but why does it need to be so big?

**Comment by kyleterry** [comment]
My bad! I didn't see that the floating buffer was called the "hud" in the config. Now that I know I can disable it from popping up all the time, I'll keep the sponsor message in there :).
