### ISSUE TITLE
Running on Mac OS X

### ISSUE THREAD

**Issue by scotts777** [Olical/conjure#23]
I am attempting to run Conjure through nvim in the mac's Terminal bash, but I am getting an error when doing ConjureAdd.  It probably isn't a bug and more likely it is that I am new to nvim and doing something wrong.  But this plugin looks so good that it is finally pushing me to the vim side.  I  will understand if you deem it an issue with my setup and not a bug then please just close it.

I added this to my init.vim
`call plug#begin('~/.local/share/nvim/plugged')

Plug 'Olical/conjure', { 'tag': 'v0.8.2', 'do': 'make compile', 'for': 'clojure', 'on': 'ConjureAdd'  }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" Initialize plugin system
call plug#end()`

I did a successful PlugInstall.  I am running a prepl in another Terminal that I can successfully connect to with nc localhost port.  However, in nvim when I do a ConjureAdd {:tag :dev, :port 40404}, it opens a vertical split window, but I get this error message:

```clojure
Error from thread 'RPC message handler': #error {                                                                                                 
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops Numbers.java 1068]}]
 :trace
 [[clojure.lang.Numbers ops Numbers.java 1068]
  [clojure.lang.Numbers gt Numbers.java 259]
  [conjure.ui$append invokeStatic ui.clj 48]
  [conjure.ui$info invokeStatic ui.clj 68]
  [conjure.prepl$add_BANG_ invokeStatic prepl.clj 102]
  [conjure.main$fn__12976 invokeStatic main.clj 34]
  [conjure.main$fn__12976 invoke main.clj 33]
  [clojure.lang.MultiFn invoke MultiFn.java 229]
  [conjure.rpc$init$fn__11386 invoke rpc.clj 168]
  [clojure.core$binding_conveyor_fn$fn__5756 invoke core.clj 2030]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 628]
  [java.lang.Thread run Thread.java 835]]}
```

When I quit out of nvim, I see this message:  Conjure exited, restarting

Thanks for any assistance you may provide

**Comment by Olical** [comment]
Thanks for giving this early version a go! Problems are definitely expected
right now.

I would guess this is to do with a number nvim is reporting back when I ask
for a buffer line count or something.

Could I get your Neovim version and Conjure logs? There's instructions to
add logging in the issue template, I think you just set CONJURE_LOG_PATH in
your env when you run nvim.

If you can reproduce it and get me that log it'll probably have the answer
in there.

Thanks! I hope your week is off to a good start other than this 😄

**Comment by Olical** [comment]
Oh, just a hunch, does OSX have a /tmp anymore? I create the log buffer
there (it's not saved, it's just the path used for it since it's
consistent). If that's Linux only now that's explain it.

I can rethink the log buffer name if so!

**Comment by Olical** [comment]
I am informed by the OSX dev to my right that it does have a `/tmp`, so it's probably not the `/tmp/conjure.cljc` buffer not being created. I would _guess_ it's a setting in Neovim like "new lines at end of empty files" or something so the line count is reporting `nil` instead of `0`.

Your logs will prove this though, every RPC call gets written there when it's enabled so we'll see what Conjure asked and what it got back from Neovim :smiley: should be an easy fix.

**Comment by scotts777** [comment]
I really appreciate you taking the time to look into this.  Yes the /tmp exists and I can see the buffer in the split.  Here is the log output.
`INFO [conjure.dev:17] - Logging initialised
 INFO [conjure.rpc:132] - Starting RPC loops
 TRACE [conjure.rpc:162] - Received RPC message: {:type :notify, :method :add, :params ["{:tag :dev, :port 40404}"]}
INFO [conjure.prepl:110] - Adding :dev 127.0.0.1 40404
TRACE [conjure.rpc:151] - Sending RPC message: {:type :request, :id 1, :method :nvim-execute-lua, :params ["return require('conjure').upsert_log(...)" ("/tmp/conjure.cljc" 40 false false)]}
TRACE [conjure.rpc:120] - Sent request, awaiting response: {:type :request, :id 1, :method :nvim-execute-lua, :params ["return require('conjure').upsert_log(...)" ("/tmp/conjure.cljc" 40 false false)]}
TRACE [conjure.rpc:154] - Sent!
TRACE [conjure.rpc:162] - Received RPC message: {:type :response, :id 1, :error nil, :result nil}
TRACE [conjure.rpc:26] - Received response: {:type :response, :id 1, :error nil, :result nil}
TRACE [conjure.rpc:120] - Sent request, awaiting response: {:type :request, :id 1, :method :nvim-buf-line-count, :params [nil]}
TRACE [conjure.rpc:151] - Sending RPC message: {:type :request, :id 1, :method :nvim-buf-line-count, :params [nil]}
TRACE [conjure.rpc:154] - Sent!
TRACE [conjure.rpc:162] - Received RPC message: {:type :response, :id 1, :error [0 "Wrong type for argument 1, expecting Buffer"], :result nil}
TRACE [conjure.rpc:26] - Received response: {:type :response, :id 1, :error [0 "Wrong type for argument 1, expecting Buffer"], :result nil}
ERROR [conjure.nvim:12] - Error while making nvim call {:method :nvim-buf-line-count, :params [nil]} -> {:error [0 "Wrong type for argument 1, expecting Buffer"], :result nil}
ERROR [conjure.rpc:?] - Error from thread 'RPC message handler': java.lang.NullPointerException`

**Comment by Olical** [comment]
Not a problem! You're helping me make a better tool by reporting it!

```Received RPC message: {:type :response, :id 1, :error [0 "Wrong type for argument 1, expecting Buffer"], :result nil}```

Hmm, that'll be the one. So I wonder why the buffer is nil, that should be the reference to the log buffer that comes back from the Lua code. A bit convoluted I know, but I have my reasons :sweat_smile:

**Comment by scotts777** [comment]
Yea, it opens a vertical split and I see the name as /tmp/conjure.cljc, but if I do a :ls command the only buffer it lists is my starting buffer with clojure code.

**Comment by Olical** [comment]
This means that one of these is returning nil when it should be returning the buffer ID: https://github.com/Olical/conjure/blob/68c2dac95e2b82db693b623832371b2b2d935b93/lua/conjure.lua#L3-L49

And you won't see it in the buffer list, it's a special hidden thing that can't be accidentally written to a file or clutter your buffer list etc. As long as you can see the window with the buffer name set to `/tmp/conjure.cljc` that's enough proof for me.

So why the nil... I do wonder if it could be some sort of race condition that isn't present on my machine.

**Comment by Olical** [comment]
Is there anything else interesting / scaring in `:messages`? Like possibly related to these commands? https://github.com/Olical/conjure/blob/68c2dac95e2b82db693b623832371b2b2d935b93/lua/conjure.lua#L34-L41

I wonder if one of those could be failing and causing the Lua function to return nil after mostly creating the buffer.

**Comment by scotts777** [comment]
No.  I don’t see anything more than the stack trace that I pasted in my first message.  If I run those commands manually in that buffer they seem to work.  Of course that may  not be apples to apples.

**Comment by Olical** [comment]
Just out of interest, swapping your vim-plug call to `'commit': 'ecfb1c09e5e8258036dfb30f3927e33488533e98'` doesn't help, right? I just fixed the requiring of Compliment if you don't have it in your project.

**Comment by scotts777** [comment]
Changed to that commit and ran PlugUpdate and it looked like it pulled that commit version ok, but same  error with same :message and same log output.

**Comment by Olical** [comment]
Okay, I'm out of lunch time now but will have a look ASAP. Just need to try and repo which seems hard :grimacing: I'd be surprised if it was OSX specific but maybe! Do you have other plugins / settings or is it a blank neovim? I might try to repro it in a bare bones neovim environment.

Latest commit is better too, prints out the full stack trace when something goes wrong `063c29b54459a326b5ff244685dd2765bcd19adf`.

**Comment by scotts777** [comment]
Ok no problem and no rush for this, so take your time.  Yes I am pretty new to the vim world so it is a totally bare bones setup of Neovim that I am running in the built in Mac Terminal.app.  Thanks again.

**Comment by Olical** [comment]
I'll try a stripped down neovim soon and see if I can reproduce it there. I would put money on this being some weird setting that most people have set that might not be set by default. It's so odd how the Lua, Clojure and VimL is all up and talking to each other but still manages to get a nil where it shouldn't.

That nil means it couldn't find the Conjure buffer/window. This could be a race condition (_ahhhhh_) or it could just be a setting on the buffer / neovim instance. I'll work it out :smile:

**Comment by scotts777** [comment]
Great!  Yes, I really like the look of your plugin and where it is heading with prepl!

**Comment by Olical** [comment]
Ah! OSX's `/tmp` is a symlink if I'm not mistaken to `/private/tmp` or something of the sort. Could you confirm that the Conjure buffer isn't in the place I expect by running `:echo expand("%:p")`? I bet it's not `/tmp/conjure.cljc`. I'll start looking for a better solution that should work for you now, if that is indeed the problem.

**Comment by Olical** [comment]
If my hunch is correct, this commit should fix it! If you get a chance to give it a go let me know how it goes :smile: https://github.com/Olical/conjure/commit/3918cbc58113f7475c4679efa818df7d0513c8a5

**Comment by scotts777** [comment]
You’ve done it.   It works!  Interestingly when I ran the echo expand command it did print out /tmp/conjure.cljc.  However, I still tried your last commit and it worked!  Thanks again for your time and all your effort on Conjure

**Comment by Olical** [comment]
Well that's weird... definitely some strange path things going on here but glad the hunch was essentially correct. I think different functions in nvim are reporting different paths depending on your dir being in a symlink or not :grimacing:

But yay! It's fixed! Thank you for your thanks, there's a lot more to do before I'm relatively happy, I hope you get a lot of value out of my work :smile:

![Success!](https://media.giphy.com/media/4xpB3eE00FfBm/giphy.gif)
