### ISSUE TITLE
Conjure displays Hy "err" on startup

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#230]
I've installed neovim with conjure, :hylang/vim-hy, and hy from AUR on arch linux. 

when I open an empty hy file, here's the message in HUD:
```
hy --repl-output-fn=hy.contrib.hy-repr.hy-repr" (started)
; (err) hy 0.20.0 using CPython(default) 3.9.6 on Linux  
```

However, the code buffer I send to it can still be evaluated, this seems to be a display problem. 

Here's the minimal init.fnl to reproduce the problem: 
```clj
(module magic.init {autoload {u magic.utils}})

;; Packer configuration format: https://github.com/wbthomason/packer.nvim
(u.use
  ;; Config for packer startup function
  {:git
   {:default_url_format "https://hub.fastgit.org/%s"}}

  :wbthomason/packer.nvim {}
  :Olical/aniseed {}
  :Olical/conjure {}
  :hylang/vim-hy {})
```
The use function is modified from MagicKit, which adds support for config in packer startup time:
```clj
(defn use [config ...]
  "Iterates through the arguments as pairs and calls packer's use function for
  each of them. Works around Fennel not liking mixed associative and sequential
  tables as well.

  This is just a helper / syntax sugar function to make interacting with packer
  a little more concise."
  (let [pkgs [...]]
    (packer.startup
      {1 (fn [use]
          (for [i 1 (a.count pkgs) 2]
            (let [name (. pkgs i)
                  opts (. pkgs (+ i 1))]
              (-?> (. opts :mod) (safe-require-plugin-config))
              (use (a.assoc opts 1 name)))))
       :config config})))
```

**Comment by glyh** [comment]
BTW, there's actually an nREPL for Hy (https://github.com/allison-casey/HyREPL)

**Comment by Olical** [comment]
Do you mean everything works fine but you see that err output on startup? Because there's nothing I can really do about that I'm afraid, this just means Hy is logging that line to stderr on startup and I display that as `err` since it came from stderr.

**Comment by glyh** [comment]
It sounds reasonable, so I'll close this, since it might be problems from upperstream.

**Comment by Olical** [comment]
I don't think it's really an error or a problem, just a style choice of Hy. They don't want to put that in stdout for some reason, I guess because it's not technically related to the evaluation of your code? So you could redir stderr elsewhere and ignore it?
