### ISSUE TITLE
Having Trouble Connecting to Clojure REPL and ClojureScript REPL simultaneously

### ISSUE THREAD

**Issue by stelcodes** [Olical/conjure#234]
Hi Ollie!

I've been trying to get two sessions running, one connected to a typical Clojure nREPL and the other connected to a shadow-cljs nREPL. The only workflow that I have success with is to run `:ConjureConnect <port>` to switch from Clojure to ClojureScript.

## What I'm Trying, Step by Step
I start a Clojure nREPL on the shell. In Neovim I open a `.clj` file and it automatically connects:
```
; --------------------------------------------------------------------------------
; Assumed session: Pointer (Clojure)
```
I test running my Clojure code and it works. Then in a new shell I start a shadow-cljs nREPL and execute the "watch" and "repl" commands. I can now run `(js/alert "hi")` from that REPL and it opens an alert in my browser.

Back in Neovim I open a `.cljs` file and run `:ConjureShadowSelect app` but it throws an exception:
```
; --------------------------------------------------------------------------------
; shadow-cljs (select): app
; (err) Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:471).
; (err) shadow.cljs.devtools.api
```
Running `<leader>sl` now gives me:
```
; --------------------------------------------------------------------------------
; Sessions (1):
; >1 - Pointer (Clojure)
```
This seems like it sent the command to the Clojure nREPL. Now I make a new session with `<leader>sf`:
```
; --------------------------------------------------------------------------------
; Assumed session: Devon Rex (Clojure)
```
`<leader>sl` shows:
```
; --------------------------------------------------------------------------------
; Sessions (2):
; >1 - Devon Rex (Clojure)
;  2 - Pointer (Clojure)
```
Then I try running `:ConjureShadowSelect app` again and get the same exception:
```
; --------------------------------------------------------------------------------
; shadow-cljs (select): app
; (err) Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:471).
; (err) shadow.cljs.devtools.api
```
Then I try running `:ConjureConnect <shadow-nrepl-port>` and it successfully connects:
```
; --------------------------------------------------------------------------------
; localhost:<clojure-repl-port> (disconnected)
; --------------------------------------------------------------------------------
; localhost:<shadow-repl-port> (connected)
; --------------------------------------------------------------------------------
; Assumed session: Lakeland Terrier (ClojureScript)
```
But when I run `<leader>sl` it tells that my Clojure nREPL connection is gone:
```
; --------------------------------------------------------------------------------
; Sessions (1):
; >1 - Lakeland Terrier (ClojureScript)
```
I can sucessfully eval `(js/alert "hi")` now from Conjure but I can no longer eval my Clojure files. So I try creating a new session again:
```
; --------------------------------------------------------------------------------
; Assumed session: Miniature Poodle (ClojureScript)
```
And then I run `:ConjureConnect <clojure-nrepl-port>` and it prints:
```
; --------------------------------------------------------------------------------
; localhost:<shadow-repl-port> (disconnected)
; --------------------------------------------------------------------------------
; localhost:<clojure-repl-port> (connected)
; --------------------------------------------------------------------------------
; Assumed session: Devon Rex (Clojure)
```
Now `<leader>sl` gives me:
```
; --------------------------------------------------------------------------------
; Sessions (2):
; >1 - Devon Rex (Clojure)
;  2 - Pointer (Clojure)
```
And trying to eval my cljs code gives me:
```
; --------------------------------------------------------------------------------
; eval (current-form): (js/alert "Does this work?")
; (err) Syntax error compiling at (src/codes/stel/functional_news/frontend.cljs:6:10).
; (err) No such namespace: js
```

So at this point I can run `:ConjureConnect <shadow-repl-port>` and `:ConjureConnect <clojure-repl-port>` to switch between my Clojure and ClojureScript but is there an easier way? Maybe I just have to configure a single REPL to run both my Clojure and ClojureScript code? I saw in another issue that you said using multiple sessions was possible. It seems like session collections are coupled to the nREPL instance? Is there a way to switch between two nREPL's using sessions? Thanks!

```
NVIM v0.5.0
Conjure 2021-07-23
```

**Comment by Olical** [comment]
So, I mayyy be misreading but I'll try my best to grok / repeat and answer!

 * You have a Clojure nREPL server for backend code etc
 * And a shadow-cljs nREPL server for frontend things
 * The codebases overlap (this is pretty common in my experience)
 * You want to be able to hop between Clojure and ClojureScript but you need to hop into different nREPLs to do so

So there's two approaches here, and I think really only one of them is viable:

 1. You connect to shadow-cljs, start a new session and `ConjureShadowSelect` in one of those sessions
 2. You use the `ConjureClientState` feature to connect to multiple nREPLs at once and use mappings or autocmds to swap between them.

I've written up my thoughts on the feature here https://github.com/Olical/conjure/wiki/Multiple-connections-with-ConjureClientState

Hopefully that helps! If so, I can make some edits (or you're more than welcome to!) with some clarifications and extra examples.

**Comment by Olical** [comment]
I'm going to close this in the hope that the wiki page is good enough, but please feel free to reopen if you have further questions or issues! We can also use the discussion feature https://github.com/Olical/conjure/discussions
