### ISSUE TITLE
Conjure fails to evaluate in latest Neovim nightly version

### ISSUE THREAD

**Issue by datwaft** [Olical/conjure#245]
**Note:** there is no problem with Neovim v0.5, this only happens on nightly.

I ran into this issue after updating Neovim nighly to the latest version yesterday using Homebrew.

Could be related to [this breaking change](https://github.com/neovim/neovim/issues/14090#issuecomment-922327377).

## Environment Information

**OS:** Ubuntu 20.04.3 LTS inside WSL2 in Windows 10 Pro 21H1
**Neovim version:** NVIM v0.6.0-dev+304-g924e8e4f2

## How to reproduce the issue

I created this Github repository which uses Docker to reproduce the issue: [datwaft/conjure-issue_neovim_nightly](https://github.com/datwaft/conjure-issue_neovim_nightly).

## Evidence

![image](https://user-images.githubusercontent.com/37723586/133939095-fbcbc39b-8d9c-4370-920d-ea31453c7bc0.png)

**Comment by Olical** [comment]
I've added some changes to use the new API instead of the older runtimepath string in Aniseed / Conjure. Let me know if that helps at all! No more time to test tonight, but seems okay on the stable version 🤔

**Comment by datwaft** [comment]
I tried with the develop branch, now it fails with another error:

```log
E5108: Error executing lua ...nvim/site/pack/packer/start/conjure/lua/conjure/eval.lua:
147: ...k/packer/start/conjure/lua/conjure/aniseed/nvim/util.lua:53: ...cker/start/conj
ure/lua/conjure/client/fennel/aniseed.lua:152: attempt to concatenate field 'context' (
a nil value)
```

![image](https://user-images.githubusercontent.com/37723586/134254040-04c48e59-84a8-4de0-ab30-3e44a2ff63b1.png)

**Comment by Olical** [comment]
Huh, well, that doesn't really make any sense from what I understand right now but thank you for trying it. I'll dig in soon with your container.

Horrible timing on this bug while I'm lacking any free time and was 80% through a huge refactor 😞 hopefully I can sort it soon.

**Comment by datwaft** [comment]
😞

**Comment by Olical** [comment]
I think I spotted it and fixed it on develop!

**Comment by datwaft** [comment]
Seems to work properly now! 😄

**Comment by Olical** [comment]
Should be fixed! Released!
