### ISSUE TITLE
Tree-sitter "execute current form" / `get-form` not always working correctly

### ISSUE THREAD

**Issue by sevanteri** [Olical/conjure#250]
For example in Fennel with `(foo.bar :baz)` and cursor over `bar`, `-ee` returns `#<function: 0xdeadbeef>` because it only evaluates the `foo.bar`.

tree-sitter-fennel got an upgrade recently and `foo.bar` is parsed as `multi_symbol` which does have child elements, so `conjure.tree-sitter.get-form` stops its walk up the tree there.

For Fennel, the `"("` and `")"` anonymous nodes are also parsed so the node can be queried with `(_ . "(" ")" .) @foo`, but I have no idea if the same goes for the other supported languages.
Instead of a query, maybe the tree could be walked up and check that the first and last children are the parenthesis. But yet again the language's treesitter has to support those anonymous nodes...

Here's something I came up with when fooling around with Treesitter and Fennel:

```clojure
(module treesitter-foo
 {require {a aniseed.core
           tsu nvim-treesitter.ts_utils
           tsq vim.treesitter.query
           queries nvim-treesitter.query}})

(tsq.set_query "fennel" "foo" "(_ . \"(\" \")\" .) @foo"))

(defn get-form-node [node]
  (let [matches (queries.get_capture_matches bufnr "@foo" "foo" node)]
    (if (a.empty? matches)
      (get-form-node (node:parent))
      node)))
``````

**Comment by Olical** [comment]
Generally I've been treating tree-sitter as something I walk up until I find the appropriate level so far. There may be better ways using queries like you've shown though, I just haven't looked into them yet. Thanks for the detailed report, I'll try to have a look very soon unless someone beats me to it 😄 I need to get the `develop` changes released ASAP, so many unreleased commits and improvements.

**Comment by sevanteri** [comment]
Well, it seems that at the moment Clojure is the only other supported language that has tree-sitter available. And it also has the parenthesis as first and last anonymous nodes! \o/

**Comment by sevanteri** [comment]
```clojure
(defn- get-form-node [node]
  (when node
    (let [first-child (node:child 0)]
      (if (and
            first-child
            (= (first-child:type) "("))
        node
        (get-form-node (node:parent))))))
```

**Comment by Olical** [comment]
Fixed in the latest release!
