### ISSUE TITLE
Error printing return value

### ISSUE THREAD

**Issue by kesk** [Olical/conjure#258]
I have noticed a problem when using [weavejester/euclidean](https://github.com/weavejester/euclidean) and Conjure. I get errors when evaluating things that return lists of vectors from the euclidean library:

```
; (err) Error printing return value (UnsupportedOperationException) at clojure.lang.RT/countFrom (RT.java:671).
; (err) count not supported on this type: Symbol
```

Example code:
```clojure
(require '[euclidean.math.vector :as v])

(v/vector 1 1) ;; <= works
(vector (v/vector 1 1)) ;; <= works
(list (v/vector 1 1)) ;; <= fails when evaluating with conjure
```

I'm using Conjure `v4.25.0`.

**Comment by Olical** [comment]
Finally investigated this! I don't think it's Conjure, I think it's the formatting of the output before it reaches Conjure in the nREPL that causes this. Conjure sets `:nrepl.middleware.print/print` to true (you can turn this off with `:h g:conjure#client#clojure#nrepl#eval#pretty_print`) which causes the output to flow through `clojure.pprint/pprint` I think, maybe that depends on what pretty printing libraries you have to hand.

I can reproduce the error with this in a normal Clojure REPL.

```clojure
$ clj
Clojure 1.10.1
user=> (require '[euclidean.math.vector :as v])
nil
user=> (clojure.pprint/pprint (list (v/vector 1 1)))
Execution error (UnsupportedOperationException) at euclidean.math.vector.Vector2D/equals (vector.clj:45).
count not supported on this type: Symbol
```

So this is either a bug in Clojure or something to do with that library not supporting some methods required for pretty printing. I don't think this is something I can work around I'm afraid, it's the language or the library, so I'm going to close this for now. I hope this points future people in the right direction!
