### ISSUE TITLE
How to disable completion only?

### ISSUE THREAD

**Issue by dkvasnicka** [Olical/conjure#266]
The docs on `g:conjure#completion#omnifunc` say

> No omnicompletion will be provided if you set this to `nil`

but when I do this in my `.vimrc` I get error saying NVim cannot understand `nil` (I guess it's a Lua-ism?). What exactly should I set this to in vimscript to disable completion _only_? When I disabled `conjure` as a source in CoC it silenced it completely, including diagnostics.

**Comment by Olical** [comment]
I think that's v:null in VimL? Or possibly v:false in this case, I'm sorry
I can't quite remember off the top of my head but one of those.

**Comment by dkvasnicka** [comment]
Looks like `v:false` did the thick, thanks!
