### ISSUE TITLE
Automatic REPL connection broken

### ISSUE THREAD

**Issue by zbouslikhin** [Olical/conjure#268]
Hi, 

I've used conjure for quite some time now and everything was working flawlessly. 
However, when trying to set up [coc.nvim](https://github.com/neoclide/coc.nvim) plugin, it broke conjure automatic connection.
In the buffer, it says "no nREPL port file found". 

Any help would be appreciated!

**Comment by Olical** [comment]
Hm this is working fine for me and hasn't been changed at all recently 🤔

Do you mean the automatic babashka REPL or the automatic connection to a running nREPL using the `.nrepl-port` file?

**Comment by zbouslikhin** [comment]
I honestly wouldn't be able to tell if babushka REPL or the automatic connection, but basically, I used to open a .clj and automatically conjure would start an REPL connection to start evaluating right away. 
Here is a screenshot if it can be any helpful
![image](https://user-images.githubusercontent.com/47977073/142242099-f7e0f2ae-3b95-4bf6-8416-564b6ff83057.png)

**Comment by Olical** [comment]
So that thing where you open Neovim and you instantly can evaluate things is powered by https://babashka.org/

Can you run `bb --version` in your terminal? If not I think bb has been uninstalled somehow which would break that feature, Conjure only tries to start a REPL and connect to it if babashka can be found.

**Comment by Olical** [comment]
Closing since I think this is due to not having babashka installed and accessible by Conjure / Neovim. Please reopen if you have it installed and it's still not working!
