### ISSUE TITLE
Auto scroll log buffer

### ISSUE THREAD

**Issue by tami5** [Olical/conjure#270]
Hello there

I'd like to have log buffer auto scroll last evaluate expression to the top.

When evaluating an expression + log buffer is open, I like to have this:
![Screen Shot 2021-11-20 at 1 13 52 AM](https://user-images.githubusercontent.com/65782666/142698202-db2ad361-babf-4a7c-8a9a-49aa8b7062f3.png)

instead of
![Screen Shot 2021-11-20 at 1 14 12 AM](https://user-images.githubusercontent.com/65782666/142698232-4cf90ffc-4954-4989-af31-e238c7161494.png)

This is something I first experienced within emacs and I kind find useful.

I believe in each evaluation somehow, the buffer should run `zt` and with scrolloff set to 2.

**Comment by Olical** [comment]
This is something I think is done in the latest release 😄 see `:h conjure` and `/jump`, you can use a mapping or have it do it automatically.

**Comment by Olical** [comment]
Closing for now but maybe it'll be worth opening another one with improvements if the current implementation isn't what you need exactly.
