### ISSUE TITLE
Issues with testing (tests pass when they shouldn't)

### ISSUE THREAD

**Issue by harrisoncramer** [Olical/conjure#275]
Hello! Thank you for the great tool.

I'm currently unable to get an individual test to fail with the `ConjureCljRunCurrentTest` command.

If I've created a new project with Leiningen, I'm able to switch into the testing file and evaluate the file with `<localleader>eb` and then run all tests with `<localleader>ta` which works fine (perhaps I'm doing this wrong, if so please let me know).

However, if I attempt to run any of the specific tests, by hovering inside of them and then pressing `<localleader>tc` then they always pass. This even occurs with the default test that is supplied by Leiningen, which should fail. The tests do fail if just run via the command line with `lein test`.
![Screenshot from 2021-12-02 18-23-26](https://user-images.githubusercontent.com/32515581/144518819-07588b98-103e-4e85-ab5c-a4dc23325270.png)

Furthermore, I'm unable to see the error output from any failing tests.

I'm on Neovim 0.6.0--I'm relatively new to Clojure, any help would be appreciated. Thank you!

**Comment by harrisoncramer** [comment]
Apologies--did not realize you needed to start the nRepl manually in another terminal in order to get this to work. Closing!

**Comment by Olical** [comment]
Hmm you shouldn't really need to, that _should_ fail, you're right. I'm going to reopen and investigate a little.

Do you know if you were using the "autorepl", the babashka thing that connects for you on startup? If so that narrows it down pretty quickly.

**Comment by harrisoncramer** [comment]
I'm pretty sure it's a misconfiguration on my part of some sort—if I'm doing nothing else other than `lein new test-repo && cd test-repo`, I'll see "No nREPL port file found" inside the Conjure buffer, after opening up a test file and trying to run a test inside Neovim. But if I'm connecting manually (running `lein repl` in a terminal) and then opening up the buffer, it actually  connects fine and the test fails, as expected.
<img width="757" alt="Screen Shot 2021-12-03 at 9 10 42 AM" src="https://user-images.githubusercontent.com/32515581/144616274-439ccfb3-1ff7-406d-83ce-482d15394697.png">

Above are the logs. This really works fine, and is a great workflow, and could only be improved if there's a way to automatically startup the Repl when opening up Neovim.
