### ISSUE TITLE
Interrupt an evaluation

### ISSUE THREAD

**Issue by Kineolyan** [Olical/conjure#276]
So far, it seems there is no way to interrupt the current evaluation. This is often an issue when working on a loop with a wrong stop condition.

Such a feature is present in [the extension Calva for vscode](https://calva.io) as well as in [cider for emacs](https://docs.cider.mx/cider/1.1/repl/basic_usage.html#interrupting-evaluations).
Is there something preventing such a feature being implemented in Conjure? - because if not, I can give it a try, with some initial guidance.

Sorry if I missed the function or an issue already asking this.

**Comment by Olical** [comment]
This is bound to `<prefix>ei`, should do the trick!

**Comment by Kineolyan** [comment]
Ah, many thanks for the very quick answer. I'll try as soon as possible.
Checking again the vim manual about conjure-mappings, I don't see any trace of it.
Would you like me to add it to the doc, as a thank you for this?

**Comment by Kineolyan** [comment]
Well, this is documented [here](https://github.com/Olical/conjure/blob/31820e386ce7a32488ad6b19033c17a8f05c36bf/doc/conjure-client-clojure-nrepl.txt#L82), my bad.
But it does not seem to work - on my very quick test with Babashka nrepl.
```clojure
(dotimes [_ 60]
    (print "Waiting ...")
    (Thread/sleep 1000)
    (println " done"))
```
It kept printing during 60 sec, though I saw the output "Interrupted: session: .... (Clojure)" - with the correct session name.
I will browse the documentation more in depth to see if there is something more to configure.

**Comment by Olical** [comment]
I'm afraid it doesn't work with babashka as far as I'm aware, I think the nREPL operation just does nothing for babashka in general. It will work in JVM Clojure but that's probably the only place it's properly implemented on the nREPL server side. If you _know_ babashka should support this operation and it's not working properly from Conjure specifically then I can look into what's going on.
