### ISSUE TITLE
Conjure's format is messed up with big output from Janet

### ISSUE THREAD

**Issue by thanhnguyen2187** [Olical/conjure#277]
Hi!

I am working on a personal project using Janet, which involves raw data reading. The REPL driven flow means a lot of big dictionary/table printing from, and the output seems messed up after a big (2000-line-ish or greater) output.

A minimal reproduction can be seen after evaluating this:

```clojure
(zipcoll
  (range 2000)
  (map inc (range 2000)))
```

![image](https://user-images.githubusercontent.com/27758849/144868240-c40c979f-7ec1-490f-aa91-fac7e5eaed13.png)

Thanks for the awesome plugin!

**Comment by Olical** [comment]
I _think_ you just need to raise this limit: https://github.com/Olical/conjure/blob/9ed390497a5013aa533a15f5d96f3fb6319b4eb9/doc/conjure.txt#L573

There's a limit on it because if you print a 300k line value I try to restrict the amount of large string processing that Conjure performs to keep the output displaying quickly. You're more than welcome to raise it as high as you want though!

**Comment by thanhnguyen2187** [comment]
Thanks for the quick reply! It is a shame I did not look at the options careful enough

**Comment by pyrmont** [comment]
@Olical It's possible with Janet's netrepl server to output without ANSI escape sequences. If you do that, does it effect the speed of processing?

**Comment by Olical** [comment]
I don't think it impacts perf either way, I only have this restriction as a precaution for people running Conjure on older machines that can't cope with modifying hundreds of MB of strings with Lua patterns 😬 I've never tested this, it's just a precaution, I could remove it tbh

**Comment by pyrmont** [comment]
@Olical What if stripping the ANSI codes was an option a user could toggle? Then if you were worried about the impact on performance, you could disable it and change it so that the sever doesn't output the codes.

**Comment by Olical** [comment]
Set it to 0 to never strip, then turn off ansi sequences in the server. Or set it to like 10000 and you should never need to worry but if you accidentally print 100k lines you'll probably be thankful that it's not splitting 100k lines into strings and running subs on each one (although even then it probably only takes a second or two on a decent CPU)

**Comment by pyrmont** [comment]
@Olical Of course I should have more closely read the documentation :P Thanks for the explanation!

@thanhnguyen2187 Sorry to have hijacked your issue! In case it's of interest. I have a new build-tool for Janet that I'm testing out called [Jeep](https://github.com/pyrmont/jeep) that can make it easy to run a netrepl server. Just `jeep netrepl` in your project directory and you're away :) By default it disables ANSI output (although you can specify a different supported format if you prefer).
