### ISSUE TITLE
Go to definition on jar files is not working on nvim 0.6

### ISSUE THREAD

**Issue by rafaeldelboni** [Olical/conjure#279]
Looks like some change in the new version on `pi_zip v32` on Oct 22, 2021 changed the path for zipfiles and when I try to do a go to definition it opens a blank buffer

- https://neovim.io/doc/user/pi_zip.html
- https://github.com/tpope/vim-fireplace/pull/398

**Comment by Olical** [comment]
More breaking changes!? 😭 but thank you so much for keeping an eye on this and fixing it. I'll merge now and try out the changes today then deploy ASAP, I've got a super busy weekend ahead but at least it'll be on the develop branch.

Thank you! ❤️

**Comment by Olical** [comment]
Oh no, it was targeting master, I need to fiddle a bit

**Comment by rafaeldelboni** [comment]
Oh I'm sorry I forgot about the develop branch :(

As I suggestion, if you add a note about the branch on CONTRIBUTING.adoc, which btw helped me a lot :)

**Comment by Olical** [comment]
Not a problem! I'll do that, for now I've just merged it into develop, will leave it on both so it's technically stealth release at the moment but I've got a lot of work to do so that'll be fine for now.
