### ISSUE TITLE
Issue when trying to use conjure with `:set throw=debug`

### ISSUE THREAD

**Issue by kyazdani42** [Olical/conjure#283]
Hi ! First of all, thanks for all those things you do for the lisp neovim community, there are quite nice :) (and actually helped me start to learn lisp like languages !)

I'm using the latest version of neovim (nightly), with packer, and upon setting `:set throw=debug`, conjure throws the following error and fails to open the buffer:
```
E5108: Error executing lua Vim:E94: No matching buffer for conjure-log-164415.fnl
stack traceback:
        [C]: in function 'bufnr'
        ...im/site/pack/packer/start/conjure/lua/conjure/buffer.lua:28: in function 'upsert_buf'
        .../nvim/site/pack/packer/start/conjure/lua/conjure/log.lua:272: in function 'display_request'
        ...nvim/site/pack/packer/start/conjure/lua/conjure/eval.lua:106: in function <...nvim/site/pack/packer/start/conjure/lua/conjure/eval.lua:101>
        ...nvim/site/pack/packer/start/conjure/lua/conjure/eval.lua:147: in function 'eval_str'
        ...nvim/site/pack/packer/start/conjure/lua/conjure/eval.lua:169: in function 'current-form'
        [string ":lua"]:1: in main chunk
```

It does not error out without the option though, but i'm enabling it to make sure my own plugins do not have any hidden issues :)
I'm not yet experimented enough with fennel/aniseed to debug this by myself yet, so i'll leave it to someone else !

**Comment by Olical** [comment]
Fixed thanks to your PR! ❤️
