### ISSUE TITLE
Crash on startup with latest nvim from Git

### ISSUE THREAD

**Issue by raymond-w-ko** [Olical/conjure#293]
```
Error executing vim.schedule lua callback: .../nvim/site/pack/packer/start/conjure/lua/conjure/log.lua:192: Expected Lua number
stack traceback:
        [C]: in function 'win_is_valid'
        .../nvim/site/pack/packer/start/conjure/lua/conjure/log.lua:192: in function 'display_hud'
        .../nvim/site/pack/packer/start/conjure/lua/conjure/log.lua:357: in function 'append'
        ...tart/conjure/lua/conjure/client/clojure/nrepl/action.lua:139: in function <...tart/conjure/lua/conjure/client/clojure/nrepl/action.lua:84>
```

**Comment by raymond-w-ko** [comment]
Probably related to https://github.com/neovim/neovim/pull/16745/files

Nvim's own code base not immune to this change, they had to fix some of their own stuff: https://github.com/neovim/neovim/commit/36662c961244f41996720a0eec8eac67a18f2ec0

`fnl/conjure/log.fnl` line 165 needs to be changed to something like `(when (and state.hud.id (not (nvim.win_is_valid state.hud.id))) ... )` ??

**Comment by daveyarwood** [comment]
I'm seeing this too, after upgrading to the latest unstable version of Neovim.

**Comment by Olical** [comment]
Agreed that it's related and that'll also be the fix 😄 can't do it right now though I'm afraid, if you open a PR to develop I'll get it merged ASAP then release soon.

**Comment by spartakos87** [comment]
Hello, I have the same problem, there is any, at least, temporary solution?

**Comment by daveyarwood** [comment]
@spartakos87 Until the next release of Conjure (which I think will include this fix), we can run the development branch, which I can confirm is stable at the moment.

On my system, `~/.vim/bundle` is the directory where vim-plug clones plugin repos. It might be different on your system, but assuming that it's the same, you can run:

```
cd ~/.vim/bundle/conjure
git checkout develop --
git pull
```

**Comment by Olical** [comment]
Should be all good now! Sorry for the delay!

**Comment by daveyarwood** [comment]
Thanks Ollie!
