### ISSUE TITLE
Broken Ansi color code in Clojure documentation 

### ISSUE THREAD

**Issue by Sangdol** [Olical/conjure#295]
Hello,

First of all, thanks a lot for the plugin. I've just finished `:ConjureSchool` and it was awesome.

While trying out Conjure I've noticed a problem with the `Look up documentation` feature. When I tried looking up a document for Clojure with `K`, it showed broken Ansi color code in the document as below (it looks more broken in Github than in vim):

```
; --------------------------------------------------------------------------------
; doc (word): is
; -------------------------
; clojure.test/is
; ([m[[mform][m [[mform msg][m)[m
; Macro
;   Generic assertion macro.  'form' is any predicate test.
;   'msg' is an optional message to attach to the assertion.
;
;   Example: (is (= 4 (+ 2 2)) "Two plus two should be 4")
;
;   Special forms:
;
;   (is (thrown? c body)) checks that an instance of c is thrown from
;   body, fails if not; then returns the thing thrown.
;
;   (is (thrown-with-msg? c re body)) checks that an instance of c is
;   thrown AND that the message on the exception matches (with
;   re-find) the regular expression re.
; --------------------------------------------------------------------------------
; doc (word): vector
; -------------------------
; clojure.core/vector
; ([m[[m][m [[ma][m [[ma b][m [[ma b c][m [[ma b c d][m [[ma b c d e][m [[ma b c d e f][m [[ma b c d e f &[m args][m)[m
;   Creates a new vector containing the args.
```
![Screen Shot 2022-01-04 at 20 42 51](https://user-images.githubusercontent.com/803223/148122944-f02e1ef9-2456-418a-bbf7-c8e766d22cca.png)

I've tried AnsiEsc as described in [the wiki page](https://github.com/Olical/conjure/wiki/Displaying-ANSI-escape-code-colours-in-the-log-buffer) but it didn't work for me due to a few reasons
1. `Autocmd BufEnter conjure-log-* AnsiEsc` this toggles `AnsiEsc` which means AnsiColor toggles whenever I enter a log buffer (I think we need to write this in the wiki). I was able to fix this with a custom function but,
1. `AnsiEsc` disables syntax highlight.

I tried using [Colorizer](https://github.com/chrisbra/Colorizer) but it didn't work and I realized that it's because the escape code is not valid Ansi codes.

I thought it could be due to the `g:conjure#log#strip_ansi_escape_sequences_line_limit` variable but the behavior didn't change when I changed the value.
```
  g:conjure#log#strip_ansi_escape_sequences_line_limit = 0
```

How could I remove the escape code? Or how could I get valid Ansi codes?

Thanks.

**Comment by daveyarwood** [comment]
I've had a good experience with [Baleia](https://github.com/m00qek/baleia.nvim#with-conjure).

See my comments at the bottom of https://github.com/Olical/conjure/issues/53

**Comment by daveyarwood** [comment]
I'm about to make an edit to that wiki page to recommend Baleia, at least as an alternative to AnsiEsc.

**Comment by Sangdol** [comment]
Thanks for the quick answer. I've actually tried Baleia but faced an error. I just created a ticket: https://github.com/m00qek/baleia.nvim/issues/4

Btw, do you have any idea why the Ansi codes are added when Conjure loads the document? Does it load the document from the original code in jar?

**Comment by Olical** [comment]
I don't have time to dig into this just yet but wanted to say I've never seen escape codes in help text in Conjure ever and I definitely don't add them. I think that's maybe some REPL middleware you have maybe 🤔 possibly some sort of REPL prettifier system like bhauman's rebel readline (I think that's the name?).

Might be something I need to strip from help text like I do most stdout/err.

**Comment by Sangdol** [comment]
Oh great. I found the reason. It was due to [ultra](https://github.com/venantius/ultra). Thanks, you're awesome.

**Comment by brendonjwong** [comment]
Thanks @Sangdol, I had this same issue and `ultra` was the culprit for me as well. It also caused me issues when trying to run Clojure projects on Java 11 recently 😢
