### ISSUE TITLE
navigating back from definition jump

### ISSUE THREAD

**Issue by shaunlebron** [Olical/conjure#298]
in `vim-fireplace`, each jump to a definition adds a breadcrumb to the tag stack, so `CTRL-T` can navigate back down the stack.

I realized that `CTRL-O` is a good substitute, but it tracks all jumps not just the definition jumps, so I have to mash it a bit more than normal.

Is there a way to do this?  Thanks

**Comment by Olical** [comment]
Oh this is a good idea, I'm not sure how to do this right now but thank you for bringing it to my attention. It may end up being a one line addition in the jump to def code!

**Comment by Olical** [comment]
Apparently this is done by setting the `'` mark! I'll add that after go-to-def calls and see if that does the trick.

**Comment by jsn** [comment]
Oh by the way, fireplace also maps Ctrl-] to what would be <Localleader>gd in conjure, might be a nice additional mapping to have in conjure.

**Comment by Olical** [comment]
Hmm isn't that that "go to tag" mapping? I see tags as a distinct thing to this jumplist+go-to-def code, I don't think I'd be comfortable mapping over that as a default but you're more than welcome to add a custom mapping for it 😄

**Comment by Olical** [comment]
I used to use `gd` without the prefix but changed it to `<prefix>gd` by default so your mappings for things like LSP clients etc will all work then you have the _option_ of Conjure's go-to-def under a more specific sequence.

**Comment by dharrigan** [comment]
Echoing what Olical says, in my vim config, I have this:

`nmap <silent> gd                    <Plug>(coc-definition)`

Since I use CoC (which is super nice :-) )

**Comment by jsn** [comment]
Sorry, I think I'm confused about what this enhancement does. I was under impression that now after `,gd` I can jump back to where I was using Ctrl-T, but apparently I can't? So what changed, then?

**Comment by Olical** [comment]
Oh, I've done a whoopsie. All I've done is improve Ctrl-O navigation by explicitly entering into the jumpstack before you go to def which makes it behave more consistently.

You're right that the tag stack is different! Not sure if it's a good thing to do 🤔 like for people that make heavy use of tags I'll be messing with their tag stack... maybe I can make it optional...

Reopening! Requires an additional change! I think the current change is still useful (if subtle) but I need to work out how to push to the tag stack.

**Comment by Olical** [comment]
Tag stack implemented! I think! Let me know how that works for you (on the `develop` branch)

**Comment by dharrigan** [comment]
Hi,

```
:version                                                                                                                                                                                                                                                       
NVIM v0.6.1                                                                                                                                                                                                                                                    
Build type: Release                                                                                                                                                                                                                                            
LuaJIT 2.0.5                                                                                                                                                                                                                                                   
Compiled by builduser
```

```
  ~/.vim/bundle/conjure on   develop                                                                                                                                                                                                                     ▼
❯ git tip  
61bfe61 (HEAD -> develop, origin/develop) Push to the tagstack when jumping to def
```

Doesn't yet seem to work.

If I `gd` a few times, typing `CTRL+T` doesn't do anything, and doing `:tags` shows an empty list.

![image](https://user-images.githubusercontent.com/427150/150645556-e698d27d-f7e8-4bcf-9df9-dbef6a654fcb.png)

**Comment by dharrigan** [comment]
Hi,

Actually, it's all good. 

By using `<prefix>gd` then it uses Conjure and the tag stack works fine.
Using just `gd` which I've mapped to `coc-definition`, then I use `ctrl+o` to jump back (perhaps coc-definition can be taught about using tag stacks, but that's for the Coc project).

So, in-so-far, as the `<prefix>gd`, and `ctrl+t`, all is good!. Thanks @Olical!

**Comment by jsn** [comment]
Thanks, seems to work as advertised!

**Comment by shaunlebron** [comment]
Great work! And thank you!

(I'm so glad how well Conjure works btw.)

Since Conjure integrates with the tag stack now, I would make sure to cover
both ops: Ctrl+T pop, Ctrl+] push.  Fireplace does this, as Dimitry said.
I sympathize with being conservative about remapping default bindings, but
it's neither popular nor useful to generate static tag files for clojure,
right?
