### ISSUE TITLE
Evaluate in Conjure's JVM by default

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#31]
So if no prepl connections match the current file or you don't have any connections at all it'll eval within Conjure's own JVM.

This means you can just open any random Clojure file and just evaluate it within a couple of seconds. Perfect for quickly trying something or scripting!

The only danger is that someone forgets to connect to their prepl and then sits there wondering "why aren't my dependencies here!?" but that could be mitigated with a warning. So on eval, if you have no connections it will warn _once_ that it's falling back to Conjure's JVM.

**Comment by daveyarwood** [comment]
I would love this feature. Especially if there were a warning when no existing connection is found, for the reason you mentioned.

**Comment by Olical** [comment]
:tada: easier than expected! Won't release just yet since I just released `v0.12.0` but you can just depend on this exact commit (https://github.com/Olical/conjure/commit/cc3bfa5777c2650d58100fefca82457c287b43d0) to try it out :smile: feedback is appreciated!
