### ISSUE TITLE
Wrong type for argument 2 when calling nvim_exec_lua, expecting Array

### ISSUE THREAD

**Issue by daveyarwood** [Olical/conjure#316]
After updating Conjure and/or Neovim recently, I've started seeing this error message pop up repeatedly as I type into any Clojure buffer:

```
Complete conjure error: request error nvim_exec_lua - Wrong type for argument 2 when calling nvim_exec_lua, expecting Array
```

I'm guessing this is some breaking change in the Neovim API?

I am using the unstable branch of Neovim, version `0.7.0~ubuntu1+git202202120047-e3c09cb9e-dd05b3569-7e71277fb~ubuntu20.04.1`

**Comment by daveyarwood** [comment]
Interestingly, if I comment out `Plug 'Olical/conjure'` in my vimrc, the problem persists! So maybe this is actually related to another plugin, probably one related to completion.

**Comment by daveyarwood** [comment]
Yeah, if I disable coc, the problem goes away. I'll file an issue with coc about this, but @Olical  if you have any suggestions or insight, that would be helpful!

**Comment by Olical** [comment]
Seems like there was probably a time when you could pass a string or something to `nvim_exec_lua` and it'd automatically wrap it in an array but that time has passed. I don't _think_ I ever do that in my code... this is a good place to check for breaking changes. I'm now subscribed to it! https://github.com/neovim/neovim/issues/14090#issuecomment-1024971664

**Comment by daveyarwood** [comment]
Yes, that was totally it! The problem went away after I upgraded coc-conjure :boom:
