### ISSUE TITLE
Check for each nREPL port file at each tree level

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#317]
As Hukka over on Clojurians slack pointed out, Conjure will pick the Clojure `.nrepl-port` file over the shadow-cljs one if a single `.nrepl-port` exists anywhere up your directory tree, so it's hunting for that first _then_ shadow-cljs if it can't find one. It should instead check each directory for each file in priority order.

The priority remains the same (Clojure then ClojureScript) but it should check for each in each directory as it travels, instead of travelling upwards twice.

**Comment by stelcodes** [comment]
Hi there @Olical, I'm not sure if you've already been working on this but I posted a rough draft PR for this issue.
