### ISSUE TITLE
Running `ConjureShadowSelect` automatically

### ISSUE THREAD

**Issue by kovasap** [Olical/conjure#318]
For me, I find setting vim up to run `ConjureShadowSelect` automatically when I open a cljs file is a big quality of life improvement.  I was doing this with:

```
autocmd BufEnter *.cljs :ConjureShadowSelect app
```

But noticed some buggy behavior when executing `:ConjureShadowSelect app` multiple times in a single editing session (whenever I would switch buffers).  I think the best solution would be to have vim only execute this autocmd once, for the first cljs file opened.  Before I try to mess around with that, I'm curious if anyone else has come up with possibly better solutions for this use case.

**Comment by Olical** [comment]
Pushed a change to develop that turns a second shadow select into a noop that still prints a little bit of text but that's all. This at least stops it from breaking things, but I'd recommend setting a flag the first time you run this then avoiding running it again 🤔

**Comment by kovasap** [comment]
Ok thanks!  I'm also curious if anyone has come up with a way to automatically determine the "app" part of the command based on open nREPLs.

**Comment by kovasap** [comment]
I have a hacky way to automate this now:

```
let shadow_build=system("ps aux | grep 'shadow-cljs watch' | head -1 | sed -E 's/.*?shadow-cljs watch //'")
autocmd BufEnter *.cljs :ConjureShadowSelect shadow_build
```

@Olical do you think it would make sense to include this as part of conjure somehow after it's been polished?

**Comment by kovasap** [comment]
A better solution:

```vim
function! AutoConjureSelect()
  let shadow_build=system("ps aux | grep 'shadow-cljs watch' | head -1 | sed -E 's/.*?shadow-cljs watch //' | tr -d '\n'")
  let cmd='ConjureShadowSelect ' . shadow_build
  execute cmd
endfunction
command! AutoConjureSelect call AutoConjureSelect()
autocmd BufEnter *.cljs :AutoConjureSelect
```

**Comment by kovasap** [comment]
@Olical would you accept a documentation pull request that adds this tip?

**Comment by Olical** [comment]
Hmm, could be good although I feel like this sort of recipes style docs would work well in the wiki since it's something we can link to easily. What do you think about creating a wiki page like the one on [ConjureClientState](https://github.com/Olical/conjure/wiki/Multiple-connections-with-ConjureClientState), either about this specific idea or maybe one to do with Clojure tips and tricks specifically.

**Comment by kovasap** [comment]
What if I add a small section to this: https://github.com/Olical/conjure/wiki/Quick-start:-ClojureScript-(shadow-cljs)#connect-and-select?

**Comment by Olical** [comment]
Yep, that's a good spot!

**Comment by kovasap** [comment]
Done!

**Comment by Olical** [comment]
Nice! That looks good to me, I think it's good to include things like this that are optional and maybe only work on some operating systems etc in wiki pages. As opposed to inside the codebase itself where complexity and effort spirals while trying to support all users and use cases. Community collections of things with caveats are great.

**Comment by kovasap** [comment]
Sounds good and makes sense!

**Comment by humorless** [comment]
Hi @kovasap 

Below is my work around version:
In `.config/nvim/lua` put this file:  https://github.com/raystubbs/edn.lua/blob/main/edn.lua


in `.config/nvim/fnl/auto-conjure.fnl`

```
(module auto-conjure {require {{:decode decode} edn} autoload {a aniseed.core}})

(local nvim vim.api)

(fn get-project-root []
  (vim.fn.getcwd))

(fn shadow-cljs []
  (let [project-root (get-project-root)
        shadow-path (.. project-root :/shadow-cljs.edn)
        file (io.open shadow-path :r)]
    (if file
        (let [content (file:read :*a)]
          (file:close)
          content)
        (do
          (nvim.nvim_err_writeln (.. "File not found: " shadow-path))
          nil))))

(fn build-key [tbl]
  (let [lseq []]
    (each [k v (pairs tbl.builds)]
      (table.insert lseq k))
    (a.first lseq)))

(fn shadow-build-id []
  (build-key (decode (shadow-cljs))))

(fn auto-conjure-select []
  (let [cmd (.. "ConjureShadowSelect " (shadow-build-id))]
    ;(a.println cmd)
    (nvim.nvim_command cmd)))

(nvim.nvim_create_user_command :AutoConjureSelect auto-conjure-select {})

{: shadow-build-id : auto-conjure-select}
```

In `.config/nvim/init.vim`

```
" Need to let aniseed auto compile
let g:aniseed#env = v:true

" put the AutoConjureSelect() function defintion into my fennel script, and the script parse shadow-cljs.edn to get the build id.
lua require('auto-conjure')
autocmd BufReadPost *.cljs :AutoConjureSelect
```

**Comment by Olical** [comment]
This is really cool, nice work!
