### ISSUE TITLE
Passive logging causes the HUD to constantly pop back up

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#321]
As discussed on Clojurians Slack and seen by many, if you have evals that take a long time to respond or passive logging from some other system you'll continually have the HUD pop up. This is kind of annoying and there's no solid one size fits all solution, however I can think of a few things!

It's also worth mentioning this basically breaks stuff like telescope which also relies on floating windows. So maybe a good fix would be keeping the HUD working but popping it BELOW telescope and ensuring other floating windows continue to work as it does it's thing. I have a feeling the weird interactions with other plugins is caused by the window focus shifting around in the background.

 * User input timeout. So if some log output appears N seconds after the last user input it won't be displayed in the HUD since it's probably passive output you don't care about as you edit.
 * Fix HUD interactions with other plugins so it can keep popping up but other systems will still work and it'll appear BELOW any other floating window.
 * Do some sort of user input eval count tracking, so for each user initiated eval we say "we can pop the HUD up once for this eventually". Each time the HUD appears the counter goes down by one. This is obviously FAR from perfect, it's very easily provably incorrect but _may_ be a good approximation for 95% of use cases and then harmless when it does go wrong. Worth looking into!
 * Maybe only pop the HUD up for returned values, not stdout/err style text. That combined with a user timeout on results could be a good combination!

Feel free to add more ideas below. This UX change would be really useful!

**Comment by harryvederci** [comment]
Thanks for picking this up!

> User input timeout. So if some log output appears N seconds after the last user input it won't be displayed in the HUD since it's probably passive output you don't care about as you edit.

If I read this correctly, it could be pretty confusing if it wouldn't be displayed. I'd personally prefer it to still be displayed, but the HUD just not popping up if that's possible. So it's added to whatever is going to displayed on the next popup, but it just doesn't *trigger* a popup.

> Maybe only pop the HUD up for returned values, not stdout/err style text

This sounds very good to me!

**Comment by daveyarwood** [comment]
I think I would actually prefer if the HUD continued to pop up for stdout/stderr text, and if it showed the bottom of the log each time it pops up.

The thing I do most in Conjure is run integration tests with our custom test runner that prints a lot of interim steps on stdout. I prefer not to have to open the Conjure log buffer to see the end of the output, so it would be nice if I could eval a form in my source file to run a test, and see the output at a glance in the HUD without opening the log buffer. Right now, I usually have to open the log buffer because, although the HUD continues to pop up with each print to stdout, it only shows me the log starting from where I eval'd the last form.

**Comment by Olical** [comment]
@harryvederci oh sorry for the confusion, the text would definitely be there, I'd just not display the HUD for some things is all I'm thinking.

@daveyarwood 🤔 it should be scrolling down on subsequent stdout printing... maybe there's another issue there.

Ultimately, any change I make here will mess with someone's workflow. Doing nothing also kind of messes with someone's workflow. Any solution I implement will be gated behind an option and I'll probably default to the existing behaviour for now.

I'm currently thinking of having a set of things you want the HUD to appear for which defaults to `[:user-action :eval-result :stdout :stderr]` or something to that effect. Will be hard to implement that across the board for all languages so I'll have a think about which lowest common denominator of an idea fits best.

**Comment by Olical** [comment]
OH! IDEA! If I can detect that the user is currently using a floating window, suppress the HUD. I _think_ that kinda addresses the main UX problem of floating windows thrashing and ruining each other while keeping the HUD as is for normal use.

**Comment by Olical** [comment]
This change is on `develop` I also popped the HUD below all other floating windows through `zindex` config. Hopefully this addresses all the UX / plugin conflict issues without changing any other behaviour or introducing any complex code. This solution is REALLY simple, so hopefully it's elegant enough to solve the issue without compromises.

Let me know what you think!

**Comment by Olical** [comment]
Still having a think about the behaviour of constantly having logs pop the HUD back up over and over as you work. That's now a different issue, at least this change should stop Conjure conflicting with Telescope.

**Comment by Olical** [comment]
Decided: Keeping the new rule of "no HUD if you're already doing something in a floating window" but I'm also going to add a concept of low/high priority log items. I'm going to tag things like stdout/stderr as low priority. I'll then add an option that lets you toggle this priority / log level (maybe a numeric log level, not sure yet).

If I detect, say, 10 log messages that each trigger the HUD with 0 user input in one session I'll log a message saying "hey, maybe set this option for this session if these log entries are getting on your nerves". This way it's entirely optional and easy to toggle on if one particular session is weird compared to others.

This works for my example use case: In one project I work on I start the system inside a jack-in REPL (not an external terminal) and that system constantly logs heartbeat messages. So for _that_ project I'll toggle down the priority so I only see eval results.

**Comment by daveyarwood** [comment]
That sounds great!

**Comment by Olical** [comment]
Implemented on `develop`! Some feedback on this would be great, it's kinda fiddly and involves state to display the help message when a REPL is being noisy. It seems to work well though! So you _can_ turn off low priority messages (just clojure stdout / stderr for now) for the HUD all the time with this option. But the idea is that it's an option you're reminded of when you need it on a rare occasion.

Hopefully that's not too annoying and obtrusive! I wouldn't want to add an option to turn off a hint about another option... so I'm hoping this is rare enough that it only pops up when you actually need it so it won't be annoying.

**Comment by harryvederci** [comment]
The "no popup if a popup is already open" thing works great, thanks Olical!

**Comment by harryvederci** [comment]
... and so does the "ignore low priority" option. This is perfect for me!
