### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by marhu98** [Olical/conjure#322]
Hi everyone, shouldn't there be a place where the bindings for form evaluation can be found? There aren't any even in the wiki.

**Comment by Olical** [comment]
Please see `:help conjure` and `:ConjureSchool` as mentioned in the README, I hope that helps!

**Comment by daveyarwood** [comment]
I have noticed a pattern where it isn't clear to new users that there is a separate help page (`:help conjure-client-clojure-nrepl`) for the Clojure nREPL client. I think this distinction makes sense, given that Conjure is a general plugin that can be used in multiple languages besides Clojure, but I wonder if there is a way that we could make it clearer in the documentation how to get started as a Clojure programmer using Conjure.

**Comment by marhu98** [comment]
Ah thanks!

**Comment by daveyarwood** [comment]
I'm having a closer look now at the README, and I like that right at the top you have links to quick start guides for each language supported.

Maybe it would be helpful if you included some basic examples [here](https://github.com/Olical/conjure/wiki/Quick-start:-Clojure#start-editing) at the bottom of the Clojure quick start guide :bulb:   Just the very basics, like press `<localleader>ee` to evaluate a form. And then you could link to the help text for more information.
