### ISSUE TITLE
Is there a way to unmap ,cd (disconnect)?

### ISSUE THREAD

**Issue by Liverm0r** [Olical/conjure#333]
I have ,c mapped as commenting a form
`(u.map :<Leader>c "<Plug>(sexp_move_to_prev_bracket)i#_<C-[>" )`

After I press `,c`  I have to wait one second before commnet inserted, because `,cd` refers to ConjureCljDisconnect and `,cf` to conjureCljConnectPortFile.

The only way I can think of right now is to map may comment to `,cc`

**Comment by Olical** [comment]
https://github.com/Olical/conjure/blob/422cadf51dd44306713f3f7965e40ec606290c49/doc/conjure.txt#L228-L235 this should do the trick!

**Comment by Olical** [comment]
Closing since I think this was just a case of finding the right docs. Please re-open if that doesn't work!
