### ISSUE TITLE
Check that the "is treesitter enabled" function asks the current buffer

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#334]
A user in discord noticed that it's trying to use treesitter on the develop branch in a Racket buffer which doesn't have treesitter support yet. So that means the function that checks the support isn't checking the current language / buffer, just if it's enabled globally in some way.

I'm pretty sure I added an explicit check for this, so maybe something weird is going on.

**Comment by Olical** [comment]
I can't reproduce this, Racket is working fine for me 🤔

**Comment by rhcher** [comment]
I can't reproduce it with minimal vimrc too... And I try to comment part of my config to figure out what lead to that but nothing found.

**Comment by Olical** [comment]
I'm guessing you did have syntax highlighting of some kind at the time too? Like it wasn't just black and white text?

**Comment by Olical** [comment]
I think I reproduced it and found the issue! For me, it was that I'd updated Neovim but I hadn't updated my tree-sitter support with `:TSUpdate`. Then the issue went away! I don't know how I can ever test for that though, Neovim is reporting that the language you're editing is TS supported, so I query for a form and it returns an empty string... not much I can do to detect that I don't think.

Unless someone has any ideas / knows of some tree-sitter API function I can use to verify that the language TS support is working correctly and up to date... I think the solution is to ensure you run `:TSUpdate` regularly.

**Comment by Olical** [comment]
Oh no way! I thought that was equivalent code and just a kind of useless
change that might prevent a bug in the future. That's great to hear!

I think `nil` is the same as `false` for Lua, but maybe there's some
differences sometimes.
