### ISSUE TITLE
Possible issue with `tree-sitter.enabled?`

### ISSUE THREAD

**Issue by TerseTears** [Olical/conjure#338]
Hello. 

I believe the culprit is the recent commit 7469e267e4eab65e2ec1aec3f398c0b5c4ff62b1. I think the line with `(and ok? parser)` doesn't actually evaluate to a boolean, resulting in `ts.enabled?` always failing. I'm not sure though, I may be using lower versions of things.

**Comment by Olical** [comment]
Quite possibly! I just pushed a small change to develop to ensure it's always a boolean.

**Comment by TerseTears** [comment]
Thank you. That fixed the issue.
