### ISSUE TITLE
Documentation on client features, configs, and mappings ? 

### ISSUE THREAD

**Issue by Dotrar** [Olical/conjure#347]
Loving Conjure, and I've implemented a bit of a basic / rudimentary Common Lisp client in it here: https://github.com/Olical/conjure/pull/296

As from previous discussions, I've found that the Clojure client has a few more features and nice things to have that I haven't yet implemented. 

I'm wondering if it's worthwhile to have a bit of a config / feature-matrix / keymapping file or wiki page that we can reference (and keep updated :crossed_fingers: ) such that I ( as the common lisp client implementer ) or anyone else who wants to maintain their clients of choice can try and keep up with a bit of a feature parity with the "main" ?

It also serves as a bit of a bulletin board for what features conjure has on the whole, and what is yet to be implemented ?

**Comment by Olical** [comment]
Good idea! I think a wiki page might be a good bet where I can also expand on each feature for implementers.

**Comment by Olical** [comment]
Starting that work here https://github.com/Olical/conjure/wiki/Client-features

**Comment by Olical** [comment]
I haven't added any mappings docs since they're all under `:help conjure-client-clojure-nrepl` for example and duplicating that will lead to SO many issues, but I've finished documenting the supported features and how they should be implemented with links to examples. I hope this is good!

**Comment by Dotrar** [comment]
This is a great starting point and exactly what I'm talking about! Thanks for the great work!
