### ISSUE TITLE
"attempt to concatenate a nil value" in "connect-command"

### ISSUE THREAD

**Issue by goto-engineering** [Olical/conjure#353]
When I try to run `:ConjureConnect` in a Clojure project with an `.nrepl-port` file, I get the following error:
```
E5108: Error executing lua ~/.vim/plugged/conjure/lua/conjure/client.lua:175: attempt to concatenate a nil value
stack traceback:
        ~/.vim/plugged/conjure/lua/conjure/client.lua:175: in function 'connect-command'
        [string ":lua"]:1: in main chunk
```

Latest version of Conjure (4.34.0) and nvim 7.0.

**Comment by Olical** [comment]
Hm, I can't reproduce that 🤔 I've added a guard for where I think this nil concat happened but I don't think I can reproduce your exact issue. Were you in a `.clj` file and do you have Clojure syntax highlighting working? Just so I know your editor is picking up the filetype correctly.

**Comment by Olical** [comment]
The guards against this are on the develop branch, so you could always try that and at least the error would come out. I think the error you're seeing is from trying to print a different error which might explain what's going on.

**Comment by goto-engineering** [comment]
I'm not in a Clojure file - yet. My Clojure files are in `src` so I typically open vim in the root (hoping to pick up the nrepl-ports file) and then open a .clj file.

When I don't try to ConjureConnect, and simply open a clj file, Conjure says no nrepl-ports file was found and starts its own, which doesn't have my deps.edn dependencies.

**Comment by goto-engineering** [comment]
On the `develop` branch I'm now getting this error:
```
E5108: Error executing lua [string ":lua"]:1: Conjure client '' doesn't support function: connect
stack traceback:
        [C]: in function 'connect-command'
        [string ":lua"]:1: in main chunk
```

**Comment by goto-engineering** [comment]
So I tried creating an empty test.clj file in the root folder so I could run vim a) in a clojure file b) next to the .nrepl-ports and deps.edn file. Conjure says connection refused (repl is running) and then seems to delete (!) the .nrepl-ports file?!

**Comment by goto-engineering** [comment]
Ok so I think it was due my me configuring the nrepl alias wrong. Now, I can start vim and navigate to a clojure file and it connects correctly. Just kind of a weird error? Maybe if you showed "Can't connect to REPL at port xxxx" instead of that lua error, I would've just realized my mistake immediately.

**Comment by Olical** [comment]
Glad to hear it. I think I fixed this error in the latest release too, it was a case of "error while trying to print the error" which isn't great.
