### ISSUE TITLE
Unable to locate external dependencies

### ISSUE THREAD

**Issue by belarte** [Olical/conjure#356]
Hi,

I have a problem when trying to evaluate a form where I am requiring a package that is not from Clojure or local.

The code/tests are running perfectly fine in the command line. Conjure works perfectly fine when only requiring namespaces from the current project or from Clojure itself (e.g. clojure.string). It is just failing when trying to load packages that are in the deps.edn (e.g. Instaparse, Reitit).

Here is an example of an error I am seeing in Conjure after trying to load the current buffer:
```
; --------------------------------------------------------------------------------
; eval (buf): /project/src/parser/parser.clj
; (err) Execution error (FileNotFoundException) at parser.parser/eval5645$loading (REPL:1).
; (err) Could not locate instaparse/core__init.class, instaparse/core.clj or instaparse/core.cljc on classpath.
```

I suspect it is not a bug but a mere configuration problem on my side (something like a missing classpath settingor something like that), though I can't seem to find any pointers on how to solve that issue. Any help would be appreciated!

I am running clj 1.11.1.1113 and a fairly recent version of Conjure (I think I updated my NeoVim plugins last week).

**Comment by belarte** [comment]
So, I find the problem. It was between the keyboard and the chair...

I somehow forgot that I needed to start my REPL in the root folder of my project. Everything is working as expected.

Apologies for opening an issue for such a mundane question.

**Comment by Olical** [comment]
Ah I see! Glad you found it! Sorry I didn't get around to helping in time.

**Comment by belarte** [comment]
No worries! Thanks for all the good work!
