### ISSUE TITLE
`<localleader> ee` not working in tutorial + several other bugs

### ISSUE THREAD

**Issue by Serif-7** [Olical/conjure#367]
`<localleader>eb` works, but `ee` does not. The manual command `ConjureEval` works to advance the tutorial. For lesson 3, `<localleader>er` does not work, but `<localleader<eb` does. In fact for everything after lesson 2, `<localleader>eb` works, but the given command doesn't. `<localleader> Eiw` worked, though.

Great plugin, by the way.

**Comment by Olical** [comment]
I can't reproduce this at all, it does sound like highlighting or tree sitter issues within your Neovim setup though.

Are you using tree sitter? If so, make sure you've updated the parsers, especially if you've recently updated Neovim.

If not, do you have syntax highlighting because that's required to select parts of code.

**Comment by Serif-7** [comment]
I think something is wrong on my end. I'm on Neovim v0.61, which might have something to do with it. I'll update in a bit and then re-test.

**Comment by Olical** [comment]
Did you manage to get this working by updating by any chance? I wonder if there's something I changed to support Neovim 0.7+ (since Neovim introduces breaking changes regularly now) that isn't backwards compatible with 0.6~ like I intended. I've tried to make every 0.7+ fix work in older versions with version gating but I might have missed something.

**Comment by jsn** [comment]
I'm not sure it's the same bug, but I think I can reliably reproduce _something_ like this. Here's how:
1. Create a file containing:
```clojure
(ns a)
42
```
2. have a REPL for it
3. in neovim, move cursor to "42" and type, for example, `<localleader>ee` . Nothing happens (which is probably not a bug).
4. now, with cursor still on "42", type `0C(+ 2 3)<Esc>` (replacing the line with a new expression)
5. now, with cursor anywhere inside of `(+ 2 3)`, type `<localleader>ee`. Nothing happens (which seems to obviously be a bug).

**Comment by Olical** [comment]
Hm, I can't reproduce that one @jsn 🤔 works totally fine for me using your exact steps. Just a hunch, have you run `:TSUpdateSync` recently? (if you're using treesitter at all, that is)

**Comment by jsn** [comment]
I think I am using treesitter, since I have `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}` in my init.vim -- is that correct? `:TSUpdateSync` says "All parsers are up-to-date!". Still, the sequence I described above works every time for me -- conjure is largely broken after that first `,ee` on a parenless atomic value

**Comment by Olical** [comment]
Yep, as long as you have that and you've run `:TSInstall clojure` at some point Conjure will lean on it for all of the form extraction.

I'll keep trying to reproduce your issue, it's really odd. And to be clear, you're talking about Clojure with an nREPL connection to a JVM Clojure instance? Or something else?

**Comment by jsn** [comment]
`:TSInstall clojure` says "clojure parser already available", so apparently yes, I'm using it.
Yes, it's JVM clojure + nREPL.
I just did `git bisect` on this one, here's what it says:
> a4cd6e089cbb75e2aec058515955f6ed668cf000 is the first bad commit

**Comment by Olical** [comment]
Well that tells us it's to do with treesitter, which I'm also using and it's working fine 🤔

**Comment by jsn** [comment]
Huh. If I do `:TSEnable highlight clojure` before, the bug doesn't happen.

**Comment by Olical** [comment]
Hmm, interesting! I'll try with that disabled and see what the treesitter API returns when I call it. Maybe it's just returning `nil` when I query what's under the cursor if you don't have highlighting enabled! That's kinda what it looks like. Could even be a Neovim + treesitter bug?

**Comment by jsn** [comment]
Is there anything I can do to help reproducing this? For some reason I see this bug triggered a lot today in my mundane activities. I use `nmap <buffer> <localleader>Tr :TSEnable<space>highlight<space><bar>:TSDisable<space>highlight<cr>` to punch some sense into treesitter now and then, but it's obviously not ideal :)

**Comment by dylanscott** [comment]
I ran into the same issue with a fresh Neovim install and fork of magic-kit that I added nvim-treesitter to (as it seemed to be recommended in the [Conjure readme](https://github.com/Olical/conjure#tree-sitter-support)). It seemed like I could eval forms under my cursor that were there when I opened nvim but any forms added/modified afterward could not be evaluated. I was quite puzzled until I found this thread!

Also thank you for your work on Conjure! I've had a couple of false starts trying to get into Clojure and the tooling always felt a bit daunting but between Conjure and the new (to me) Clojure CLI tools things feel so much smoother this time around. And being able to interactively configure nvim with Fennel is kind of blowing my mind

**Comment by jsn** [comment]
Yeah, it's basically impossible to enter an expression and immediately eval it now -- I have to toggle treesitter every time before `,ee` / `,er`. Occasionally (that's rare, though) it also evals the wrong piece of code (so I receive complaints about unknown identifiers or perhaps even unmatched parens, not sure) -- and it all goes away after treesitter toggle.

**Comment by Olical** [comment]
So I don't have this issue and have never seen it despite using tree sitter the entire time in multiple languages.

Would you be able to list any tree sitter related plugins you have, if any? Maybe some that change highlighting or allow you to manipulate the tree? Maybe your theme too?

And Neovim / OS version information can't hurt. If we can compare a few of you that have this maybe we can work out what's doing it.

**Comment by jsn** [comment]
@Olical did you try to reproduce it while having treesitter *highlighting* disabled (`:TSDisable highlight clojure`)? Because that's when it happens for me.

**Comment by Olical** [comment]
Oh, no I haven't but I presume that will reproduce the issue. Which means tree sitter doesn't update it's in memory tree on change if highlighting is disabled? Is there a way to force tree sitter to refresh the tree I wonder?

**Comment by jsn** [comment]
I really know nothing about treesitter, sorry. By the way, the bug happens even when I have `:TSEnable indent` or `incremental_selection` (but not `highlight`) -- shouldn't treesitter update its representations in this case?

**Comment by jsn** [comment]
Not sure if it matters, but here's my plugin section of init.vim and my nvim --version output:
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
https://gist.github.com/jsn/56e0d94e4a7f446930a9f0c5e9765915

**Comment by dylanscott** [comment]
It seems like it's able to fall back to logic that behaves correctly when treesitter isn't installed. I wonder if the [treesitter `enabled?`](https://github.com/Olical/conjure/blob/08236a13164a948fe403f34fe1f593ead0a3c6fe/fnl/conjure/tree-sitter.fnl#L16-L29) check could check if highlighting is enabled if it's necessary for the cursor functionality to work? Otherwise it might just be worth mentioning in the treesitter section of the readme that highlighting must be enabled for the `ConjureEval*Form` commands to work

**Comment by Olical** [comment]
So, my backup is to do what you just said @dylanscott, however I _may_ have fixed this. Testing myself now, but letting people know: I think I was supposed to call a function to re-parse the tree before I accessed it, which maybe is done for me if you have syntax highlighting on? So now I'm calling that parse function maybe that'll help!

If not, I'll do as you say and not rely on TS if the highlighting is disabled.

**Comment by Olical** [comment]
So @jsn's repro with my ts highlighting disabled (I think?) is working for me now! I'd love to hear a confirmation from someone else though.

**Comment by Olical** [comment]
I'm 99% sure I've fixed this without compromises 🎉

**Comment by jsn** [comment]
> I'm 99% sure I've fixed this without compromises tada

Yes, sir, I believe you truly have! At least I can't reproduce it on fresh dev. Thank you so much! I'll keep an eye out for it next time I'm deep in some Clojure codebase, but for now I consider it fixed. Yay!
