### ISSUE TITLE
<localleader>er behavior change in 560e0c7f9

### ISSUE THREAD

**Issue by jsn** [Olical/conjure#368]
Commit 560e0c7 changes `<localleader>er` behavior  like this:
If you have
```clojure
#_(+ 1 2 3)
```
as a top-level form, and cursor is on "2", and you type  `<localleader>er`, then,
before 560e0c7 : it evaluates `(+ 1 2 3)`, producing `6`.
after 560e0c7 : apparently it evaluates everything including `#_`, producing nothing.

I think the behavior before 560e0c7 was *much* more useful, I routinely leave snippets like this in my code as a quick test etc. Is it possible to bring it back?

**Comment by adz5a** [comment]
i know it implies a change in your workflow, but could'nt you use `(comment (+ 1 2 3)) instead of the reader macro (that's the pattern i personnally use, kind of because of the behaviour you mentioned but also because i find more flexible than the macro, which is imo more for "inline" examples)?

**Comment by jsn** [comment]
My problem is with deeply nested forms. Before the change, I could be making changes deep inside some commented out form, and use `,er` to immediately evaluate the root form, without losing my cursor position. After the change, I must move cursor to the outer layer of parens. This applies both to `(comment ...)` comments and to `#_` comments alike -- `,er` now evaluates both is comments, so I there is no way to eval the outer one without losing my cursor position.

**Comment by Olical** [comment]
Interesting! I added support for evaluating the entire form including it's reader macro prefix when using tree-sitter recently:

```fennel
(def- reader-macro-pairs
  [["#{" "}"]
   ["#(" ")"]
   ["#?(" ")"]
   ["'(" ")"]
   ["'[" "]"]
   ["'{" "}"]
   ["`(" ")"]
   ["`[" "]"]
   ["`{" "}"]])
```

But as you can see there, I didn't add anything specific around the reader macro comment. I'll have a look, this could be an accidental change on my part, I also agree that evaluating reader conditional commented forms should probably still evaluate them.

As for treating comments as do blocks, you can find out more about that here https://github.com/Olical/conjure/blob/d88a3c8f911b92db5bf34b3b0e7a9e10692bafcb/doc/conjure.txt#L356-L374

**Comment by jsn** [comment]
Thanks! `let g:conjure#eval#gsubs = {'eval-reader-comment': ['^#_', '']}` seems like a very acceptable workaround so far (much better than ``nmap <buffer> ,eR me,E15af`e`` [uses vim-sexp] that I came up with :) )

**Comment by jsn** [comment]
> ```viml
> let g:conjure#eval#gsubs = {'eval-reader-comments': ['^#_', '']}
> ```

That's practically exactly what I said above :))

**Comment by Olical** [comment]
I'm a big dum dum who didn't read properly. Looks good to me! 😅
