### ISSUE TITLE
Guile connection requires to execute ConjureConnect twice

### ISSUE THREAD

**Issue by ekaitz-zarraga** [Olical/conjure#373]
I tried to connect to Guile and it's doing weird things, this is the result of calling the same `ConjureConnect /home/Ekaitz/projects/GUILE.SOCKET` command. In the first it says `pipename` is not defined, even if I sent it as an arg to `ConjureConnect` and the second time it just connects.

```
; /home/Ekaitz/projects/GUILE.SOCKET (disconnected)                             │
; g:conjure#client#guile#socket#pipename is not specified                       │
; Please set it to the name of your Guile REPL pipe or pass it to :ConjureConnec│
; Empty result                                                                  │
; ------------------------------------------------------------------------------│
; /home/Ekaitz/projects/GUILE.SOCKET (connected)                                │
; Empty result                                                                  │

```

Is this expected behavior?

Thanks!

**Comment by Olical** [comment]
Probably not! Seems like a bug to me in something that's trying to be helpful and failing at it. I'll take a look soon!

This may also be interesting to you: https://github.com/Olical/conjure/pull/369

**Comment by Olical** [comment]
Fixed on develop, it was just as the module lazy loaded it triggered a connection attempt which would log a warning if you didn't have a guile socket path set. That warning now only displays if you invoked `ConjureConnect` and will be silent if it's a passive connect from opening a guile file / loading the module for the first time.
