### ISSUE TITLE
Is it possible to remap "Evaluate Motion"?

### ISSUE THREAD

**Issue by elmehalawi** [Olical/conjure#374]
I'm trying to remap "evaluate motion" to "E", while leaving all the other keybindings behind local leader as they are. I found all sorts of :ConjureEval* commands in the command input, but I didn't see :ConjureEvalMotion. Is it possible to rebind it from lua?

Sorry if this is a noob question, I'm fairly new to neovim.

**Comment by Olical** [comment]
Yep, you can! It looks kind of awkward and it's documented somewhere in `:h conjure` but this should do the trick:

```viml
let g:conjure#mapping#eval_motion = ["E"]
```

So you wrap the mapping string in a list to signify that it's kind of a raw, unprefixed, mapping. As you can tell, this was added quite late after I committed to the simple auto prefixed string. Kinda gross API really but it does the job until I one day rewrite all of the mapping code once again 😅

**Comment by elmehalawi** [comment]
Thanks! And thanks for this awesome plugin!
