### ISSUE TITLE
Avoid autoconnect when file is opened

### ISSUE THREAD

**Issue by ekaitz-zarraga** [Olical/conjure#377]
Hi,

I've been looking in the documentation but I can't find a good way to prevent conjure from autoconnecting.
I just want to activate conjure manually, because I use many scheme/lisp files as configuration and it's automatically loading a mit scheme shell (wrongly even, because it's not installed). I just want it disable the behavior until I selectively switch it on in certain cases.

Is this possible?

**Comment by Olical** [comment]
Hey! I don't think any client has an option for this yet but it wouldn't be hard to add. Which client are you talking about specifically? Is this mostly Scheme or any client?

**Comment by ekaitz-zarraga** [comment]
I'd love to do this globally. Keep conjure inactive until I selectively run it.

**Comment by Olical** [comment]
Until I get a chance to add an option for every client, I think the best approach would be to use any lazy loading systems your plugin manager has. I remember with vim-plug I could load a plugin with a certain command, so you would set `command = ConjureConnect` then when you invoked `ConjureConnect` for the first time it loaded the plugin and executed the command.

That might be the best stop gap for now.

**Comment by Olical** [comment]
I'll have a look at adding an option for this asap though! Making all of the clients a little more passive with one option would be good.

**Comment by ekaitz-zarraga** [comment]
Thanks a lot!

**Comment by Olical** [comment]
This is on develop! Sorry it took a while! `let g:conjure#client_on_load = v:false` should do the trick.
