### ISSUE TITLE
Hotkeys don't work in Guile

### ISSUE THREAD

**Issue by ekaitz-zarraga** [Olical/conjure#378]
Hi!

I managed to connect to a guile repl and send code by `:<range>ConjureEval` but the hotkeys don't work, but they do work in the `:ConjureSchool` any idea of what I might be doing wrong?

**Comment by Olical** [comment]
Hmm, not sure right now but I don't think I have enough information.

So `<localleader>ee` etc works inside the school but when you're inside a Guile / Scheme buffer you can't run `<localleader>ee`? Do you see anything in the log when you do this, like an evaluation started but there's no response?

Can you send me the log after reproducing this? That'll help a lot! If it's empty that also tells us a lot. You can also set `:let g:conjure#debug = v:true` to enable some more logging into the log buffer.

**Comment by ekaitz-zarraga** [comment]
Let me share more info:

I have set the Conjure plugin to be started by vim-plug when I run ConjureConnect. Like this:

``` vimscript
Plug 'Olical/conjure', { 'on': 'ConjureConnect' }
```

The keys literally don't launch anything, it's just like ignoring the keymap. For example, if I do `,ee` (being `,` the localleader) it just does `ee`, which moves the cursor two times to the end of the word.

**Comment by ekaitz-zarraga** [comment]
I just tried loading the plugin on startup and the problem persists. In Scheme files I can't use the hotkeys...

Also, setting the debug, connecting to a repl and closing the file gives me this error:

```
Error executing vim.schedule lua callback: ....local/share/nvim/plugged/conjure/lua/conjure/buffer.lua:42: Failed to delete line
stack traceback:
	[C]: in function 'new_buf_fn'
	....local/share/nvim/plugged/conjure/lua/conjure/buffer.lua:42: in function 'upsert_buf'
	...tz/.local/share/nvim/plugged/conjure/lua/conjure/log.lua:329: in function 'append'
	...tz/.local/share/nvim/plugged/conjure/lua/conjure/log.lua:498: in function 'dbg'
	...share/nvim/plugged/conjure/lua/conjure/remote/socket.lua:49: in function 'cb'
	vim/_editor.lua:256: in function <vim/_editor.lua:256>
```

**Comment by Olical** [comment]
That error is really weird, I'm not sure if I've ever seen that before 😢 sorry about that!

And here's my only hunch right now: Have you set your localleader? ConjureSchool sets the `maplocalleader` to `,` for you if you don't have one (I think it prints that in the file but it's maybe hard to spot) but once you're done with the school you need to set your own, it won't set one for you.

Conjure isn't bound to `,` by default, it's prefixed by `localleader`, which you need to set yourself. Maybe you have but I thought I'd check.

**Comment by ekaitz-zarraga** [comment]
I set it and it doesn't work. :(

**Comment by Olical** [comment]
Hmm, what about in a .fnl buffer? Does that work? And you're not lazy loading the plugin through a plugin manager, are you?

**Comment by ekaitz-zarraga** [comment]
Oh it was that! I was lazyloading the plugin and that was breaking everything!
Still, I'd like to lazy load the thing, is there any way we can support that?

**Comment by Olical** [comment]
Lazy loading hooks into the commands defined by the plugin I think? So you tell it which commands the plugin defines then when you invoke those the loader intercepts them, loads the plugin then invokes the real command.

I'm not sure how you do this though... it varies in plugin manager to plugin manager. I'd personally just use a filetype based lazy loading, not command based. If you can configure it to only load in Scheme, for example, you're 90% of the way there with 5% of the effort. Hopefully that'll be enough!

I've found lazy loading plugins on commands ONLY works for me with small plugins with one or two commands where I created the mappings myself to call them. I gave up using lazy loading a long time ago though and my nvim still starts in < 100ms, so I'm fine with that.

I'd personally just recommend lazy loading on filetypes if you really notice the difference. Or have a mapping that sort of turns Conjure on, your own custom mapping that invokes a Conjure command to load it.

**Comment by ekaitz-zarraga** [comment]
Can you show me an example of filetype based lazy loading?
Anyway, just leaving conjure run with no restriction does not make my vim go slower so I can just leave it.

**Comment by Olical** [comment]
I think that depends on the plugin manager you're using and I definitely won't remember how 😅 I think last time I did it was 4+ years ago in vim-plug, should be in their docs?

**Comment by Olical** [comment]
But yeah, Conjure lazy loads every module, so it only loads code as it's used thanks to Aniseed's `autoload` call. Shouldn't notice a startup difference, regardless of how big Conjure gets 😄

**Comment by ekaitz-zarraga** [comment]
Thank you very much!
I'll close the issue then, sorry for the noise!
