### ISSUE TITLE
don't log giant objects/format julia output the same way the repl formats things!

### ISSUE THREAD

**Issue by josephsdavid** [Olical/conjure#380]
I am running into a slight issue at least with the Julia client, everything works great, but, if i run a bit of code that returns say a table with 600k rows, every single row is stored in the log, which causes a conjure to eat up all my cpu!

MWE:

```julia
import Pkg
Pkg.add("DataFrames")
using DataFrames

x = DataFrame(1:1e7)
```

When I run this in the julia repl, I get:

```
10000000×1 DataFrame
      Row │ x
          │ Float64
──────────┼────────────
        1 │  1.0
        2 │  2.0
        3 │  3.0
        4 │  4.0
        5 │  5.0
        6 │  6.0
        7 │  7.0
        8 │  8.0
        9 │  9.0
       10 │ 10.0
       11 │ 11.0
       12 │ 12.0
       13 │ 13.0
       14 │ 14.0
       15 │ 15.0
       16 │ 16.0
       17 │ 17.0
    ⋮     │     ⋮
  9999984 │  9.99998e6
  9999985 │  9.99998e6
  9999986 │  9.99999e6
  9999987 │  9.99999e6
  9999988 │  9.99999e6
  9999989 │  9.99999e6
  9999990 │  9.99999e6
  9999991 │  9.99999e6
  9999992 │  9.99999e6
  9999993 │  9.99999e6
  9999994 │  9.99999e6
  9999995 │  1.0e7
  9999996 │  1.0e7
  9999997 │  1.0e7
  9999998 │  1.0e7
  9999999 │  1.0e7
 10000000 │  1.0e7
   9999966 rows omitted
```

However if i evaluate this block with conjure, every item is logged!!

**Comment by Olical** [comment]
Ah that sucks! Hmm I wonder if there's an option we can set to tell the REPL not to print everything? Or do we have to receive everything from the REPL and then do the truncating inside Conjure 🤔 

I'd like to set some sort of global that auto truncates, that's what I do with Clojure / CIDER and it does some clever nested data truncation which is far smarter than anything I could do inside Conjure.

**Comment by josephsdavid** [comment]
> Ah that sucks! Hmm I wonder if there's an option we can set to tell the REPL not to print everything? Or do we have to receive everything from the REPL and then do the truncating inside Conjure 🤔 
> 
> 
> 
> I'd like to set some sort of global that auto truncates, that's what I do with Clojure / CIDER and it does some clever nested data truncation which is far smarter than anything I could do inside Conjure.

Auto truncation would be very cool! I will spend some time to try to figure out if there's a command or flag I can use to get the julia server to handle the printing and truncation! By the way thanks for making this!

**Comment by usmcamp0811** [comment]
Ahh I missed this issue before making mine... [This is my issue](https://github.com/Olical/conjure/issues/416). Julia has functionality baked into it to do this. It is the done my simply appending a `;` to the end of the line and the REPL knows not to return the results. It seems like Conjure is seeing the `;` and just treating it like a code/line break, when it should be sending it to the REPL also...

**Comment by Olical** [comment]
So could we consider this done now that the support for `;` works properly? 🤔
