### ISSUE TITLE
Atoms are not correctly lexed.

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#385]
I'm not sure this is a conjure issue or a treesitter-clojure issue(I've enabled TS support):

Take Clojure for example, put your cursor on `+'`'s first character and query doc for it, it would yield document for `+`, rather than `+'`

**Comment by glyh** [comment]
Pretty sure this is a conjure issue, because here's what TSPlayground says:
![image](https://user-images.githubusercontent.com/12870742/182019419-d77df42a-05ae-4a8c-9640-9b810c2d553f.png)

**Comment by Olical** [comment]
Conjure doesn't use tree sitter for doc, eval, def. It uses vim's cword, although tree sitter would be better! I'll have a look if I can swap that over now. Here's the existing word / symbol extraction code:

```fennel
; https://stackoverflow.com/questions/15020143/vim-script-check-if-the-cursor-is-on-the-current-word/15058922
(defn word []
  (let [cword (nvim.fn.expand "<cword>")
        line (nvim.fn.getline ".")
        cword-index
        (nvim.fn.strridx
         line
         cword
         (- (nvim.fn.col ".") 1))
        line-num (nvim.fn.line ".")]
   {:content cword
    :range {:start [line-num cword-index]
            :end [line-num (+ cword-index (length cword) -1)]}}))
```

**Comment by glyh** [comment]
That is good as a fallback though.

**Comment by Olical** [comment]
Okay, swapped to tree sitter when enabled on `develop`! Let me know if that works for you, it seems to work for me!

**Comment by glyh** [comment]
Great, it's working for me.

**Comment by glyh** [comment]
Seems like there's other issues:
`(- 1 2 3)`

I put my cursor on the left bracket and press K to invoke doc, it should leave a warning in the logs or whatever, but conjure panics with this error message:

![image](https://user-images.githubusercontent.com/12870742/182026125-7e120d49-c61e-486d-b76a-42198fb9c157.png)

**Comment by Olical** [comment]
Oh that's really weird, I'll take a look at this soon! Thank you for reporting with the error, I _think_ this is an NPE from somewhere deeep down.

**Comment by Olical** [comment]
Hmm I can't reproduce this, mine picks the right word as you described... however I've put in a guard to protect against this error I think. I'm pretty sure it's caused by Fennel's generated destructuring code trying to run on a `nil` value.

**Comment by glyh** [comment]
Yeah I tested it again and can't reproduce either...
