### ISSUE TITLE
Propossal: Refactor some legacy codes with new neovim lua APIs

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#390]
For example, nvim_set_keymap can now use callbacks, so you don't have to build a string on your own:
```lua
      vim.api.nvim_set_keymap('n', 'F', '',
        {callback = function()
          require('hop').hint_patterns({case_insensitive = false})
         end,
         noremap = true})
```

There's also nvim_create_augroup to help you create augroups:
```lua
vim.api.nvim_create_augroup('LuaAutoConfReload', {}) -- Clear old group if this config is reloaded
vim.api.nvim_create_autocmd('BufWritePost', {
  pattern = 'init.lua',
  group = 'LuaAutoConfReload',
  callback = function()
    local main_config = vim.fn.resolve(vim.fn.expand('~/.config/nvim/init.lua'))
    local current_file = vim.fn.resolve(vim.fn.expand('%:p'))
    if main_config == current_file then
      vim.cmd("luafile %")
      require('packer').compile()
    end
  end
})
```

Using these new apis instead of building your own code via vim.cmd will likely provide better performance, and less bugs.

I'd like to help if you like.

**Comment by Olical** [comment]
Hmm so I've considered this but it does break backwards compatibility for like 1-2 versions of Neovim ago, which probably breaks it for anyone on Debian etc since it's always behind. This feature of callbacks being passed into these mappings and autocmds is VERY recent, so I've been holding off using it so far.

I think I may had added one use of them though somewhere recently... so maybe that ship has sailed. We could swap to it, we just need to have VERY clear mentions of the minimum Neovim version in the documentation.

**Comment by Olical** [comment]
This will fix #389, so I'm going to do it, even if it'll bump the minimum required Neovim version, it's for the best.

**Comment by Olical** [comment]
Will take me a while to get through all the mappings and commands but will convert to first class function passing for all mappings and commands, work is under way!

**Comment by Olical** [comment]
Done! Although I haven't done the augroups yet, all of the keys and commands are updated.

**Comment by glyh** [comment]
Did you add the minimal version requirement to the README/helpfile?

**Comment by Olical** [comment]
Oh, no! It's in the VimL loader though so it prints before Conjure loads. Will add.

**Comment by Olical** [comment]
Oh there was already a warning in the installation section but it was on 0.5, updated.

**Comment by glyh** [comment]
So I think it's safe to close this issue?

**Comment by Olical** [comment]
I guess so yeah, I haven't updated autocmds yet but I'm less worried about those. Can do that first I guess, then I don't think there will be any more VimL source string wrangling left.
