### ISSUE TITLE
Inline Results Persistent?

### ISSUE THREAD

**Issue by usmcamp0811** [Olical/conjure#391]
Is it possible to make the inline results persist when you move the cursor to another line? 

Also how would I go about changing the inline virtual text color?

**Comment by Olical** [comment]
This is not a thing right now, no. How long would things persist for? Do you envision EVERY line slowly filling up with results or just the last one staying there forever until you eval something else?

And changing the colour is done through the highlight group which can be configured here https://github.com/Olical/conjure/blob/572c9717d82de38f5bc60c2942843ce9b941aed6/doc/conjure.txt#L334-L338

You can set the theme for that highlight group using normal vim concepts.

**Comment by Olical** [comment]
Closing this since I think it's hard to implement, would need a LOT of configuration + documentation to fit the needs of everyone and shouldn't be required. I think the UX of this would get kinda rough since it'd just clutter your buffer with more and more output.

**Comment by practicalli-john** [comment]
I found evaluating to a comment is far more useful than having an option to persist inline evaluation results.

It is far easier to be selective with the comment approach and evaluation results can even be persisted to file and therefore across REPL sessions.  There are occasions when I want to show expected results from evaluating a function call to help developer understand my code behavior.

**Comment by Tomcat-42** [comment]
First of all, sorry for necrobumping.

Just for future wanderers:

The behavior of closing the HUD or clearing inline text is handled [here](https://github.com/Olical/conjure/blob/5a198c0a3f2bf3d707faed9756d5bd075d5cefcb/lua/conjure/mapping.lua#L130) using the `CursorMoved` and `CursorMovedI` events.

To disable this behavior, you can remove those autocommands like so:

```lua
local autocmd = vim.api.nvim_create_autocmd
local get_autocmds = vim.api.nvim_get_autocmds
local del_autocmd = vim.api.nvim_del_autocmd

return {
  "Olical/conjure",
  ft = { "racket", "scheme" },
  event = { "BufReadPre", "BufNewFile" },
  init = function()
    vim.g["conjure#mapping#doc_word"] = false
    vim.g["conjure#highlight#enabled"] = true
    vim.g["conjure#log#hud#enabled"] = false
  end,
  config = function()
    local conjure_autocmds = get_autocmds({
      group = "conjure_init_filetypes",
      event = { "CursorMoved", "CursorMovedI" },
      pattern = "*"
    })
    for _, a in ipairs(conjure_autocmds) do
      del_autocmd(a.id)
    end
  end,
  dependencies = { "gpanders/nvim-parinfer" },
}

This snippet uses [lazy.nvim](https://lazy.folke.io/) and Neovim trunk, but you can adapt it to your own setup.
