### ISSUE TITLE
Evaluation in visual mode is broken in develop branch

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#394]
Whenever I try to evaluate in visual mode, it says: `E481: No range allowed`

**Comment by Olical** [comment]
Probably caused by the vim-repeat change I put in. I guess it doesn't like some mappings and that problem was hidden until now.

**Comment by Olical** [comment]
Reverted the commit that caused this. Will have to do a fairly large refactor to support vim-repeat and the ability to prompt for user input through neovim interactively. The two are just at odds with each other right now.
