### ISSUE TITLE
Print something less scary / more helpful as a default eval response for Aniseed / Fennel

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#395]
This commit https://github.com/Olical/conjure/commit/1945bcad14111ee68c07454ddf72fccddd9fbdad#commitcomment-81031952 and this issue https://github.com/Olical/conjure/issues/392 tried to fix a lie but introduced confusion.

When you eval the `module` macro etc it actually returns ZERO results, nothing, nada, not even a single `nil`. I made the code lie to you and say it returned `nil` because it made the most sense in this context but wasn't quite true. I changed that to instead print a warning to maybe help you realise you have to restart your REPL if it's hung / died. That has created more confusion!

So what should it be? A comment that just says `; No result`? Back to `nil`? No idea!

**Comment by glyh** [comment]
I think there is a hard but correct route. That is to hook into fennel's compiler to find out whether the input is completed or the compiler is craving for more input. Or maybe we could file an issue at fennel's site if that's super hacky/impossible.

**Comment by glyh** [comment]
https://git.sr.ht/~technomancy/fennel/tree/main/item/src/fennel/repl.fnl#L14

So here's how they deal with incomplete inputs;

We can also check if the input is complete and reject incomplete inputs.

**Comment by glyh** [comment]
Great job Olical!
