### ISSUE TITLE
Path to evcxr

### ISSUE THREAD

**Issue by DieracDelta** [Olical/conjure#397]
Is there a way to pass in the absolute path to evcxr? I don't want to add it to my path.

**Comment by Olical** [comment]
Does setting this config to something absolute not work then? https://github.com/Olical/conjure/blob/08236a13164a948fe403f34fe1f593ead0a3c6fe/doc/conjure-client-rust-evcxr.txt#L66-L70

**Comment by DieracDelta** [comment]
Whoops, this works, thanks!
