### ISSUE TITLE
Git history diverged, error during update

### ISSUE THREAD

**Issue by lockejan** [Olical/conjure#404]
Hi,
I just noticed that I couldn't update conjure with packer.
Given the error message:
> ✗ Failed to update Olical/conjure
  Errors:
    fatal: Not possible to fast-forward, aborting.
    08236a1

My guess is that the history has been rewritten. If that's the case, why did it happen?

**Comment by Olical** [comment]
I have seen some people complain about this now and again but usually a long time ago. I tried to rename `master` to `main` once and it caused issues like this so I gave up and went back to `master` for now, that was the _only_ time there was weirdness around the main branch as far as I know.

I have not force pushed to the repo ever as far as I recall and have never rebased the `master` branch, so I don't understand where this is coming from... when did you last update, was this pretty recently and it only just threw this error?

**Comment by Olical** [comment]
The commit mentioned in the error is on the `master` branch too, it's not like it's from some diverged history... so weird 🤔

**Comment by lockejan** [comment]
Thanks for clarifying. It just happened now for the first time. I did update a few days ago.
Yeah, I found the commit in my local history as well, so I'm a bit unsure as well. 
I removed conjure and installed it again.
Will try to update manually the next time and see if the issue persists then.

This way there will be at least no package manager involved. Will keep you posted then.

**Comment by Olical** [comment]
I've definitely seen people have this issue, you are not the only one and that worries me. I'd like to think I know my way around git (as much as anyone can) and I wouldn't be diverging history by mistake and somehow force pushing without realising (I never really do it, I rarely even rebase and never rebase to squash or edit).

I don't understand where these diverging histories could come from... unless it's a packer bug? But I kinda doubt it.

**Comment by lockejan** [comment]
I have the exact same problem on a different machine now.
Looking at the local clone there's definitely some changes in the history
>Your branch and 'origin/master' have diverged,
and have 1 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

Hmm, I'm going to take a closer look.
Maybe you have something in your git config that causes this.🤔

**Comment by lockejan** [comment]
`git log HEAD..origin/master` gives me

>commit a8686aa6f8760bd3cd4f219a8a4101af037c9d9b (tag: v4.39.0, origin/master, origin/HEAD)
AuthorDate: Wed Aug 31 18:45:14 2022 +0100
CommitDate: Wed Aug 31 18:45:14 2022 +0100

 >   Fix updating virtual text while not moving the cursor

>commit f05787a20584f88640be6f54d17e434074acea70
AuthorDate: Wed Aug 31 18:42:26 2022 +0100
CommitDate: Wed Aug 31 18:42:26 2022 +0100

  >  Sync sponsors

>commit ba3e996d8f631a239ba53424a1742cc28877efd5 (grafted)
AuthorDate: Wed Aug 24 20:32:24 2022 +0100
CommitDate: Wed Aug 24 20:32:24 2022 +0100

 >   Re-indent and prefix reults with res= instead of return lines

**Comment by Olical** [comment]
I've never had this with any of the other 10s of repos I interact with on a weekly basis across teams, so I have no idea why this would just happen with Conjure. And again, I have NOT force pushed and that is not a default or something that would happen without me explicitly going in and adding the argument.

I'll try to investigate soon, in the meantime, has ANYONE else seen this? It should be every single person if history has diverged?

**Comment by stefanvanburen** [comment]
I also saw this ... maybe a week ago? And I think it's maybe happened once before?

**Comment by Olical** [comment]
So why _just_ Conjure and why is this happening without me force pushing... is it when I merge PRs through the GitHub UI maybe? Maybe the merge button is defaulting to something awful?

This does not happen with any other repo I contribute to.

**Comment by stefanvanburen** [comment]
_maybe_ the GitHub UI merging, followed by a rebase-pull? (I'm really unsure 😄). 

Maybe if you had a local commit you hadn't pushed on `develop`, followed by a GitHub merge to develop, and then a pull to your local with caused a rebase? 🤷‍♂️.

For context, I'm just following `HEAD`, not `develop`.

**Comment by Olical** [comment]
But then I would still need to force push because history would've diverged... and I don't do that 😢

**Comment by stefanvanburen** [comment]
yeah, good point. no idea then :/

**Comment by Olical** [comment]
Long shot, but did anyone happen to add their own changes or commits to their local Conjure version at any point? Even a small tinkering at one point that you maybe forgot about? Because that'd explain it... or some .lua file or something is being created under Conjure's source dir that isn't git ignored which is causing the pull to fail.

Next time someone sees this I'd love to see a `git status` from the offending copy.

**Comment by lockejan** [comment]
> Long shot, but did anyone happen to add their own changes or commits to their local Conjure version at any point? Even a small tinkering at one point that you maybe forgot about? Because that'd explain it... or some .lua file or something is being created under Conjure's source dir that isn't git ignored which is causing the pull to fail.
> 
> 
> 
> Next time someone sees this I'd love to see a `git status` from the offending copy.

In this case there would have been a different commit author in the history. 
But no, I didn't. I'm following master as well by the way.

**Comment by Olical** [comment]
> This way you will be informed in case it happens.

True, but again, I'd still have to force push and would notice the discrepancy. That's the thing I don't get, it doesn't matter how it's happening, I'd have to force push and I never do that.

Didn't spot the git status before, thanks for sharing. All of my work is done from the same machine, I do have some includes etc but all of my work work and OSS work is on the same machine at the moment, no other repos or team members have issues with this.

The _only_ difference is that I merge PRs into Conjure, I don't use GitHub PRs elsewhere right now, but then that'd still require me to pull --rebase THEN push --force, which I don't do unless I'm sleepwalking and doing it. I wonder if I can find some history in my reflog or in GitHub that'd point to a force push happening at some point.

**Comment by Olical** [comment]
It'll be interesting to see if it's EVERYONE that's experiencing this, or just some people some of the time. If it was me force pushing (last time I used it was over a month ago in another repo for good reasons) then EVERY single user's copy would break 🤔

**Comment by stefanvanburen** [comment]
packer!

**Comment by practicalli-john** [comment]
Suggest it's a packer issue

I had the same issue on 7th August
https://clojurians.slack.com/archives/CK143P6D7/p1659896715161759

I commented the conjure package, ran :Packerclean , removed the comment from the conjure package, ran :PackerInstall and conjure installed just fine.  I haven't had issues since

Others reported it happening with other packages with packer

**Comment by lockejan** [comment]
Now that's interesting. 
Your commit hash 2e7f449 (extracted from your slack post) is different from mine above. 
Mine dates back to the 7th of August as well and on that day a new release tag has been published.
Doesn't feel like a packer problem to me.

@Olical how does your git releasing workflow look like? 🤔

**Comment by Olical** [comment]
```
git checkout master
git merge develop
git push
git checkout develop
```

Nothing fancy 😬 I do the tagging though the GitHub releases UI.

**Comment by lockejan** [comment]
> ```
> git checkout master
> git merge --ff-only -
> git push
> git checkout develop
> ```
> 
> Nothing fancy 😬 I do the tagging though the GitHub releases UI.

Hmm, you could try to merge with additional flags:
`git merge --ff-only develop`

>With --ff-only, resolve the merge as a fast-forward when possible. When not possible, refuse to merge and exit with a non-zero status.

**Comment by TheodorRene** [comment]
``` 
- Finishing ... Done!
x conjure:
    fatal: refusing to merge unrelated histories
``` 
Same issue with Vim-Plug. Ended up with deleting `~/.local/share/nvim/plugged/conjure` and reinstalling. 👍

**Comment by Olical** [comment]
So I don't think I can do anything about this now other than be super careful in the future. And if it happens again without me knowingly force pushing I'll have to go full CSI and work out what is happening.

Maybe I should leave this open a little longer though just for the other people that will run into this as they upgrade. Speaking of which, has anyone _not_ run into this and updated just fine? That'd be interesting! I haven't run into it and I just `git pull` in locally linked directories for dev purposes across two Linux machines.

**Comment by Olical** [comment]
Going to close this and hope it was a one off mistake somehow. I still don't understand how, I hope I don't cause it again, please let me know if so and I'll change my workflow or something.
