### ISSUE TITLE
Selectively eval certain forms

### ISSUE THREAD

**Issue by kovasap** [Olical/conjure#405]
Is there a way to configure conjure to selectively eval only e.g. defn forms?  I'm interested in setting conjure up so that whenever i save the file all my changed functions are reloaded.  Curious if there is already a good workflow in place for this.

**Comment by Invertisment** [comment]
I'm very suspicious what kind of overengineering you got here because normally you don't care and evaluate whole namespace.

Do you have more than 10k lines of code in one file? How big is your file that you need to do this? 

IMO this is a non-issue. Just run "eval buffer" on save if you want to eval on save.

**Comment by kovasap** [comment]
Fair point.  My situation is that I have tests interspersed with my
functions, and I don't want to run them every time if e.g. I'm printing
stuff from a function when debugging.  But this is really just a minor
annoyance.

**Comment by Invertisment** [comment]
Ok. Then regarding the initial request.

I can't find the issue where Olical mentioned that he doesn't want to auto-evaluate things. I think I was asking to evaluate the namespace before running a test and even running auto-save before running a test.

And his answer was that he doesn't want to auto-evaluate that many things.
I can't find the source and probably we'll need to wait until he replies.

**Comment by Invertisment** [comment]
I happened to have open the file which has the function definitions.
The function that you want to use for evaluating your file is `EvalBuffer` or `EvalFile`: https://github.com/Olical/conjure/blob/master/fnl/conjure/mapping.fnl#L81
It depends on how you set it up but it should probably be `EvalBuffer` if you're saving the current buffer.

**Comment by Olical** [comment]
Yeah there's no way to filter forms down like this and I don't intend to add one, but running EvalBuf on every save may do what you want? You can also look into tools.namespace reload, there's docs for how to set that up somewhere, maybe in the wiki or under :help. Like @Invertisment says, I do not want to add things that run your code passively without you explicitly asking for it, that kind of thing will have to be from 3rd party plugins / configuration.

**Comment by Olical** [comment]
Going to close this one since I don't plan on implementing it. However, I recommend checking out my response to this feature request: https://github.com/Olical/conjure/issues/418

I reckon this could be implemented with a custom mapping or plugin.
