### ISSUE TITLE
Error in conjure/mapping.lua

### ISSUE THREAD

**Issue by nashbridges** [Olical/conjure#417]
I'm on neovim v.0.6.1 (readme [suggests 0.5+](https://github.com/Olical/conjure#installation), was it changed?).

While starting neovim with conjure installed I get the exception:

```
Error detected while processing /Users/nash/.local/share/nvim/plugged/conjure/plugin/conjure.vim:
line    2:
E5108: Error executing lua ...local/share/nvim/plugged/conjure/lua/conjure/mapping.lua:203: attempt to call field 'create_user_command' (
a nil value)
stack traceback:
        ...local/share/nvim/plugged/conjure/lua/conjure/mapping.lua:203: in main chunk
        [C]: in function 'require'
        ...re/nvim/plugged/conjure/lua/conjure/aniseed/autoload.lua:19: in function 'ensure'
        ...re/nvim/plugged/conjure/lua/conjure/aniseed/autoload.lua:28: in function '__index'
        ...h/.local/share/nvim/plugged/conjure/lua/conjure/main.lua:18: in function 'main'
        [string ":lua"]:1: in main chunk
```

I was able to pinpoint the problem to [the specific commit](https://github.com/Olical/conjure/commit/bfe6e6fac5d249c6e3b6411c82f28cfaca40f54c). So if you use vim-plugged, then

```viml
" this works fine (parent commit)
Plug 'Olical/conjure', {'commit': '06ecf117a'}

" this results in exception
Plug 'Olical/conjure', {'commit': 'bfe6e6fac'}
```

**Comment by Olical** [comment]
That's going up to 0.7, you'll have to stay on the older Conjure version or update Neovim I'm afraid. I'm fixing a bunch of issues and it requires newer versions of Neovim where functions like `create_user_command` exist. Before that point I had to rely on horrible hacks that caused other bugs and I can't solve them without removing the hacks.

I'll never rely on unreleased features and I try to slowly roll into the newer features as they release, not using them from day one, but it's unavoidable, I need to keep using newer things as they improve Lua support. Sorry if this is problematic for you 😞  I know some distros are waaaaaay behind, especially Debian based ones.

If it helps, I found the only comfortable way to use Neovim on distros with slow package management was to use linuxbrew for it. I hear there's also some neovim version manager programs out there that can solve the problem.

**Comment by Olical** [comment]
I need to update the readme or docs that mention 0.5, that's way too old now, that's when the VERY first lua support came in but it was lacking so much. I've worked around that for a while, but I need to move on now, there's too many bugs caused by the workarounds.

**Comment by nashbridges** [comment]
Ah! No worries, I'll update neovim. I use homebrew, but prefer not to update software just for the sake of new features. I did not realize neovim is moving so fast and breaks things.

Thanks for the super-quick response! Feel free to close the issue.

**Comment by Olical** [comment]
Yeah nvim has been adding a few breaking changes but also adding very essential Lua support functions recently. 0.7 introduced some key concepts for mapping keys and commands to Lua functions which means I no longer have to hack together Vim Script on the fly and map to that which in turn calls Lua functions. It was gross but the only way.

I think 0.7 is a very worthwhile upgrade and you'll find many plugins will require it. I think 0.7.1/0.8 etc are far smaller increments, 0.7 was just a big one for Lua support so you'll see a lot of people require it if they're all in on Lua.

I try to limit when I force upgrades, but when I do it's for stuff that fixes things, I promise not for the sake of it. I'm overhauling how every mapping works right now to use the new APIs and remove all the hacks. By forcing upgrades I can remove a bunch of backwards compatibility code I've been keeping around too.

You can keep up with Neovim breaking changes here https://github.com/neovim/neovim/issues/14090#issuecomment-1240357210

I try to handle them before they cause bugs in the wild. I always develop against the latest stable released Neovim, for reference. Never beyond that though.

**Comment by nashbridges** [comment]
Unfortunately, neovim 0.7.x (I suspect an update in libvterm) introduced an annoying bug with Ukrainian layout and 0.8.x broke compatibility with nerdtree (which is no longer maintained).

In the meantime I decided to roll back to 0.6.1. Here's the steps for macOS/homebrew users:

1. install neovim 0.6.1 (taken from the [article](https://cmichel.io/how-to-install-an-old-package-version-with-brew/)):

```
brew new-tap nashbridges/neovim
brew extract --version=0.6.1 neovim nashbridges/neovim
brew install neovim@0.6.1
```

If you have [the compilation bug](https://github.com/neovim/neovim/issues/16217), make sure to `brew uninstall --force libvterm`.

2. lock conjure to the commit that supports neovim 0.6.1:

```
Plug 'Olical/conjure', {'commit': '06ecf117a'}
```

**Comment by Olical** [comment]
Oh no! That's awful! Breaking changes aren't fun, maybe I should keep more old code around and try to support two paths, although that would've been VERY hard with the mapping code since it's fundamentally very different now. I'm not sure if it would've even been possible.

Thank you for documenting this for others though, it's greatly appreciated. I hope the Neovim bug gets fixed soon and you can roll forward again!

I hope you and your family are safe and healthy and reach the end of this fucking awful war as soon as possible ❤️

**Comment by nashbridges** [comment]
> maybe I should keep more old code around and try to support two paths, although that would've been VERY hard with the mapping code since it's fundamentally very different now

I don't think it's a good idea for every neovim library to maintain its own backwards compatibility layer. This really should be done upstream.

I will eventually get to my own issues with new versions of neovim (it just requires time to investigate and report them properly). The comments above, as you correctly mentioned, might be useful for other folks who have similar troubles. Please don't treat them personally, and keep your awesome project up!

> I hope you and your family are safe and healthy and reach the end of this fucking awful war as soon as possible ❤️

Thank you! ❤️
