### ISSUE TITLE
Neovim 0.8.0: Error messages and warnings in log buffer

### ISSUE THREAD

**Issue by Tdback** [Olical/conjure#427]
Honestly I am not sure if this is more the Neovim side or Conjure, but since updating to Neovim 0.8.0 my log buffer is beginning to display warning messages and errors. Unsure if this is because of some obscure LSP setting or if there is a way to disable this in the log. Super frustrating to use. 
![D5153672-964B-4228-B20A-C67C695AF7DA](https://user-images.githubusercontent.com/98326106/193709006-4e448859-ed37-4f8f-bb32-3ca77637fd68.png)

Update: I disabled diagnostics globally and that seemed to fix the issue.

**Comment by walterl** [comment]
This works for disabling diagnostics in Conjure log files only (Neovim 0.7.2):

```vim
autocmd BufNewFile conjure-log-* lua vim.diagnostic.disable(0)
```

**Comment by Olical** [comment]
Added this to the FAQ https://github.com/Olical/conjure/wiki/Frequently-asked-questions#my-log-buffer-is-full-of-diagnostic-warnings-and-errors--a-plugin-is-running-in-the-log-buffer-and-i-dont-want-it-to

Because I think it will be frequently asked for a while.

**Comment by randomizedthinking** [comment]
It would be good if conjure can incorporate it. The solution from @walterl works for all log buffers as long as the error messages are coming from nvim-lspconfig. Since all conjure log buffers are of buftype `nofile`, it would be easy to single all such buffers out.

@Olical, please let me know if you'd like to have a PR.

**Comment by Olical** [comment]
I think it would be an overreach for Conjure to turn off LSP diagnostics for _all_ buffers that happen to be `nofile`, that will almost certainly mess with some users workflows in unintended and surprising ways I think. I'd rather leave this as a a thing users can work around with advice in the FAQ if they really need to.

**Comment by randomizedthinking** [comment]
I didn't say it clearly. As a user, I use the `nofile` as an indicator to disable lsp, but conjure can disable lsp when log buffers are created.

**Comment by russtoku** [comment]
I have a rough Fennel translation of the above autocmd in my config based on [Magic Kit](https://github.com/Olical/magic-kit).
