### ISSUE TITLE
Possible issue lspconfig on nightly Neovim

### ISSUE THREAD

**Issue by samuelludwig** [Olical/conjure#429]
I recently updated my neovim and plugins and when I went to open a `.clj` file I encounter this rather cryptic echo

```
Error executing vim.schedule lua callback: vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'f'
        ...nvim/site/pack/packer/start/aniseed/lua/aniseed/core.lua:169: in function 'f'
        ...nvim/site/pack/packer/start/aniseed/lua/aniseed/core.lua:142: in function 'run_21'
        ...nvim/site/pack/packer/start/aniseed/lua/aniseed/core.lua:179: in function '_on_attach'
        ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:288: in function '_setup_buffer'
        ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:191: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

This appears to only happen on the nightly branch atm, when I switch back to neovim 0.8, I do not get this error. I haven't done a minimal test yet with a plain lua config. I didn't notice anyone else mention this error on the `lspconfig` issues so I'm unsure if its actually due to aniseed or just some recent braking change.

I will stick with 0.8 for the time being :^)

And thank you for the work that you've done on this plugin, its been a life-changer :open_hands:

**Comment by Olical** [comment]
Transferred to Conjure since it _should_ be Conjure's code that needs changing (if there's actually anything I can do and it's not some other plugin causing this).

**Comment by Olical** [comment]
If anyone else has seen this or has any information / context, please let me know!

**Comment by sandersantema** [comment]
This is just guesswork since I can't remember exactly anymore but I believe this was just a bug in nightly. I remember reverting to an earlier commit when I encountered (again I believe) this bug. Waited a bit with updating again and since then I haven't seen it while running nightly.

**Comment by Olical** [comment]
Closing for now since I think it's Neovim nightly thing, if others run into it maybe I need to do some work to handle some more breaking changes in Neovim. Feel free to reopen if you think this is still an issue with Conjure!
