### ISSUE TITLE
Conjure fennel window messes up vim-which-key

### ISSUE THREAD

**Issue by johannboehme** [Olical/conjure#430]
Hi, i am unsure if this bug is on the Conjure or which-key side, but whenever which-key tries to open in a conjure fennel window, it crashes:
![image](https://user-images.githubusercontent.com/58803954/195451349-7e89c5c6-f543-4a23-bf4c-db56dadc29bb.png)
It only does so in this kind of buffers, not in lua or vimscript files (or other langs).
I know the error messages are from which-key, but i thought since it only happens here you may have an idea on how to circumvent that.

BR,
Johann

**Comment by Olical** [comment]
I think it's an incompatibility between Neovim's newer Lua based mapping system and vim-which-key. I recommend changing to https://github.com/folke/which-key.nvim which should work the same but will support newer Neovim features.

A few people have run into this and swapped. vim-which-key probably works fine in older Neovim versions and normal Vim but there's a few Neovim specific issues building up now that the maintainer doesn't have the time to address just yet.

Previous issue for this: https://github.com/Olical/conjure/issues/417, and there's been some other people in Discord and Clojurians Slack with the same question. I guess it'll just keep coming up unless I can sort of hack around this issue.

WhichKey complains about not having a `rhs` key on the mapping... but all of my mappings have a `rhs`, just like they used to. Now they point at Lua functions though so the `rhs` is an empty string. I guess Neovim internally removes that `rhs` key thinking nobody needs it which kills vim-which-key.

**Comment by Olical** [comment]
Closing since I think it's a thing the which key plugin will need to handle as more plugins use the newer Neovim APIs. Please correct me if I'm wrong.
