### ISSUE TITLE
client for psql (postgresql repl) 

### ISSUE THREAD

**Issue by AbhinavOmprakash** [Olical/conjure#432]
Hi, I was wondering if it would be possible to add [psql](https://www.postgresql.org/docs/current/app-psql.html) client support for conjure. 

I use psql extensively and conjure as well, and I would like to work on this if you give me some pointers. 

I know that tree-sitter can be used to parse the syntax, and I can look at the python implementation for pointers. 

I'm not certain how to connect conjure with the psql client and pass data between them. (whether it will be remote or via stdio) 

Also, in order to start the psql client, a database URL must be given to it. This can be added to the user's init file, I'm not sure how to pick it up from conjure. (I bring this up because this will directly impact the UX)

**Comment by Invertisment** [comment]
Clojure plugin loads the nREPL port from a file in the working directory.
That means that the plugin loads only after you enter a file.
And that also means that you can have a config file in your project that you could use to read this DB URL from.

Conjure can also switch between REPL connections (I think) so you may want to look into the initialization code of Clojure.

**Comment by AbhinavOmprakash** [comment]
That is an idea. In the case of clojure you have deps.edn/project.clj files which contain the port information. In the case of db connections there is no such standard file that I'm aware of. 

a `.psqlrc` file does exist, but that's just config specific a psql application. Any ideas?

**Comment by Invertisment** [comment]
Read it from and environment variable or hardcode into your `.vimrc`. Just do something simple, don't spend time on it. And then later you'll decide what you want.

**Comment by AbhinavOmprakash** [comment]
okay, sure. 
also, how to connect conjure with the psql client and pass data between them?

**Comment by Olical** [comment]
That would have to be over stdio, there's already a shared module all other stdio clients use to spin up a sub-process and send/receive data. That module needs a rewrite / sequel that works a lot better, but the existing one is good enough for a bunch of simple cases.

**Comment by Olical** [comment]
This can probably be a copy/paste/modify job of an existing stdio client, of which there are quite a few!

**Comment by AbhinavOmprakash** [comment]
Alright. Thanks for the pointers. Let me try to implement something :)

**Comment by russtoku** [comment]
I've been trying to come up with a SQL client but had to modify `fnl/conjure/remote/stdio.fnl` to get things to work. The [next-in-queue](https://github.com/Olical/conjure/blob/31a1626273e2bab479b6b8416a137f9edaba7daa/fnl/conjure/remote/stdio.fnl#LL69C4-L75C41) function is what I had trouble with. Removing the test for `(not repl.current)` in [line 71](https://github.com/Olical/conjure/blob/31a1626273e2bab479b6b8416a137f9edaba7daa/fnl/conjure/remote/stdio.fnl#L71) allows the responses from psql to be displayed in the source and log buffers.

**Comment by russtoku** [comment]
BTW, you can use `psql -U user postgres` as the command to run a repl and it will get the user's password from `~/.pgpass`.  In this example, the database is the default one called `postgres`. It should be readable only by you and contain something like:
```
# <host>:<port>:<database>:<db_user>:<db_password>
localhost:5432:postgres:user:secret
```

See [The Password File](https://www.postgresql.org/docs/14/libpq-pgpass.html) in the PostgresQL docs for details and Windows set-up.

**Comment by russtoku** [comment]
See PR #511
