### ISSUE TITLE
Imrpove third party plugin experience

### ISSUE THREAD

**Issue by sigmaSd** [Olical/conjure#433]
Taking https://github.com/sigmaSd/conjure-deno as an example

I currently I have to ask the user to do:
1- 
```lua
use 'Olical/conjure'
use 'sigmaSd/conjure-deno'
```
2-
 ```lua
local conjure_filetypes = { "clojure", "fennel", "janet", "hy", "julia", "racket", "scheme", "lua", "lisp",
    "rust" }
for _, v in pairs({ "typescript", "javascript" }) do
    conjure_filetypes[#conjure_filetypes + 1] = v
end

vim.g["conjure#filetypes"] = conjure_filetypes

vim.g["conjure#filetype#typescript"]      = "deno.deno"
vim.g["conjure#filetype#javascript"]      = "deno.deno"
```

The second step is just a workaround and it doesn't handle all the cases (for example if the user have other third party plugins)

In ideal scenario I would only need to tell the user to use step 1 with maybe only these  2 lines or something alike 
```lua
vim.g["conjure#filetype#typescript"]      = "deno.deno"
vim.g["conjure#filetype#javascript"]      = "deno.deno"
```

**Comment by Olical** [comment]
Agreed! I think this part of the API / options is pretty awkward right now. Will have a crack at improving this soon. I would like a single table of options too, will see what fits best and hopefully make it backwards

**Comment by glyh** [comment]
I guess this in general could have higher priority? I'm thinking spliting conjure itself into different parts and stop accepting new plugins, this will keep the project lean and we know everything is maintained.

**Comment by russtoku** [comment]
@sigmaSd, I was able to set things up so that *conjure-deno* is automatically wired into Conjure. I've forked your repo and created https://github.com/russtoku/conjure-deno/tree/issue-433 so you can try it out. If it suits you, I can make a pull request and you can take it from there.

The key thing is to use an script (Vimscript or Lua) in the `after/plugin` directory. I also took the liberty of rearranging things so that *conjure-deno* plugin follows the naming convention of existing clients.

Hope this helps!

**Comment by sigmaSd** [comment]
thanks that looks awesome, feel free to open a pr on my repo, your changes errors on my testing though
```
vim/_editor.lua:0: /home/mrcool/.local/share/lunarvim/lvim/init.lua..nvim_exec2() called at /home/mrcool/.local/share/lunarvim/lvim/init.lua:0../home/mrcool/.local/share/lunarvim/site/pack/lazy/opt/conjure-deno/plugin/init.lua: Vim(source):E5113: Error while calling lua chunk: .../lazy/opt/conjure-deno/lua/conjure/client/deno/stdio.lua:13: module 'aniseed.autoload' not found:
```

There seems to be a lot of unrelated changes to  lua/deno/aniseed/deps/fennel.lua thats causing this

**Comment by russtoku** [comment]
I created PR [#1](https://github.com/sigmaSd/conjure-deno/pull/1) for your *conjure-deno* plugin.

I noticed that the version of Aniseed that you used created this on L.13 of `lua/deno/deno.lua`:
```
local autoload = (require("deno.aniseed.autoload")).autoload
```
versus a recent version of Aniseed which created this on L.13 of `lua/conjure/client/deno/stdio.lua`:
```
local autoload = (require("aniseed.autoload")).autoload
```

I'm using *vim.plug* as my plugin manager for Neovim so I don't see the errors that you do. I'm guessing that it might be the plugin manager you are using. When I change *aniseed.autoload* to *deno.aniseed.autoload* I still don't see any errors. I'm still very shaky about loading bits.

The changes are few so you could do it by hand and see if there still the errors that you see.

**Comment by sigmaSd** [comment]
with @russtoku pr https://github.com/sigmaSd/conjure-deno/pull/1 personally I find this issue resolved, turns out the missing peace was putting the extra work in after/plugins, now the user only needs
```lua
use 'Olical/conjure'
use 'thirpartyrepl'
```
