### ISSUE TITLE
`bb nrepl-server` auto-repl silently fails when another `bb nrepl-server` has already been started on the same port

### ISSUE THREAD

**Issue by kovasap** [Olical/conjure#434]
This for instance happens when having two instances of vim open.  I would expect Conjure to retry the command with a new random or incremented port.  Currently the behavior I see is that Conjure simply cannot eval code when this happens.

**Comment by Olical** [comment]
Pushed a fix! The port is now random and assigned into the babashka `cmd` with a `$port` substitution. So it can be moved around the configured cmd and even removed. If you remove it Conjure won't pick a random port and will instead assume the cmd you're executing will write a port file that Conjure will look for.

Let me know how this works for you!

**Comment by kovasap** [comment]
Thanks!!  Which change fixes this?  I tried updating but still see the issue.

**Comment by Olical** [comment]
It's only on the `develop` branch for now, sorry, should've said.

**Comment by kovasap** [comment]
Thanks this works for me on the main release now!
