### ISSUE TITLE
EvalComment* commands fail in Racket

### ISSUE THREAD

**Issue by thesergiomiguel** [Olical/conjure#438]
Hi.

`:ConjureEvalComment*` commands have always been flaky at best for me with Racket. Previously I tried playing with Clojure and that worked great, all of the time. I've looked for other people with similar issues but can't find any, so I'm assuming it's something with my setup. What info would help you debug?

https://user-images.githubusercontent.com/22590655/203498307-fe305a43-1e53-46e6-8b74-a776239a1146.mov

Moreover, I'd like to take the opportunity to say thank you, and woah!, for Conjure. It still boggles my mind that such a cool thing exists, and is built by one person. Well done!

**Comment by Olical** [comment]
Oh interesting, thanks for reporting! I thought this was to do with the current stdio / cli REPL support (which I'm going to start rewriting today) but that actually looks different. I'll have a look, thank you!

**Comment by Olical** [comment]
Should be fixed on the `develop` branch! Thanks for bringing it to my attention.

**Comment by thesergiomiguel** [comment]
Thanks a lot, I can't believe how quickly you fixed this. It's a great thing you've built here.
