### ISSUE TITLE
"Attempt to concatenate a nil value" in `eval.lua`

### ISSUE THREAD

**Issue by gwerbin** [Olical/conjure#442]
I unfortunately just started having this error on Conjure commit 0be93ef60 with both Neovim v0.8.0 and v0.9.0-dev-308+g736c36.

Error:

```none
E5108: Error executing lua: Vim:Error executing Lua callback: ...e/nvim/site/pack/packer/opt/conjure/lua/conjure/eval.lua:41: attempt to concatenate a nil value
stack traceback:
        ...e/nvim/site/pack/packer/opt/conjure/lua/conjure/eval.lua:41: in function 'preview'
        ...e/nvim/site/pack/packer/opt/conjure/lua/conjure/eval.lua:112: in function <...e/nvim/site/pack/packer/opt/conjure/lua/conjure/eval.lua:109>
        ...e/nvim/site/pack/packer/opt/conjure/lua/conjure/eval.lua:167: in function <...e/nvim/site/pack/packer/opt/conjure/lua/conjure/eval.lua:156>
        [C]: at 0x01028fe484
stack traceback:
        [C]: at 0x01028fe484
```

Here is my Conjure setup:

```lua
local M = {}

local vim_utils = require('local.vim')

--[[ http://community.schemewiki.org/?scheme-faq-standards#implementations ]]
M.scheme_settings = {
  chez = {
    command = 'chez',
    prompt_pattern = '> ',
    value_prefix_pattern = false,
  },
  chicken = {
    command = 'csi -:c',
    prompt_pattern = '\n#;%d+> ',
    value_prefix_pattern = false,
  },
  mit = {
    command = 'mit-scheme',
    prompt_pattern = '[%]e][=r]r?o?r?> ',
    value_prefix_pattern = '^;Value: ',
  },
  gauche = {
    command = 'gosh -i',
    prompt_pattern = 'gosh[>$] ',
    value_prefix_pattern = false,
  },
}

M.set_scheme_impl = function(impl_name, options)
  local settings = M.scheme_settings[impl_name]
  if settings == nil then
    vim_utils.viml_exec([[echoerr 'Unknown scheme implementation: %s']], impl_name)
    return
  end

  if options.set_client_state and options.set_client_state ~= 0 then
    vim_utils.viml_exec([[ConjureClientState scheme_%s]], impl_name)
  end

  vim.g['conjure#client#scheme#stdio#command'] = settings.command
  vim.g['conjure#client#scheme#stdio#prompt_pattern'] = settings.prompt_pattern
  vim.g['conjure#client#scheme#stdio#value_prefix_pattern'] = settings.value_prefix_pattern
  M.current_scheme_impl = impl_name

  vim_utils.echomsg('Switched to Scheme implementation: ' .. impl_name)
end

M.current_scheme_impl = nil

M.setup = function()
  vim.fn.nvim_create_user_command(
    'ConjureSchemeImpl',
    function(cmd)
      if cmd.fargs[1] ~= "" and cmd.fargs[1] ~= nil then
        M.set_scheme_impl(cmd.fargs[1], { set_client_state = not cmd.bang })
      else
        print(M.current_scheme_impl)
      end
    end,
    { bang = true, nargs = '?' }
  )
end

return M
```

The file that triggered the error was using the Gauche interpreter:

```
#!/usr/bin/env gosh -b

(print 1234)
```

I can trigger the error reliably with the `<localleader>er` or `<localleader>ee` mapping, regardless of what log windows I have open.

I'm not sure if this is related to https://github.com/Olical/conjure/issues/320, or if it's different.

**Comment by chip** [comment]
Having same issue, `HEAD` is `v4.41.0` (nvim `v0.9.0-dev-3131+gf92aab5f7-dirty`).

Notes:
* I'm using `racket`
* From lua, `client.get("comment-prefix")` is `nil` (after debugging `eval.lua` file in stacktrace)
* Hardcoding to `"; "` then shows further errors
* `:set ft` returns `scheme` (not sure if this is correct)
* `:ConjureConnect` shows errors, but can connect when I `:set ft=racket`, but error persists

If I find anything else, I'll report back. Grateful for any further suggestions from anyone. Thanks in advance. :smile:

**Comment by chip** [comment]
Not sure what happened, but this will now work for me if I can get it to recognize `.rkt` files and `set filetype=racket` instead of `scheme`.

**Comment by chip** [comment]
Apologies for the noise, but this has been resolved for me after reinstalling `vim-racket`.

**Comment by Olical** [comment]
Not sure on the root cause still (sorry!) but I've replaced the unsafe string concats in the `conjure.eval` module with the save `aniseed.string/join` function calls on the *develop* branch. So now you might end up with `something ()` where you expected `something (else)` but it will no longer crash.

The Lua `..` string concat throws if it encounters a `nil`, so we can either eliminate all possibilities of `nil` (thought I had done here, hence `..` usage) or make a best effort and use safe functions that check and handle `nil`. I'll opt for the latter wherever possible, hopefully this never happens again for you.

If you now see an eval preview (that's the thing that tells you what you did and with which code before the result is displayed in the log) with some parts that look missing, please share them with me so I'll be able to work out what part of the string was `nil`.
