### ISSUE TITLE
[FR] configing fallbacks for conjure auto connect?

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#453]
Right now conjure is doing a great job by auto connecting. But I want it to start REPLs when it fails to do so. I know there's vim-jack-in, but how should I make it only start a REPL only when it fails to auto connect? 

Is there a hook function or something?

**Comment by Olical** [comment]
I think the new `conjure.hook` module I've just added today could help with this, I'll probably add a hook for you to interject your own logic and inspect Conjure's result then act upon it in a way you see fit. Will integrate the Clojure client connect code with hooks and document it, should be all you need 🎉

**Comment by Olical** [comment]
See the commit above for more info, there's now a hook where you can intercept, replace or augment the current passive connection behaviour. More can be added when required. Should allow you to do basically anything you want although it will require a little thought and reading, not just a simple option to toggle I'm afraid.

I think you can also override the `nrepl.connect` arguments now, at least I hope I made it possible for you. So you can basically set your own `on-*` handler functions that are passed to the actual connection. Meaning you can define your own failure cases. Or you can detect when no portfile was found (it returns `nil`) and then start your own REPL.

**Comment by Olical** [comment]
This is only on the develop branch for now. There's general docs on hooks in the main `conjure.txt` file and specific ones about this Clojure connect hook in the clojure doc txt.
