### ISSUE TITLE
Clojure: Defword on symbol finds no definition (treesitter)

### ISSUE THREAD

**Issue by Akeboshiwind** [Olical/conjure#457]
Say I'm looking at some code like this:

```clojure
(ns my-ns
  (:require [clojure.string :as str]))

(str/join " " ["a" "b"])
; 1 2  3 (cursor positions)
```

I'm trying to navigate to the definition of the `str/join` function.
Typically if I put my cursor at position 3 (withing the symbol `join`) and use `:ConjureDefWord` (or the keybinding) this would happen.

But now for some reason I get the following:
```clojure
; def (word): join
; Multiple candidates found
java.lang.Thread/join
java.lang.String/join
```

Luckily there's a work around: I can put my cursor at position 1 and then just search for `join`, but this isn't ideal.

---
### Minimal Reproduction

<details>
<summary>minimal.lua</summary>

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
            "Olical/conjure",
            {
                "nvim-treesitter/nvim-treesitter",
                run = ":TSUpdate",
            },
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. "/plugin/packer_compiled.lua",
            display = { non_interactive = true },
        },
    })
end

_G.load_config = function()
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    require("nvim-treesitter.configs").setup({
        ensure_installed = { "clojure" },
        highlight = {
            enable = true,
        },
    })
end
if vim.fn.isdirectory(install_path) == 0 then
    print("Installing dependencies.")
    vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

</details>

1. Create a file `my_ns.clj` with the code above
2. Start a repl (with cider etc)
3. Start nvim with the above config `nvim -nu minimal.lua`
4. `:e my_ns.clj`
5. Put cursor over the `join` symbol
6. `:ConjureDefWord`

---

I've narrowed things down a little, by using [extract.word](https://github.com/Olical/conjure/blob/2355c67b1924560897a21acf454b655680f391c1/fnl/conjure/extract.fnl#L35):
```lua
:lua print(vim.inspect(require("conjure.extract").word()))
```
At position 3 this outputs:
```lua
{
  content = "join",
  range = {
    ["end"] = { 11, 8 },
    start = { 11, 5 }
  }
}
```

Whereas [extract.legacy-word](https://github.com/Olical/conjure/blob/2355c67b1924560897a21acf454b655680f391c1/fnl/conjure/extract.fnl#L22) outputs what I'd consider the "correct" extraction.
```lua
{
  content = "str/join",
  range = {
    ["end"] = { 11, 8 },
    start = { 11, 1 }
  }
}
```

**Comment by Akeboshiwind** [comment]
I seem to remember this working a couple of days ago which makes me think that this is an issue with a tree-sitter update or something.

**Comment by Akeboshiwind** [comment]
Cool, so I managed to narrow it down to this commit which updates the Clojure parser in Treesitter:
https://github.com/nvim-treesitter/nvim-treesitter/commit/5b8a152c6c9de4004725c20b891658e698430c70

**Comment by Akeboshiwind** [comment]
I've not looked to deeply but I think the output of the clojure treesitter changed?
Changes in the above commit: https://github.com/sogaiu/tree-sitter-clojure/compare/8c23e..50468

If I had to guess it'd be this PR: https://github.com/sogaiu/tree-sitter-clojure/pull/31

Under the hood the `:TSPlayground` output has gone from:
<details>

<summary>from:</summary>

```
list_lit [0, 0] - [1, 38]
  value: sym_lit [0, 1] - [0, 3]
  value: sym_lit [0, 4] - [0, 11]
  value: list_lit [1, 2] - [1, 37]
    value: kwd_lit [1, 3] - [1, 11]
    value: vec_lit [1, 12] - [1, 36]
      value: sym_lit [1, 13] - [1, 27]
      value: kwd_lit [1, 28] - [1, 31]
      value: sym_lit [1, 32] - [1, 35]
list_lit [3, 0] - [3, 24]
  value: sym_lit [3, 1] - [3, 9]
  value: str_lit [3, 10] - [3, 13]
  value: vec_lit [3, 14] - [3, 23]
    value: str_lit [3, 15] - [3, 18]
    value: str_lit [3, 19] - [3, 22]
```

</details>

<details>

<summary>to:</summary>

```
list_lit [0, 0] - [1, 38]
  value: sym_lit [0, 1] - [0, 3]
    name: sym_name [0, 1] - [0, 3]
  value: sym_lit [0, 4] - [0, 11]
    name: sym_name [0, 4] - [0, 11]
  value: list_lit [1, 2] - [1, 37]
    value: kwd_lit [1, 3] - [1, 11]
      name: kwd_name [1, 4] - [1, 11]
    value: vec_lit [1, 12] - [1, 36]
      value: sym_lit [1, 13] - [1, 27]
        name: sym_name [1, 13] - [1, 27]
      value: kwd_lit [1, 28] - [1, 31]
        name: kwd_name [1, 29] - [1, 31]
      value: sym_lit [1, 32] - [1, 35]
        name: sym_name [1, 32] - [1, 35]
list_lit [3, 0] - [3, 24]
  value: sym_lit [3, 1] - [3, 9]
    namespace: sym_ns [3, 1] - [3, 4]
    name: sym_name [3, 5] - [3, 9]
  value: str_lit [3, 10] - [3, 13]
  value: vec_lit [3, 14] - [3, 23]
    value: str_lit [3, 15] - [3, 18]
    value: str_lit [3, 19] - [3, 22]
```

</details>

**Comment by Akeboshiwind** [comment]
One (probably less than ideal) solution might be:
```lua
local ts = require("conjure.tree-sitter")

local node = ts["get-leaf"]()
local node_type = node:type()
if node_type == "sym_name" or node_type == "sym_ns" then
  node = node:parent()
end

print(ts["node->str"](node))
```

Problems with this are:
- It's a specific work around for the clojure parser
- It doesn't find the symbol if you have your cursor over the `/` (position 2 in OP)

**Comment by Olical** [comment]
Oh I think I fixed this in #460! And yeah, I think the syntax updated so the tree had more nuance to it. I changed the TS word extraction to consider it's parent, if it's a `multi_symbol` we use that instead of the lower `symbol` we started with. That _should_ fix all occurrences of this although we may have to recursively walk up.

I wonder if `foo.bar/x.y` becomes `[[foo, bar], [x, y]]`, so two levels of `multi_symbol` with four `symbol` at the bottom of the tree. If so, we just need to recur in some way and handle infinite layers of multi syms.

**Comment by Olical** [comment]
Yep, it does double nest, fixing with recursion, the duct tape of the CPU.

**Comment by Olical** [comment]
Fixed, I think? (on develop)

**Comment by Akeboshiwind** [comment]
Just tried out `develop` and this fixed it for me.
I'll be keeping an eye out on releases 👀

**Comment by sogaiu** [comment]
@Olical and @Akeboshiwind 

Sorry about the change / breakage.

We had created [this issue](https://github.com/sogaiu/tree-sitter-clojure/issues/33) to try to give advance warning of planned changes, but I didn't realize clearly that Conjure was using tree-sitter-clojure, and thus failed to reach out earlier (before releasing the change).

Please consider subscribing if interested.

(There is [another change](https://github.com/sogaiu/tree-sitter-clojure/commit/7df2726280aef74ed963d980c1fa9c9f554eac97) we're planning to release [to better handle ClojureDart code](https://github.com/sogaiu/tree-sitter-clojure/issues/46), but perhaps it won't affect folks adversely.)

**Comment by Olical** [comment]
No problem! Thank you for improving the TS support and the added context.
