### ISSUE TITLE
Documentation: make it more obvious that conjure ships with aniseed

### ISSUE THREAD

**Issue by gagbo** [Olical/conjure#462]
Hello,

I got confused for a bit because the help entry on `g:conjure#filetype#fennel` doesn't say that conjure vendors a version of `aniseed`:

> Client to use for `fennel` buffers. Conjure also ships with an
> alternative `"conjure.client.fennel.stdio"` client which allows
> you to work with Fennel (without Aniseed) outside of Neovim in an
> external Lua process.
> Help: |conjure-client-fennel-aniseed|, |conjure-client-fennel-stdio|
> Default: `"conjure.client.fennel.aniseed"`

So since I don't use `aniseed`, I thought I had to switch to `conjure.client.fennel.stdio`; but at that point, I lose most of the cool features that conjure can give me in my Fennel configuration.

I sorted this out thanks to the helptext on `conjure-client-fennel-aniseed`, that mentions the vendored `aniseed`, but I think it'd be helpful if the text on the first variable also mentionned it, like:

> Client to use for `fennel` buffers. Conjure defaults to using
> a vendored aniseed client which give extra help when using
> Fennel in the context of Neovim Lua API. Conjure also ships with
> an alternative `"conjure.client.fennel.stdio"` client which allows
> you to work with Fennel (without Aniseed) outside of Neovim in an
> external Lua process.
> Help: |conjure-client-fennel-aniseed|, |conjure-client-fennel-stdio|
> Default: `"conjure.client.fennel.aniseed"`

"vendored" or "included" or "built-in", I never know which word is the best one.

Thanks for your work on conjure/aniseed/magic-kit, and have a nice day :)

Gerry

**Comment by Olical** [comment]
Changed on develop, thanks! I think vendored is good and the location you mentioned makes sense. Added a sentence explaining that the default client has everything built in for you.
