### ISSUE TITLE
Comment!

### ISSUE THREAD

**Issue by falberto** [Olical/conjure#465]
Is it possible to make comments (_ignore next form_) the same color as comments with the (`;`)?

![image](https://user-images.githubusercontent.com/1578072/220618362-a6477e34-c307-4fdc-ab28-651e430569e6.png)

**Comment by Olical** [comment]
This is an issue with the built in Neovim Clojure syntax highlighting and
not to do with Conjure I'm afraid. Although if you use tree sitter this
does work as you expect, that'll require some googling and configuring to
set up, but it's worth it imo.

**Comment by practicalli-john** [comment]
I can confirm that when using Treesitter the `#_` reader comment does highlight the next form in the same way as a line comment.

https://practical.li/neovim/install/configuration/ is a fennel configuration I uses which includes Treesitter and gives the desired results.

Essentially the https://github.com/nvim-treesitter/nvim-treesitter package should be installed along with the clojure parser (ideally configured to update when the nvim-treesitter package updates)

https://github.com/nvim-treesitter/nvim-treesitter has a lot of info
