### ISSUE TITLE
can somebody help figuring out setting up conjure for guile scheme via lua?

### ISSUE THREAD

**Issue by fislysandi** [Olical/conjure#473]
hi i want to have real time evaluation for guile scheme so that it will make my life so much easier and make me work faster on my project.

i use init.lua but i see that you use vimscript, do you have a lua version of the command?

also i really dont get what you are saying about 'socket' i just dont get it. what am i suppost to do to setup up this 'socket' and documentation you give me like im suppose to know what to do with it?
https://github.com/Olical/conjure/wiki/Quick-start:-Guile-(socket)

ive seen on the example neovim video that the guy in the video did :Clj and it executed REPL. also what is REPL? where do i get it?

i just have so many questions,

**Comment by fuadsaud** [comment]
Hi @fislysandi!

I don't have experience with Guile specifically but I can help clarifying some of your questions.

--- 

> what is REPL? where do i get it?

REPL stands for [Read-Print-Eval-Loop](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop). It is a way to interact with a running program. According to the [Guile docs](https://www.gnu.org/software/guile/manual/html_node/The-REPL.html) you can run Guile without supplying a program to the interpreted to get a REPL at the command line.

---

> also i really dont get what you are saying about 'socket' i just dont get it.

A [socket](https://en.wikipedia.org/wiki/Unix_domain_socket) is a communication channel between two running programs on a Unix environment.

---

>what am i suppost to do to setup up this 'socket'

This is stated [in the page you linked](https://github.com/Olical/conjure/wiki/Quick-start:-Guile-(socket)):

> First, you need to start your Guile REPL and give it a path to a socket file, this path has to be absolute as far as I can tell. Here’s a script that starts a REPL and places the .socket file in your current repository then cleans up after it exits.

Did you try following these instructions? If you don't have a git repo or don't want to use the provided script you can simply run, for example, `guile --listen=$HOME/.guile-repl.socket` and supply that same path to the `:ConjureConnect` command in neovim.

---

>i use init.lua but i see that you use vimscript, do you have a lua version of the command?

You can read more about setting variables from lua by running `:help lua-vim-variables` on neovim.

ToIn this specific case you can use `vim.g["conjure#filetype#scheme"] = "conjure.client.guile.socket"`.

**Comment by Olical** [comment]
Thank you for stepping in and answering things here @fuadsaud! I hope that covers all of the questions, if not I'll try my best to help out too.
