### ISSUE TITLE
I moved Conjure additions to GitLab

### ISSUE THREAD

**Issue by Invertisment** [Olical/conjure#475]
Hey.
I moved https://github.com/invertisment/conjure-clj-additions-cider-nrepl-mw and https://github.com/invertisment/conjure-clj-additions-vanilla into gitlab so it would be good to update the `Mods` section of the README.

New links are these:
https://gitlab.com/invertisment/conjure-clj-additions-cider-nrepl-mw
https://gitlab.com/invertisment/conjure-clj-additions-vanilla

I also made an error so that it would crash upon loading. That error shows the repository link for each of the plugins. 
So there is no need to update the README immediately.

**Comment by Olical** [comment]
Done! Thanks for the heads up.
