### ISSUE TITLE
Small Build Issues on MacOs with fixes

### ISSUE THREAD

**Issue by thecontinium** [Olical/conjure#48]
1. stat is still being used in bin/compile; change as for other stat statement
2. error in building:
`Error building classpath. Could not transfer artifact leiningen:leiningen:jar:2.9.0 from/to clojars (https://repo.clojars.org/): Range Not Satisfiable (416)`

Fixed it by changing 2.0.9 to 2.9.1 in deps.edn

cheers

**Comment by Olical** [comment]
Oh well that's odd, thanks for reporting! I'll bump it in develop and get it into master soon.

**Comment by Olical** [comment]
Ah, it's already 2.9.1 in develop. I'll get this published soon!

**Comment by thecontinium** [comment]
Also replace the use of ‘stat’ in compile if you can please.

I’m looking forward to using this plugin.

Thank you for writing it.

Cheers

--
The Continium

On 12 July 2019 at 17:10:21, Oliver Caldwell (notifications@github.com<mailto:notifications@github.com>) wrote:

Ah, it's already 2.9.1 in develop. I'll get this published soon!

**Comment by Olical** [comment]
Ah, I thought I had! I missed one of them! So sorry, I'll get this out now actually.

**Comment by thecontinium** [comment]
Cool

--
The Continium

On 12 July 2019 at 17:49:39, Oliver Caldwell (notifications@github.com<mailto:notifications@github.com>) wrote:

Ah, I thought I had! I missed one of them! So sorry, I'll get this out now actually.

**Comment by Olical** [comment]
Tagged `v0.22.0`, hopefully that works well for you!

**Comment by Olical** [comment]
Going to close this now in the hopes that it's all fixed. Let me know if not!

**Comment by thecontinium** [comment]
Fixed
