### ISSUE TITLE
how to hide enter buffer

### ISSUE THREAD

**Issue by WingDust** [Olical/conjure#491]
![image](https://github.com/Olical/conjure/assets/45911286/7b4e11ef-b359-4263-8ede-775ee48878be)
how to hide this buffer in enter python file or other language file 
I already try
```fnl
(do
  (nvim.ex.augroup :ConjureRemoveSponsor)
  (nvim.ex.au_)
  (nvim.ex.autocmd :BufWinEnter "conjure-log-*" "silent s/; Sponsored by @.*//e")
  (nvim.ex.augroup :END))
```
no work

**Comment by Olical** [comment]
The expression `s/; Sponsored by @.*//e` will need to be updated to also support `s/# Sponsored by @.*//e` which is the Python comment syntax.

I think something like `s/[#;] Sponsored by @.*//e` might work, but I'm not sure exactly. The vim regular expression syntax might be different.

**Comment by WingDust** [comment]
![image](https://github.com/Olical/conjure/assets/45911286/fdfec3fa-9341-46b3-a2bf-02b15840cd58)
```fnl
(vim.api.nvim_create_augroup :ConjureRemoveSponsor {:clear true})
    (vim.api.nvim_create_autocmd :BufWinEnter
                                 {:pattern :conjure-log-*
                                  :command "silent s/# Sponsored by @.*//e"})
```
code is work
but I want to will not show this buffer when neovim first enter a python file

**Comment by Olical** [comment]
You can also evaluate this after the substitution, after the buffer has opened to close the HUD (that's what the window in the corner is called): `:lua require("conjure.log")["close-hud"]()`

If you do not ever want to see the HUD then you can configure this:

https://github.com/Olical/conjure/blob/1dd96d90f53122225f698e58b50dee9ed760cf2e/doc/conjure.txt#L557-L560

**Comment by russtoku** [comment]
My preference is not to have the HUD popping up so I set `g:conjure#log#hud#enabled` to to `v:false`.

At the command-line, you type:
```
let g:conjure#log#hud#enabled=v:false
```
