### ISSUE TITLE
Interrupt support for Scheme client

### ISSUE THREAD

**Issue by AbheetChaudhary** [Olical/conjure#497]
Scheme's  REPL does not have interrupt support like some others. For scheme `<localleader>ei` does not sends interrupt signal. It behaves as usual `ei` key press in vim, i.e, goto end then insert. So if we enter in an infinite loop or some situation like that, then there will be choice but to stop the repl completely with `<localleader>cS`. 

Also, the help docs on running `:help conjure` dont tell about the keybindings `<localleader>ei` and `<localleader>cS`. I got them from discord.

**Comment by AbheetChaudhary** [comment]
Out of curiosity I tried to use conjure from your fork `russtoku/conjure`. I used lazy and set `branch="dev2"` and `commit="4dd024c"`, Then i put scheme in an infinite loop but the binding `<localleader>ei` didn't sent any interrupt signal instead it was still at its old behaviour. Also there was no `ConjureInterruptScheme` command like there is for `ConjureInterruptPython`. Did I missed some step? Was it supposed to work at this stage?

Could it be because of this thing mentioned in the [Contributing to Conjure](https://github.com/Olical/conjure/blob/1dd96d90f53122225f698e58b50dee9ed760cf2e/CONTRIBUTING.adoc#contributing-to-conjure):
"Your changes and evaluations only apply to the in memory copy of Conjure, use `make compile` to persist the changes as files in the lua directory. I commit these alongside my Fennel changes so each commit lines up with the Fennel and corresponding Lua changes."

Because when I tried to fix it I took some 15-20 lines of code from the python client's implementation of interrupt and when i ran `make compile` I just gave up by looking at the amount of diffs it made. I may have done something wrong ... kinda new to OSS. Your commit [Fix for issue Olical#497 Scheme client ](https://github.com/russtoku/conjure/commit/4dd024cb0b0729e33b08998e4b782b79ab824498) did not had too many diffs, just two files and less about 20 lines. 

It could have been because of that or I am being too hasty.

**Comment by russtoku** [comment]
Sorry! That was my fault. I didn't commit the Lua files from running "make compile". I've done that and pushed a commit on my `dev2` branch.

I think it would be better if you just specify the `branch` for the lazy.nvim config. This is what I used for testing with a `~/.config/nvim/init.lua` file for Neovim:
```
require('lazy').setup({
  'navarasu/onedark.nvim',
  'nvim-lualine/lualine.nvim',
  'nvim-treesitter/nvim-treesitter',
  { 'russtoku/conjure', branch = "dev2" }}, {})
```

**Comment by AbheetChaudhary** [comment]
Great!
I just tried it and its working. Thanks for the fix. Hoping to see the PR getting merged.

**Comment by Olical** [comment]
This is implemented on the `develop` branch, please let me know what you think and I'll get this in a release soon. Just need some other users to smoke test it first really.
