### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jlesquembre** [Olical/conjure#5]
I'm playing with Conjure, and it looks great, good job! Since I saw in twitter that you'd like some feedback, I'm writing it here, I hope it's ok.

- Conjure log looks nice, I really like the comments before the evaluation result. But I think it would be better if:
   - You have an option to show only the last result. Usually I'm only interested in the last one.
   - You have an option to split the log window horizontally. It's just a personal preference, but it'd make easier to read the `ConjureDoc` results
   
- `ConjureEvalRootForm` is nice, but it would be even better with support for "rich" comments. E.g., for 
```clojure
(comment
  (inc 1))
```
  I'd expect to evaluate `(inc 1)`, not `(comment (inc 1))`

I see a lot of potential on Conjure, looking forward to see how it evolves.

**Comment by Olical** [comment]
This is great, thank you very much! The two log comments make sense and are definitely things I could offer as configuration, good idea. I knew horizontal split would be mentioned very early on :stuck_out_tongue:

The eval of a comment body is a little more nuanced I guess but yeah, definitely one I'll think about. I'm not sure if I'd want `,rr` on a comment to actually eval by default but that's just me. A while back I was considering `1,rr` evalling one form in from the outside and `1,re` evalling one out from your current one, but wasn't sure about it.

I'm not even sure if it's possible, would potentially be pretty powerful though!

**Comment by Olical** [comment]
Pinned for others to use this issue as a place to discuss the current early state. If there's anyone that wishes to do so, that is :stuck_out_tongue:

**Comment by Olical** [comment]
Going to close this one since I'm still not sure about "smart comments" just yet and you wrote the log window config yourself! :D

**Comment by tomekw** [comment]
After trying out Conjure after a lot of time with The Other vim Clojure REPL plugin this was the first thing that occurred to me as well: it would be so cool to have a way to eval a rich comment block as well!

But I don't even where to start implementing this...

**Comment by Olical** [comment]
Although a proper solution depends on TreeSitter (which I'm now using personally, see `:h g:conjure#extract#tree_sitter#enabled`), I did sort of implement a solution for this, see `:h g:conjure#eval#gsubs` for more information on the feature but this is the config you'd maybe be interested in.

```viml
let g:conjure#eval#gsubs = {'do-comment': ['^%(comment[%s%c]', '(do ']}
```

**Comment by Olical** [comment]
That basically turns `(comment` blocks into `(do` blocks at eval time, which isn't what everyone really wants but it's a _step_.

**Comment by tomekw** [comment]
Wow, that works for me for now :) Thank you :pray:
