### ISSUE TITLE
ConjureEval failing with "unmatched delimiter"

### ISSUE THREAD

**Issue by ketansrivastav** [Olical/conjure#501]
So i am using my desktop after a few months and I am noticing this strange behavior. I have updated Neovim and Conjure (though not the Clojure LSP)

A few minutes after i start editing, as soon as there is any syntax error, ConjureEval starts failing with "unmatched delimiter" even after the syntax error has been fixed. If i save and close the file, and reopen it works fine until it starts failing again.
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```
I am not sure what am i doing wrong. 
It works fine on my laptop.

**Comment by Olical** [comment]
Are you using TreeSitter too? If so, make sure you use :TSUpdate whenever
you update Neovim since those two falling out of sync causes super weird
issues.

**Comment by ketansrivastav** [comment]
i wasn't using TreeSitter but i suspect you are right in TS having some role in this strange behavior -- i have played with multiple nvim.init and perhaps in one i had setup TS. I am still not sure what happened but after your suggestion, i actually went ahead and added TreeSitter and themnuninstalled and that seemed to have gotten rid of the problem!

Thanks, @Olical and keep up the good work!
