### ISSUE TITLE
Eval file in clojure nREPL on Windows isn't working.

### ISSUE THREAD

**Issue by UnderCooled** [Olical/conjure#505]
`extract.file-path` returns a path like this on Windows: `D:\foo\bar.clj`, then it's double-quoted in `eval-file`, `"D:\foo\bar.clj"`, those backslashes become escape like `\f`, `\b`.

https://github.com/Olical/conjure/blob/31a1626273e2bab479b6b8416a137f9edaba7daa/fnl/conjure/client/clojure/nrepl/action.fnl#L240

`opts.file-path` should be escaped on Windows platform: `(nvim.fn.escape opts.file-path "\\")` or `(opts.file-path:gsub "\\" "\\\\")`.

**Comment by Olical** [comment]
Ah no! Sorry, I'll get this fixed as soon as I can. Thanks you for reporting and sorry for the error, Windows paths always catch me out, we did a huge pass a year or so ago to escape everything and use the right slashes everywhere, I guess something slipped the net or was added later.

**Comment by Olical** [comment]
Pushed a fix for this to develop.

**Comment by UnderCooled** [comment]
It works great!
