### ISSUE TITLE
Remove redundent part in README.md

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#509]
This part: 
![image](https://github.com/Olical/conjure/assets/12870742/c857348c-503f-42ec-bc34-d8e99b8685d1)
And this part: 
![image](https://github.com/Olical/conjure/assets/12870742/dce3cc51-241c-42a5-af3d-92d39d8d3647)
Are 100% the same.

**Comment by Olical** [comment]
Yeah that did always irk me. I think I had both lists for a reason and I thought they were slightly different, but I guess not. I'll go take a look soon.
