### ISSUE TITLE
Can Conjure be configured to be silent (i.e. no popup) when starting?

### ISSUE THREAD

**Issue by daveyarwood** [Olical/conjure#51]
As I've been using Conjure, I've been noticing that I tend to reflexively press `<localleader>cq` to close the initial Conjure log that pops up and tells me the results of its trying to connect to any prepls as configured in conjure.edn:

```
; conjure/out | Welcome to Conjure! (v0.22.0-0-g0cbb94a56f)
; conjure/out | Adding :cwd
```

In practice, I don't care about these results upon starting Neovim, and I assume that it's just going to work when I'm ready to use it. (And if it doesn't work, I'll find out anyway!)

So I'm wondering, is there any way to configure Conjure not to pop up initially? I realize this is a bit complicated, because under the hood it's probably just doing what it always does with `:out` messages. And I _do_ want the Conjure log to pop open for `:out` messages, in general, like if I evaluate something that prints to STDOUT, or if I run `:ConjureUp`. It would be nice, anyway. Thoughts welcome. :)

**Comment by Olical** [comment]
So interestingly I was thinking about this exact thing. I think I might
move away from tagging them as out and use start tagging as conjure/conns
or something. Maybe conjure/up, just like how test output goes to
conjure/test.

But then if you turned off conjure/up you'd never see them / it's never pop
the log open. Unless you maybe rebound so you had your own mapping that
opened the log then ran up?

What do you think?

**Comment by daveyarwood** [comment]
I like the idea of tagging that output as `conjure/up` instead of `out`.  I didn't realize you could do that with prepl, neat!

Rebinding `<localleader>cu` to run `:ConjureUp` followed by `:ConjureOpenLog` sounds workable to me. There are a couple of related QOL things that would make me happy in that workflow:

* Having the ability to deliberately open the Conjure log in small mode would be nice. I have `g:conjure_log_size_large` set to 100%, which is what I want when I run `:ConjureOpenLog` by itself (to view large eval results, etc.), but to support opening it just to see the output following `:ConjureUp`, it would be nice to be able to open the log in small mode (i.e. 25%). It's a subtle thing, but it would feel more like the Conjure window is out of my way when I want it to be.

* Ideally, I wouldn't ever have to run `:ConjureUp` manually. Typically, I have to run `:ConjureUp` if I started Vim before I started my prepl server, or if I have to restart my prepl server for whatever reason. (Maybe that idea is already on the road map? It reminds me of the discussion around #15 )

**Comment by Olical** [comment]
So I've split `ConjureStatus` and `ConjureUp` log entries out into their own categories. If you have changed `g:conjure_log_auto_open` you'll need to add `status` and maybe `up` if you wanna see connection syncing output. But yeah, maybe being able to control log size when opening it would be good too.

Let me know how you get on with this first :smiley:

**Comment by Olical** [comment]
Something about how this is split up and configured smells to me right now, but I'll mull it over. Maybe I need to flip that list over so you choose what you _don't_ want to see?

**Comment by daveyarwood** [comment]
"Everything by default" does sound good to me. Maybe that implies a separate config var like `g:conjure_log_auto_open_blacklist`. If you did that and continued to treat `g:conjure_log_auto_open` as a whitelist (default: everything), you could probably make this a non-breaking change.

I tried the `develop` branch and it's looking good from my perspective. :+1:  I added `status` to my whitelist, and left `up` out so that the log doesn't pop open when I start Vim and Conjure tries to make its first connection to my prepl. I also added a `<localleader>cU` mapping that does `:ConjureUp<CR>:ConjureOpenLog<CR>`, but interestingly, I found that I didn't really need it, because in practice, I just run `:ConjureUp` (not seeing the output) and trust that it'll work, and if it doesn't work, I'll know as soon as I try to eval a form and the Conjure log pops open for the `err` message.

I think the next step is to have Conjure periodically re-up my connections, so that I never have to run `:ConjureUp` manually :)

**Comment by Olical** [comment]
Cool that all sounds good to me! I'm glad it works, and yeah, you shouldn't have to see the log when you `ConjureUp` really. It should do exactly what you expect, if you need to check it you can.

I think if I add a blacklist I may well just do a breaking change and remove the existing config while it's still < 1.0.0. Having that legacy forever after 1.0.0 will be a little gross I think, especially if I think it's not the best UX and the interaction with the new config will be... questionable. Like what happens if you set both.

I think I'll swap it to a blacklist and document it well for the next release. Or I'll call it "suppress" maybe.

Not sure about running `ConjureUp` periodically but I'll give it some thought. You might be starting and stopping other prepls you _don't_ want it to connect to until you ask / it might disconnect mid way through some execution. I'll give it some thought though!

**Comment by daveyarwood** [comment]
You're actually in a great position as the author of a plugin that's oriented around a log. Whenever you want to make a breaking change, if you want, you can follow a deprecation process where you notice when users are doing the old thing and print a warning to the log. In this case, for example, you could recognize when the old config variable is set and print a deprecation warning.

**Comment by Olical** [comment]
Good point, might go down that route so it sticks around for a while then
I'll have a prune sometimes.

**Comment by Olical** [comment]
Okay, `g:conjure_log_auto_open` has been swapped to `g:conjure_log_blacklist`, let me know how you get on!

https://github.com/Olical/conjure/commit/e90c56ac9725cefcae33344032913a99bbc3262e

Should solve your issues fairly nicely? I know it's a breaking change but I think it's for the best. Like a plaster, better to rip it off quickly.

**Comment by daveyarwood** [comment]
I like it. I went through and figured out what I need in my blacklist to get the equivalent of my current whitelist:

```viml
let g:conjure_log_blacklist = ["up", "eval", "ret", "load-file"]
```

I like this because the intent reads much clearer than with the whitelist version. :+1: 

One thing you might consider before this gets pushed to master: the name "conjure log blacklist" might imply that it's a list of things not to include in the log, vs. what it really is, which is a list of things that should not result in the log popping open. As such, I think `g:conjure_log_auto_open_blacklist` is a better name because it's more precise. It is a bit lengthy, though :)
