### ISSUE TITLE
Support repeating last evaluation

### ISSUE THREAD

**Issue by flipsi** [Olical/conjure#518]
I love this plugin, thank you for your efforts! :clap: 

---

The one feature that I am missing badly is the possiblity to **repeat evaluating whatever has been evaluated most recently**. 

This would require to store the evaluated form internally and evaluated again on demand. As demonstrated below, it may be necessary to exclude forms from being stored, so this becomes really useful.

I think this would enable many nice workflows. At the same time, it's hard to implement in the user's configuration (because evaluating a literal (`:ConjureEval`) or evaluating (`:ConjureEvalMarkedForm`) works quite differently).

---

What I'm suggesting is a new command like `:ConjureEvalLast` or `:ConjureRepeat` that behaves as follows:

### Literal evaluation (minimal example)
* Run `:ConjureEval (* 21 2)` => evaluates to `42`
* Run `:ConjureRepeat` => evaluates to `42`

### Running tests
* Focus some test buffer
* Run `:ConjureCljRunCurrentNsTests` => see test fail
* Focus application code buffer
* Fix code and re-evaluate with `:ConjureEvalRootForm <donotstore>` (without storing it, so the "last form" stays the test form!)
* Run `:ConjureRepeat` => see test succeed

**Comment by TimoKramer** [comment]
You can evaluate marks like here: https://youtu.be/AcWnGKGqFZA?t=812

**Comment by flipsi** [comment]
@TimoKramer thanks for your reply!

I am aware of the mark evaluation feature. It is not quite what I'm asking for. Note that e.g. for literal form evaluation or for running all tests within a namespace it would not work.

**Comment by Olical** [comment]
I think people have asked for this in the past, possibly have an open issue for it already. It wouldn't be too hard to implement for _some_ evaluations but gets tricky quite quickly when you need to remember and support: forms, root forms, marks, tests, files, buffers etc.

So this is easy if we just support "eval form", but to support everything gets a little more fiddly. Especially when you count custom mappings that some clients add. This feature should work for all clients and all eval solutions. I'll give it some more thought.

**Comment by flipsi** [comment]
Thank you @Olical!

> So this is easy if we just support "eval form", but to support everything gets a little more fiddly. [...] I'll give it some more thought.

Great, I appreciate it when plugin authors carefully consider new features instead of blindly adding them, especially when incomplete/inconsistent. :+1: 
I'd be happy to see this gaining more traction in the future.

>  Edit: Can't see an existing issue at a quick glance so maybe it's one I closed a long time ago.

I searched before I opened this issue. The only related one I found was #171, maybe that's what you had in mind? Maybe I didn't understand it (or it didn't work for some reason). Anyway, I would consider it a different feature. I don't think of code evaluations as editing actions that I want to repeat with the same mechanism.

**Comment by flipsi** [comment]
That's awesome, thank you, really appreciate it! :pray: 

> I'd over complicated this in my head which is what put me off of doing it, but I like this approach. If someone needs a way to evaluate at a distance and have code changes get picked up (i.e, the source changed but I still want to eval root form at that point) they can just use the mark eval system.

As far as I am concerned, evaluating the last expression _literally_ (i.e. not detecting code changes) is a feature not a bug :smile: 

I will try the feature in the upcoming weeks and may share further thoughts after using it for a while.
