### ISSUE TITLE
[Clojure] Is cider.nrepl/middleware necessary?

### ISSUE THREAD

**Issue by NoahTheDuke** [Olical/conjure#519]
In the [Quick start: Clojure](https://github.com/Olical/conjure/wiki/Quick-start:-Clojure) page, the repl alias includes the CIDER middleware (which bundles a lot of stuff). Is this strictly necessary for Conjure to work with Clojure? I think it's interfering sometimes with my workflow, but I want to make sure that's a potential source before I break Conjure in some new and interesting way I haven't seen yet.

**Comment by Olical** [comment]
It's optional, Conjure only uses nREPL ops that the nREPL says it supports. So it will warn you if you try to do something the nREPL doesn't support. What makes you think it's interfering?

**Comment by NoahTheDuke** [comment]
I'm honestly not sure, just sometimes it feels like Conjure acts in slightly different ways than I anticipated. I suspect I am just using it wrong or don't fully understand how it overlaps with clojure-lsp and/or coc.nvim and/or any other number of plugins I have. :grimacing: This just stood out to me as one potential source of additional functionality that I don't rely on intentionally. I'll close this for now as you've answered my question, which probably should have been a discussion now that I see you have them.
