### ISSUE TITLE
Deoplete Config

### ISSUE THREAD

**Issue by mn-dimension** [Olical/conjure#52]
The configuration for deoplete `keyword_pattern` in the readme is out of date. 

rather than

>let g:deoplete#keyword_patterns = {}
let g:deoplete#keyword_patterns.clojure = '[\w!$%&*+/:<=>?@\^_~\-\.#]*'

it should be:

 >call deoplete#custom#option('keyword_patterns', {'clojure': '[\w!$%&*+/:<=>?@\^_~\-\.#]*'})

**Comment by Olical** [comment]
Thanks for pointing this out, I've corrected it on develop.
