### ISSUE TITLE
Add Quick Start guides for SQL and snd-s7 clients

### ISSUE THREAD

**Issue by russtoku** [Olical/conjure#523]
Having commented on issue #521, it occurs to me that there are no Quick Start guides for the SQL and snd-s7 clients. I should add them before I forget how to use them. Some information about them is in the associated issues and PRs but a Quick Start guide would be easier for others to find.

**Comment by russtoku** [comment]
Added:
* https://github.com/Olical/conjure/wiki/Quick-start:-snd%E2%80%90s7-(stdio)
* https://github.com/Olical/conjure/wiki/Quick-start:-SQL-(stdio)

**Comment by Olical** [comment]
Oh nice, thank you very much!
