### ISSUE TITLE
[Clojure] Defining custom/alternative test runner

### ISSUE THREAD

**Issue by NoahTheDuke** [Olical/conjure#525]
Hey Ollie!

I'm experimenting with an alternative to `clojure.test` and I'd like to be able to run the tests from within Conjure. I know that `kaocha` is built-in but that required modifying Conjure itself. If I wanted to make my own Conjure test runner, could I do this from my dotfiles? Maybe some method of altering [conjure.client.clojure.nrepl.action/test-runners](https://github.com/Olical/conjure/blob/0d9b823db06cc11e6115b54297f690dff10c0299/fnl/conjure/client/clojure/nrepl/action.fnl#L397) or related functions to hook in my own stuff?

If this seems reasonable or interesting, I can develop a patch to make this work.

Thanks so much!

**Comment by NoahTheDuke** [comment]
Using the `develop` branch, the below works great!

```
local runners = require("conjure.client.clojure.nrepl.action")

runners["test-runners"].lazytest = {
  ["namespace"] = "lazytest.runner.console",
  ["all-fn"] = "run-tests",
  ["ns-fn"] = "run-tests",
  ["single-fn"] = "run-test-var",
  ["default-call-suffix"] = "",
  ["name-prefix"] = "#'",
  ["name-suffix"] = "",
}

vim.g["conjure#client#clojure#nrepl#test#runner"] = "lazytest"
vim.g["conjure#client#clojure#nrepl#test#current_form_names"] = { "describe" }
```

I suspect there's a smoother way to do it, but for me, this is really solid.

**Comment by NoahTheDuke** [comment]
Given that this works so well, want me to add a section to the docs about it?

**Comment by Olical** [comment]
Ohh that'd be great actually, could start with a wiki page? I feel like that'll be better than help text for this since it's a bit more involved than just setting a variable to a number/string in nvim global variables. Thanks!

**Comment by NoahTheDuke** [comment]
I've added it [here](https://github.com/Olical/conjure/wiki/Using-Conjure-programatically-(API)#using-a-custom-test-framework-clojure). Edit as you desire!
