### ISSUE TITLE
Regression on the `develop` branch since 5119706fa08ecb1efa72fb9d6e68bb965d259015

### ISSUE THREAD

**Issue by dharrigan** [Olical/conjure#526]
Hi,

Since this commit `https://github.com/Olical/conjure/commit/5119706fa08ecb1efa72fb9d6e68bb965d259015`, when eval'ing a buffer, a screenful of this (below) is presented:

```
:
; (err) Error printing return value (ArityException) at clojure.lang.AFn/throwArity (AFn.java:429).
; (err) Wrong number of args (3) passed to: clojure.pprint/pprint
; (err) Error printing return value (ArityException) at clojure.lang.AFn/throwArity (AFn.java:429).
; (err) Wrong number of args (3) passed to: clojure.pprint/pprint
; (err) Error printing return value (ArityException) at clojure.lang.AFn/throwArity (AFn.java:429).
; (err) Wrong number of args (3) passed to: clojure.pprint/pprint
```

and so on and so on.

Reverting to the previous commit `e5586b7bfaad4e1319cd357f5101ab50b59f8689`, the error goes away.

-=david=-

**Comment by Olical** [comment]
Sorry about this and thanks for pointing it out. I can't wait to port this to nfnl where this bug would be impossible 😅 it came out of some #406 experimentation, I had changed the pprint fn back to the correct one but hadn't compiled after the previous attempt. Should be okay now!

**Comment by dharrigan** [comment]
Thanks Oliver for taking a look and fixing quickly :-)

Have a lovely day.

-=david=-

**Comment by dharrigan** [comment]
All working grand. I'll close this issue.
