### ISSUE TITLE
Randomly losing keymaps

### ISSUE THREAD

**Issue by dgriffith0** [Olical/conjure#537]
I use the default setup with the exception of setting , as my leader for conjure. Majority of the time I have no issues but occasionally when I open a new clj file the key map is gone and the only way I can get it back is to close down neovim. Any ideas what might be happening? It isn’t any specific file. On a typical 8 hour day I might see it a couple times. 

Is there a quick way to reload the keymaps in the file thats missing them?

**Comment by Olical** [comment]
Sorry! I thought I'd responded to this, hard to keep track sometimes I'm afraid. This sounds like a really weird bug that I've never encountered, I suspect it's interplay with another plugin but can't be sure. Did you manage to resolve it or did you have to stop using Conjure? Just for future reference.
