### ISSUE TITLE
Clojure: evaluate word misinterprets single-quotes in symbol names

### ISSUE THREAD

**Issue by mars0i** [Olical/conjure#538]
In Clojure a single-quote is a legal character in a symbol name, if it's not the first character: https://clojure.org/reference/reader#_symbols

```clojure
(def x 1) 
(def x' 3) 
(def y 42)
(def x'y 4) 
```
If I evaluate `x'` or `x'y` at a normal nrepl or clj prompt, the results are 3 and 4, respectively.  

However, if I evaluate `x'` in Neovim using Conjure's `<LocalLeader>ew`, the results is 1 if the cursor is on `x`, but 3 if the cursor is on the quotation mark.  

If I evaluate `x'y` using `<LocalLeader>ew`, the result is 1 if the cursor is on `x`, and 42 if the cursor is on the quotation mark or the `y`.

So Conjure treats a single-quote as beginning a new symbol name?  I'm not sure if that's the right way to describe the problem.

(I don't know how to check the Conjure version, but I use vim.plug, and I just ran `PlugUpdate` and got this result with the latest release.)

**Comment by Olical** [comment]
This works fine for me with treesitter enabled so this is the legacy word extraction code, having a look now.

**Comment by mars0i** [comment]
Thanks @Olical !  `:set iskeyword+='` seems to work.  I'll consider doing something further with the syntax file.  I think I see the relevant line, but I'd have to learn to parse what looks like line noise. :-) 

I haven't used treesitter--seemed like overkill for my needs and interests--but maybe this is a reason to use it.

**Comment by mars0i** [comment]
Thanks @Olical.  Those comments are much appreciated.  I will definitely put it on the todo list.
