### ISSUE TITLE
README Suggestion

### ISSUE THREAD

**Issue by Sleepful** [Olical/conjure#541]
Add this example to the readme:
```lua
vim.cmd("let g:conjure#mapping#doc_word = v:false")
```

The default `K` mapping was overwriting my `vim.lsp.buf.hover`, and it took me a good amount of time to figure out that this Conjure option was the way to change that.

I think it is pretty common to have an LSP set-up these days.

As an additional comment, it would be great to add a quick rundown of the default keybinds to the readme! Even though the docs here https://github.com/Olical/conjure/blob/master/doc/conjure.txt are quite thorough, the information is a bit "hidden" from a user installing the first time.

Well, I know that is how it felt for me because I had a lot of trouble figuring out these other plugins at the same time:

```lua
  { "tpope/vim-dispatch",            ft = clojure_filetype },
  { "radenling/vim-dispatch-neovim", ft = clojure_filetype },
  {
    "clojure-vim/vim-jack-in",
    ft = clojure_filetype,
    config = function()
      vim.g.default_lein_task = "with-profile dev repl"
    end
  }
```

So for the distracted and overwhelmed user coming in here for the first time, it is great practice to add the default keymaps to the readme! Otherwise big surprise while coding and lots of searching.

Thanks! This plugin is super dope.

**Comment by Olical** [comment]
Mulling this over, but I'd argue `vim.g["conjure#mapping#doc_word"] = false` would be a better way to do this since it doesn't involve a VimL parsing step.
