### ISSUE TITLE
Cannot connect to Scheme through socket

### ISSUE THREAD

**Issue by ab5tract** [Olical/conjure#543]
I've just installed everything fresh using Magic-Kit. However I'm unable to successfully connect to Guile Scheme (3.0.9) running on a socket using the instructions outlined on the wiki (macOS 14.1.1).

This appears in nvim after several attempts to `ConjureConnect`:

<img width="378" alt="image" src="https://github.com/Olical/conjure/assets/2742/8b8a723c-e96b-4f47-b194-9debd19f189f">

And occassionally output like this appears in the running REPL:

<img width="239" alt="image" src="https://github.com/Olical/conjure/assets/2742/2f0bf3f5-b75e-49ab-8f23-7c54760eb26a">

**Comment by russtoku** [comment]
Can you provide:

- What is `g:conjure#client#guile#socket#pipename` set to?
- What is `g:conjure#filetype#scheme` set to?
- How are you starting your Guile REPL?

When editing your Scheme file, have you tried using `<localleader>cc` to connect to your REPL and `<localleader>cd` to disconnect?

You can execute this on the nvm command line if you don't know what `<localleader>` is mapped to:

```
echo "-"g:maplocalleader"-"
```

There will be a space after the first "-" and before the second "-".

**Comment by ab5tract** [comment]
Hi @russtoku,

Sorry, I thought it was clear through the output that `g:conjure#client#guile#socket#pipename` was set to `/Users/longwalker/.local/bin/.guile-repl.socket`. Everything but using this absolute path is the same as the setup described in the wiki page.

Anyway, it works! It might be worth updating the documentation to include using `<localleder>cc` to connect, as that seems to have worked just fine. Or maybe I was connected before and just didn't understand it.

Thank you to everyone who has worked on this! I really don't want to learn emacs just to hack on Scheme :)

**Comment by russtoku** [comment]
Some follow-up notes:
- The Conjure wiki page on [Guile](https://github.com/Olical/conjure/wiki/Quick-start:-Guile-(socket)) is not correct about automatically connecting to a running Guile REPL listening on a domain socket.
- The occasional messages in the terminal that the Guile REPL is running in are produced when disconnecting the Conjure Guile client from the Guile REPL.
- The log buffer message "Empty result" is typically produced when there is an error.
