### ISSUE TITLE
Problems with evaluation: wrong returns

### ISSUE THREAD

**Issue by lanjoni** [Olical/conjure#548]
First of all I would like to thank you for the incredible plugin! It has been my main means of developing with Clojure, where the speed and easy interactivity has attracted me a lot, so know that it is an incredible plugin!

Well, I'm having some problems evaluating some functions, in which they often give me a value that seems "wrong", like executing functions returning what they shouldn't, among other problems. This has been happening for a while and I would like to understand the problem and if there is any kind of solution.

![image](https://github.com/Olical/conjure/assets/91899995/117b5838-947e-4a7a-a46a-6e98c9ac4bbf)

![image](https://github.com/Olical/conjure/assets/91899995/2ec6cc79-a815-45fc-b135-d328931b70a9)

The projects I use are mostly running with Leiningen, perhaps this could be a point? And yes, to run and start the REPL I have used `:Lein` with the `vim-jack-in` configuration. To configure the plugin I'm using Lazy instead of Packer!

**Comment by leafgarland** [comment]
Just guessing but are you evaluating the whole file/buffer, instead of the current definition/form?

When you evaluate the file/buffer the displayed result is the last form. Is `validate-token` the last form in your file?

**Comment by lanjoni** [comment]
Yes, indeed, this is the last function in my file. But, does this assessment make sense? After all, the key combination I'm using is the `<leader> + e + b` pattern.

**Comment by lanjoni** [comment]
Thank you very much @leafgarland for alerting me that I was evaluating the entire file! The correct key combination would be `<leader> + e + e`!
