### ISSUE TITLE
Question: Working with cljs and Fulcro app 

### ISSUE THREAD

**Issue by rafaeldelboni** [Olical/conjure#55]
First of all, thanks for this plugin!

I've been a couple of days using it with my company backend services written in Clojure and is super great!

Now I would like some help to setup an environment to play around with some `cljs` and `fulcro`.

### Here is what I'm doing:

1. `lein new fulcro app` 
2. `npm install` and `npx shadow-cljs server`
3. Turn On building and watching the `main` and `workspaces`
4. `lein repl :connect 9000`
5. Execute the following command in the repl:
```
(clojure.core.server/start-server {:accept 'clojure.core.server/io-prepl :address "localhost" :port 55555 :name "lein"})
(clojure.core.server/start-server {:accept 'cljs.server.node/prepl :address "localhost" :port 55556 :name "node"})
```
6. Open `nvim`

When I open a `.clj` file like `server_main.clj` everything is working great, but for any `.cljs` file I lost all the benefits like `Go To Definiton`, `Documentation` and `Auto Complete`.

Here is my `conjure.edn` file
```
{:conns
 {:lein {:port 55555}
  :node {:port 55556 :lang :cljs}}}
```

Can someone help me to find out what I'm doing wrong?

### Log
[conjure.log](https://github.com/Olical/conjure/files/3509956/conjure.log)

**Comment by Olical** [comment]
Hmm, so evaluation works but nothing else does? I'm currently poking around
with Orchard integration which should improve the ClojureScript side a lot!

**Comment by Olical** [comment]
So I've fixed go to definition to an extent on a branch that'll be released as part of my 1.0.0 documentation push (hopefully tomorrow!), documentation seems to work fine for me :thinking: 

![Screenshot_2019-08-30_00-21-45](https://user-images.githubusercontent.com/315229/63982883-40b86700-cabc-11e9-9d47-a781468636d4.png)

Waiting on Complement to release their next version that adds ClojureScript support which I think is almost there!

I've completely refactored how dependencies are prepared and injected so hopefully that'll make integration for ClojureScript easier going forward. You probably won't see _many_ improvements in the next release but I will be giving the CLJS side more love as the tooling I depend on adds more and more support :smile: 

Go to definition was broken though, it was using `clojure.string` internally which _might_ not have been loaded in your environment.

**Comment by Olical** [comment]
Also worth noting, if you eval a function with `,ee` or something then it loses it's definition information. The only way to preserve it is to eval the whole file with `,ef`. I can't find a nice way to tell ClojureScript where things are right now like I do with Clojure but I may find a way some day and it'll just start working for you.

I'm working around the constraints of a ClojureScript only REPL as best I can :slightly_smiling_face:

**Comment by Olical** [comment]
I'm going to close this for now since you should have doc and go to definition (for some symbols) again. To keep go to definition working consistently you should evaluate the entire file from disk (`<localleader>ef`), if you just evaluate the form it'll lose it's definition information.

It's annoying but I can't find a way around that just yet, I'll see what I can do to improve that eventually! Autocompletion will start working soon I hope, I'm waiting on a new release of Compliment.

**Comment by rafaeldelboni** [comment]
Is there any special setup for this, or only updating to 1.0.0 should be fin

**Comment by Olical** [comment]
Updating to 1.0 should just fix a few small things around the Clojure
script doc lookup and definition stuff. It won't be perfect still, but I
hope it'll be slightly better.

I've got more to do around here but updating to 1.0 is all you need to do
for now. My main concern was that you could eval, everything else in CLJS
isn't amazing just yet but it'll improve 😄

**Comment by rafaeldelboni** [comment]
Go to definition and docs is a great progress, I will try it out and give you an feedback, just  a last question in this thread: Which prepl should I use node or browser?

**Comment by Olical** [comment]
I'll need to have a proper look tomorrow, I'm too tired tonight I'm afraid.
You might need to start up fulcro, then ask it for the ClojureScript
environment then give that to a prepl.

I'd recommend you go and read the source of Propel, there isn't much but
what I'm doing with figwheel you might need to do here.

I'm assuming fulcro starts your ClojureScript builds and serves then to the
browser for you? If so, you need to do the stuff I did with figwheel.

If it's up to you to start the environment you can use any prepl you want,
browser will be fine.

My point being, starting a browser prepl is its own ClojureScript
environment, like starting a fresh JVM. If fulcro starts their own one...
it's like having two JVM instances, evals in one won't effect the other. I
hope that makes sense?
