### ISSUE TITLE
Local leader key not active when open scm files

### ISSUE THREAD

**Issue by mrmodolo** [Olical/conjure#554]
Hi!

Sometimes the local leader key does not work when opening a ".scm" scheme file. To get it working again, you need to open another buffer and go back to the buffer again. At this moment, the `\`  key works again.

This is my config.

```lua
return {
  "Olical/conjure",
  ft = { "scheme" }, -- etc
  dependencies = {
    {
      "PaterJason/cmp-conjure",
      config = function()
        local cmp = require("cmp")
        local config = cmp.get_config()
        table.insert(config.sources, {
          name = "buffer",
          option = {
            sources = {
              { name = "conjure" },
            },
          },
        })
        cmp.setup(config)
      end,
    },
  },
  config = function()
    require("conjure.main").main()
    require("conjure.mapping")["on-filetype"]()
    -- vim.g["conjure#mapping#prefix"] = "\\"
  end,
  init = function()
    -- Set configuration options here
    vim.g["conjure#debug"] = true
  end,
}

```
```bash
nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

Lazyvim - updated
```

Other than that, the plugin is excellent, I'm using mit-scheme and it's very pleasant to learn with the instant evaluation functionality!

Regards,
Marcelo Módolo

**Comment by mrmodolo** [comment]
Hi!

I try to use vim.g.maplocalleader = "\\" like you said but it had no effect. I put lazy = false but I don't know if that's what you meant, it's also set to scheme only.

```lua
return {
	"Olical/conjure",
	ft = { "scheme" },
	dependencies = {
		{
			"PaterJason/cmp-conjure",
			config = function()
				local cmp = require("cmp")
				local config = cmp.get_config()
				table.insert(config.sources, {
					name = "buffer",
					option = {
						sources = {
							{ name = "conjure" },
						},
					},
				})
				cmp.setup(config)
			end,
		},
	},
	config = function()
		vim.g.maplocalleader = "\\"
		require("conjure.main").main()
		require("conjure.mapping")["on-filetype"]()
	end,
	init = function()
		-- Set configuration options here
		vim.g["conjure#debug"] = true
	end,
	lazy = false,
}
```
This is my current configuration, I discovered another way to activate the menu with `\` I press `<leader> g` to show the menu and then the ESC key, from that moment on the `\` key works again.

Regards,
Marcelo Módolo

**Comment by Olical** [comment]
Sorry for the delay, had a very busy week! That's very very odd, so `\` doesn't work until you press `<leader>g`, then after that point you can use `\` as your local leader no problem? This still feels like an issue to do with lazy loading to me, maybe not Conjure but maybe some other plugin that has some other config that loads later because of some filetype or event.

I'm afraid I can't think of any tips right now, everything looks okay to me in general, maybe try ruling out laziness by disabling globally? Just to check if it's a race condition somewhere? I've never run into this myself so I don't have much advice to offer 😞

**Comment by mrmodolo** [comment]
> Sorry for the delay, had a very busy week! That's very very odd, so `\` doesn't work until you press `<leader>g`, then after that point you can use `\` as your local leader no problem? This still feels like an issue to do with lazy loading to me, maybe not Conjure but maybe some other plugin that has some other config that loads later because of some filetype or event.
> 
> I'm afraid I can't think of any tips right now, everything looks okay to me in general, maybe try ruling out laziness by disabling globally? Just to check if it's a race condition somewhere? I've never run into this myself so I don't have much advice to offer 😞

Hi!
No problem, I've gotten the hang of it, and it's not such a bad thing.

Thanks,
marcelo Módolo

**Comment by Olical** [comment]
Hm okay then, I still think this is something local to your config somehow and not really something I can fix, I'm just sorry you're having to deal with it. Are you happy to close this issue for now and re-open if you can reproduce it with a minimal configuration that I can also reproduce with? Or if someone else turns up with the same issue of course.

**Comment by mrmodolo** [comment]
> Hm okay then, I still think this is something local to your config somehow and not really something I can fix, I'm just sorry you're having to deal with it. Are you happy to close this issue for now and re-open if you can reproduce it with a minimal configuration that I can also reproduce with? Or if someone else turns up with the same issue of course.

**Comment by mrmodolo** [comment]
Hi!

I did a test on another lazyvim installation (another computer) and the behavior was the same, but it could be the result of other installed plugins. But it's no reason to waste time, otherwise everything works very well.

Thanks,
Marcelo Módolo
