### ISSUE TITLE
Alternate scheme interpreters do not appear to work

### ISSUE THREAD

**Issue by c-tb** [Olical/conjure#583]
I've followed the directions as specified in: [Scheme Quickstart](https://github.com/Olical/conjure/wiki/Quick-start:-Scheme-(stdio)).

However, when attempting to evaluate the Buffer, File, or current form, this error appears:
```
E5108: Error executing lua: Vim:Error executing Lua callback: ...ngma/.local/share/nvim/lazy/conjure/lua/conjure/eval.lua:166: Conjure client ''
doesn't support function: eval-str
stack traceback:
        [builtin#19]: at 0x01049417c8
        ...ngma/.local/share/nvim/lazy/conjure/lua/conjure/eval.lua:166: in function 'eval_str'
        ...ngma/.local/share/nvim/lazy/conjure/lua/conjure/eval.lua:198: in function <...ngma/.local/share/nvim/lazy/conjure/lua/conjure/eval.lua
:192>
        [C]: at 0x0104b3841c
stack traceback:
        [C]: at 0x0104b3841c
```

Platform: MacOS Apple Silicon
Neovim: v0.10.0

init.lua (chez):
```lua
vim.cmd([[
  let g:conjure#client#scheme#stdio#command = "petite"
  let g:conjure#client#scheme#stdio#prompt_pattern = "> $"
  let g:conjure#client#scheme#stdio#value_prefix_pattern = v:false
]])

local plugins = require("plugins")({
	...
	{ "Olical/conjure" }, -- LISP / Scheme REPL tools.
	...
})
```

init.lua (chicken):
```lua
vim.cmd([[
  let g:conjure#client#scheme#stdio#command = "csi -quiet -:c"
  let g:conjure#client#scheme#stdio#prompt_pattern = "\n-#;%d-> "
  let g:conjure#client#scheme#stdio#value_prefix_pattern = v:false
]])

local plugins = require("plugins")({
	...
	{ "Olical/conjure" }, -- LISP / Scheme REPL tools.
	...
})

```

The REPLs appear to start fine:
Chez output on start of a .scm file:
```
┌────────────────────────────────────────────────────────────┐
│Sponsored by @harrygallagher4 ❤                             │
│------------------------------------------------------------│
│; petite (started)                                          │
│Petite Chez Scheme Version 10.0.0                           │
│Copyright 1984-2024 Cisco Systems, Inc.                     │
│                                                            │
│                                                            │
│                                                            │
│                                                            │
│                                                            │
│                                                            │
│                                                            │                                                                                  └────────────────────────────────────────────────────────────┘
```

Maybe I am missing configuration, but I cannot find any more information on setting up my scheme interpreter other than the quickstart linked above.

Please let me know if there is additional information i can provide.

My full neovim config: https://github.com/c-tb/neovim-config

- Timm

**Comment by Olical** [comment]
Hey! Sorry about the issues you're experiencing. I'm hoping this is just a configuration thing and not a bug. The error `Conjure client ''` is suggesting that you don't have a client for this buffer, so the client is `nil` which maps to an empty string.

This normally comes from the filetype configuration

https://github.com/Olical/conjure/blob/v4.52.1/doc/conjure.txt#L257

So you need to tell Conjure which filetypes it should work with and also which client to use for each filetype. The thing I want to check is if:

 - Your current `filetype` is just `scheme`
 - Is your `g:conjure#filetype#scheme` set to `conjure.client.scheme.stdio`?

If those are both true then something else is going on and I'll try to help you get to the bottom of it.

**Comment by Olical** [comment]
Also can you open the log buffer without evaluating? So running `<prefix>lv` or something similar? Does that open a Conjure log buffer ending in `.scm`? I guess it should since you showed the HUD output displaying the REPL starting.

Right now with the error you showed on eval I would expect the log to ALSO not work. The fact that it does is confusing.

**Comment by c-tb** [comment]
Hi! thanks for the reply.

so `set filetype?` gives me `filetype=r7rs`

and my `g:conjure#filetype#scheme` is `conjure.client.scheme.stdio`

which makes me realize that i've done this to myself 😅 

I'm using https://github.com/m15a/vim-r7rs-syntax to provide better syntax highlighting.

I disabled that and everything works! :)

----

I'll have to figure out how to get that theme working without messing around with the filetype.

Thanks for the troubleshooting help!

**Comment by Olical** [comment]
So you should be able to use that if you add the filetype to conjures known
filetypes array then create a config option for that filetype that loads
the scheme client. It's definitely doable!
