### ISSUE TITLE
`fs.upwards-file-search` not always returning absolute paths

### ISSUE THREAD

**Issue by pyrmont** [Olical/conjure#587]
In the docstring for `fs.upwards-file-search`, it says:

https://github.com/Olical/conjure/blob/a81977726f726b21d4bd75cea5bbbb7022005507/fnl/conjure/fs.fnl#L44-L48

I don’t think this is always correct. In my code, if the file is in the `from-dir` directory, what will be returned is the bare filename rather than the absolute path. I think this is because that’s what `nvim.fn.findfile` returns.

**Comment by Olical** [comment]
Thanks for catching this, I've updated the chain of functions based on `findfile` to now resolve paths to their absolute versions and then normalize them for the OS we're working on. I worry that this will break Windows support somehow as it usually does whenever I do anything path related 😢 

I really need to get the test suite running under Windows like what is currently progressing in nfnl, but there's some Neovim Windows bugs around file trust stuff that needs to be fixed first. I think I won't port this system to Windows but instead include that as part of the nfnl port.

I'm wondering if I should normalize here, maybe just expanding to absolute paths is enough and the normalize step will be what breaks Windows support. I don't have a way to test this right now though, I have no idea what steps it would take to test this out on Windows.

**Comment by Olical** [comment]
Oh and the tests are failing in CI but not locally, drat!

**Comment by Olical** [comment]
Removed the normalize call, I think that's good in nfnl land but might break assumptions in Conjure around how we treat paths in the system.
