### ISSUE TITLE
Interested in extra prepl messages?

### ISSUE THREAD

**Issue by thheller** [Olical/conjure#59]
I'm currently implemented the pREPL support in shadow-cljs and wonder if you'd be interested in receiving "extra" messages from the server for CLJS REPLs.

So in addition to the regular `:tag :ret|:out|:err` you'd get something like `{:tag :shadow/info ...}`. Those messages would basically be notifications of events happening with a CLJS build. These would mostly be about

- a JS runtime connecting (eg. user opens browser output, new tab, different browser)
- a JS runtime disconnecting (eg. tab closed, hard reload -> followed by new connect)

I already have the events available and currently have to decide if I should just discard them or put them on the socket. Regular CLJS REPLs don't report these events so you might not be interested in them at all?

**Comment by Olical** [comment]
Ohhh that could be neat, I'd probably print them under some other "type" of message in the log so that users could blacklist it separately to stop it opening the log window.

I'd say it can't hurt, the only problems could be if the client connecting expected the prepl to behave exactly like a normal prepl, people need to build their clients to log or ignore unknown messages.

Mine is built on assumptions that I'll only see one :ret and only after I've evaluated a single form, for example. But I could see out, tap or err at any time.

I'd say go ahead, can't hurt! I think!

**Comment by thheller** [comment]
Good to know.

It might make sense to accept multiple `:ret` values in case it is possible for the user to send `1 2 3` directly to the REPL socket. Not sure how much parsing you do on your end.

I'll try to make a wiki page of all the possible "extra" prepl messages you might receive.

**Comment by Olical** [comment]
So if you send multiple forms you will get multiple `:ret` values, Conjure however wraps all evaluations to ensure multiple forms (such as an entire buffer contents or visual range eval) will always return one thing.

In Clojure it does this by passing the raw string wrapped in some code to evaluate it with the correct source file / line / column set. This means the code sent to the prepl is actually one form, no matter what, that contains the code to evaluate your code. If that makes sense?

In CLJS I try to work out if you have a single form or many, if I am sure you're sending one form it's sent as is, no modifications are made other than switching to the correct namespace for the eval. If you send multiple forms they'll be automatically wrapped in a `do` which _could_ cause issues in some rare cases, but the only one I know of is some specific namespace form evals.

If I started using self hosted CLJS (which I think would bring a whole host of complications) then I could do the wrapped eval just like I do in Clojure, which would be nice. I don't think I can do self hosted CLJS and have all the require loading etc just work out of the box... I think you know more than me about that though, maybe self hosting would be a good route for CLJS evals.

Then I think I could set the file / line / col for different evals which would be :ok_hand: 

Super excited to see prepl getting "native" support in shadow though!

**Comment by thheller** [comment]
Even self-hosted can't get past the limitations of the CLJS REPL. You can find the REPL specials [here](https://github.com/thheller/clojurescript/blob/820e6fa0fd10a5ac9ce2606e955debfc82934454/src/main/clojure/cljs/repl.cljc#L779-L790) and those wouldn't work when wrapped in a `do`.

Most of those can't work like Clojure because almost all IO is async in JS so a `require` that needs to load namespaces from somewhere first would need to take a callback before proceeding. In Clojure `require` is blocking and you can immediately use the new ns.

I believe the default CLJS repl impls (eg. browser) are still buggy and evaluating `(require 'some.ns) (some.ns/foo)` too quickly would fail if there isn't an accidental "wait" time after the `require`.

**Comment by Olical** [comment]
Yep, of course. So if you eval the file or you eval that single form it'll be fine. If a user tries to eval multiple forms from a range or block it'll cause issues but I think that's okay. There's some... interesting... workarounds I could do for evaluating the whole buffer from memory (not from disk) for example, but for the most part it all works fine.

Generally when I'm editing CLJS I use `<localleader>ef` a lot which translates to a `load-file` call, that produces nice results with the "go to definition" information intact.

I don't require any sync `require` as part of Conjure, so I'm okay on that front :slightly_smiling_face:

**Comment by Olical** [comment]
Going to close this issue for now since I don't think there's much else to say. If you want to send some extra values I'd be happy to render them :smile: I'll make sure there's a catch all for non-standard prepl messages.
