### ISSUE TITLE
All `ret` values seem to be multiline now

### ISSUE THREAD

**Issue by daveyarwood** [Olical/conjure#60]
# Logs

[conjure.log](https://github.com/Olical/conjure/files/3588234/conjure.log)

# Issue

My `g:conjure_log_blacklist` includes `ret`, as I prefer for the log not to pop open for single-line `ret` values.

I noticed since a recent update that all `ret` values seem to be popping open the Conjure log now. It appears that there might be a newline prepended to all of them, making them all multiline. For example, if I eval `(+ 1 2)`, the Conjure log pops open and I see:

```
; cwd/eval | (+ 1 2)
; cwd/ret ⤸
3
```

I noticed that there is no initial newline for `out` values, incidentally. If I eval `(println (+ 1 2))`, I get:

```
; cwd/eval | (println (+ 1 2))
; cwd/out | 3
; cwd/ret ⤸
nil
```

**Comment by daveyarwood** [comment]
I just updated Conjure again and the issue seems to have corrected itself!

I think I may have been misunderstanding the output, anyway. The Conjure log still has the same sort of output:

```
; cwd/eval | (+ 1 2)
; cwd/ret ⤸
3
```

However, the log doesn't pop open anymore on single-line `ret`, which the 3 does indeed seem to be. When I eval something that causes a multi-line `ret`, the log does pop open as expected.

**Comment by Olical** [comment]
Yep, I fixed that the other day, Nate pointed it out and I think I fixed it on master? It was suuuuper silly, I had `(and x) y` instead of `(and x y)` essentially :upside_down_face: a refactoring / sexp gone wrong.

**Comment by Olical** [comment]
So the output of single and multi line ret looks very similar, this was essentially saying "I'm multi line!" when it wasn't, but the output in the log should look the same. It's just the categorization for blacklisting that got fixed really.
