### ISSUE TITLE
Conjure hijacks my <leader>gd mapping

### ISSUE THREAD

**Issue by pillmuncher** [Olical/conjure#614]
I get this error message when I press `<leader>gd` (for _Goto Definition_) in a Python buffer in normal mode, even though I haven't added Python to the `ft` list in the Conjure config:
```
E5108: Error executing lua: Vim:Error executing Lua callback: Conjure client 'conjure.client.python.stdio' doesn't support function: def-str
stack traceback:
	[builtin#19]: at 0x7f5c982dba40
	[C]: at 0x55df00247d73
stack traceback:
	[C]: at 0x55df00247d73
```
Even disabling `conjure.mapping` or adding `vim.g["conjure#filetype#python"] = false` as suggested [here](https://github.com/Olical/conjure/issues/472#issuecomment-1484073000) doesn't help.

Here is my conjure.lua file:
```
vim.g["conjure#filetype#python"] = false
return {
    "Olical/conjure",
    ft = {
        "clojure",
        "fennel",
        "hy",
        "racket"
    },
    dependencies = {
        { "Olical/nfnl",           ft = "fennel" },
        { "Olical/aniseed" },
        { "PaterJason/cmp-conjure" },
    },
    config = function()
        require("conjure.main").main()
        -- require("conjure.mapping")["on-filetype"]()
    end,
    init = function()
        vim.g["conjure#debug"] = true
    end,
}
```
In the `on_attach` function in LSP config I've mapped that combination like so:
```
buf_set_keymap(bufnr, 'n', '<leader>gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
```
I just found out [here](https://github.com/Olical/conjure/issues/533#issue-1952543152) that I can disable Conjure's mappings altogether with this:
```
vim.g["conjure#mapping#enable_ft_mappings"] = false
```
That would mean I'd have to set all mappings myself, just because I want to disable one specific mapping for one specific file type. Or are there other options that I've overlooked?

**Comment by Olical** [comment]
You can also disable each mapping, the help text gives the exact variable
for go to Def, I think you also just need to set it to false?

**Comment by Olical** [comment]
Here's the config for the def word mapping

https://github.com/Olical/conjure/blob/6d2bc7f7b24c2c43d54f263bee7b9b08aef5d1a1/doc/conjure.txt#L555-L558

And here's the part that mentions how mappings can be un-prefixed or disabled

https://github.com/Olical/conjure/blob/6d2bc7f7b24c2c43d54f263bee7b9b08aef5d1a1/doc/conjure.txt#L217-L231

So setting this should do the trick!

```vim
" Disable the mapping entirely. Notice the `b:` prefix, this can be used in a Python ft autocmd to disable it ONLY in Python. Use g: if you want to disable it everywhere.
let b:conjure#mapping#def_word = v:false
```

Alternatively, you could remap it to something like `"gD"` so `<leader>gd` would be LSP and `<leader>gD` would be Conjure. I hope some of this helps!
