### ISSUE TITLE
:ConjureEval keeps toggling a new buffer even if :ConjureLogToggle was already run after using :ConjureEvalBuf

### ISSUE THREAD

**Issue by AlexisG13** [Olical/conjure#615]
Hi!
I like to have the Conjure Log buffer opened permanently so I used :ConjureLogToggle to keep it open but if I try  to load the complete current buffer I'm working on and then just :ConjureEval a single form Conjure toggles a new LogBuffer while also updating the LogBuffer I already had open. Is this the expected behavior? 

![image](https://github.com/user-attachments/assets/d273492f-3ccf-46da-b9e3-6430c09a678d)

**Comment by Olical** [comment]
Hey, so do you mean the floating window in the top right? Because that should appear any time you can't quite see the bottom of the log buffer to show you the new output. If it's appearing even though you can see the bottom of the log buffer / window then something has gone wrong.

**Comment by Olical** [comment]
If you're not interested in having the HUD pop up you can disable it entirely with this configuration:

https://github.com/Olical/conjure/blob/main/doc/conjure.txt#L614-L617

I'm going to close this in the hopes that it'll solve your problem but please do re-open it if you think there's a bug somewhere or you need more help.
