### ISSUE TITLE
Julia: evaluating functions from imported packages

### ISSUE THREAD

**Issue by theplatters** [Olical/conjure#617]
When using Conjure with Julia and Tree-Sitter evaluating a form, when over a  simple function call correctly send the function call to the repl. i.e `abs(-3)` => 3 evaluates correctly. 
When however doing the same on functions, that are called from a module, only the function definition is sent to the repl. 
i.e: 
`using Pkg`
`Pkg.activate("project")` => `activate (generic function with 3 methods)` 

Expected behavior:
Evaluate the function call.

**Comment by Olical** [comment]
Ah! So in this cause `Pkg.activate` is being sent but not the actual application of it through the parens. Investigating!

**Comment by Olical** [comment]
While debugging this, TIL about `:InspectTree`, perfect for debugging tree sitter stuff! Used to be this plugin https://github.com/nvim-treesitter/playground

![image](https://github.com/user-attachments/assets/44388196-f222-4bbb-a530-bd5c3f06dd5a)

**Comment by Olical** [comment]
Pushed some changes to the `main` branch that should fix your issues. I also made it so we don't treat argument lists as valid forms, so if you eval from within the arg list now it correctly executes the function instead of returning the arg list as a tuple.

**Comment by Olical** [comment]
Improved it again, now if you have `Foo.bar` on it's own `ee` will evaluate and return `bar`. If you have parens after the end and it's actually a `call_expression` then the whole thing will be called. So you can have lines that look things up and things that call things and `ee` should "do the right thing". There's always `er` too if Conjure is only evaluating a part of something and you want it to do the WHOLE thing.

**Comment by theplatters** [comment]
Thanks for the quick fix

**Comment by theplatters** [comment]
Hey, I found a simmilar bug

``julia

a = 3
b = 4

(a,b) = b,a
``

evaluating the last line just evaluates (a,b) and not (a,b) = b,a.
a,b = b,a work's fine, so this is not that terrible of a bug.

**Comment by Olical** [comment]
Oh actually, evaluating an assignment actually shows you the result which is nice.

**Comment by Olical** [comment]
Okay, added this rule, the user can still use visual eval or motions like `ea(` to evaluate something more specific. But the default behaviour is now "if you eval in an assignment, the assignment is evaluated" because it prints the results anyway as part of that operation. I was worried it would hide the results so you'd have to write specific expressions to print the results after.

**Comment by theplatters** [comment]
Thank you
