### ISSUE TITLE
Evaluating the buffer only evaluates the first function in common lisp

### ISSUE THREAD

**Issue by wbehrens-on-gh** [Olical/conjure#622]
When I run `<localleader>eb` on the following file only the `defun coeff` is evaluated

```lisp
(defun coeff (term)
  (car term))

(defun degree (term)
  (cadr term))

(degree '(3 4))
```

**Comment by Olical** [comment]
Interesting, I can reproduce this, but other longer files evaluate just fine. Here's the output with `g:conjure#debug` set to true:

```lisp
; debug: eval-str() called with: {:cb #<function: 0x77447d40b0d8>↵ :code "(swank:simple-completions \"j\" nil)"↵ :file-path "/home/olical/repos/Olical/conjure/conjure-log-700819.lisp"↵ :on-result #<function: 0x77447ff5da08>↵ :passive? true↵ :prefix "j"}
nil
; debug: swank.send called with msg: "(swank:simple-completions \"j\" nil)", context: nilnil
; --------------------------------------------------------------------------------
; eval (buf): ...os/Olical/conjure/dev/common-lisp/minimal.lisp
; debug: eval-str() called with: {:action "eval"↵ :code "(defun coeff (term)↵  (car term))↵↵(defun degree (term)↵  (cadr term))↵↵(degree '(3 4))"↵ :file-path "/home/olical/repos/Olical/conjure/dev/common-lisp/minimal.lisp"↵ :on-result #<function: 0x77447cb9f538>↵ :origin "buf"↵ :preview "; eval (buf): ...os/Olical/conjure/dev/common-lisp/minimal.lisp"↵ :range {:end [-1 15] :start [1 0]}}
nil
; debug: swank.send called with msg: "(defun coeff (term)↵  (car term))↵↵(defun degree (term)↵  (cadr term))↵↵(degree '(3 4))", context: nil
nil
COEFF
```

So we can see that the full code is actually being sent but evaluation seems to stop. I also see this warning in my server terminal so maybe that's related `WARNING: redefining COMMON-LISP-USER::COEFF in DEFUN`.

**Comment by Olical** [comment]
It looks like this `swank:eval-and-grab-output` API we're using to evaluate code only runs the first form? Trying to work out how to get it to run all of them or if that's even possible but I can't find the appropriate docs on it.

**Comment by Olical** [comment]
Just pushed a change to `main` that will wrap buffer evals in `(list ...)` which ensures that all values are evaluated and you see every result, which is how most other clients work.

What do you think?

**Comment by wbehrens-on-gh** [comment]
Thank you! looks like it worked.

**Comment by Olical** [comment]
Nice! Glad to hear it!
