### ISSUE TITLE
add command to eval macroexpand?

### ISSUE THREAD

**Issue by lost22git** [Olical/conjure#623]
for example:

cursor hold the code 
`(clojure.test/is (= 1 1))`

and execute conjure command to run this
`macroexpand '(clojure.test/is (= 1 1))`

and same for `macroexpand-1` `macroexpand-all`

thanks.

**Comment by Olical** [comment]
Good idea and I agree, I personally don't really ever use this and if I do I just write out the form. But I'm happy to add the mappings for this, should be pretty straightforward.

**Comment by Olical** [comment]
Pushed to main defaulting to `<prefix>x` as the prefix by default.

 - `x1` is `macroexpand-1`
 - `xr` is `macroexpand` (it calls repeatedly, hence the `r`)
 - `xa` is `clojure.walk/macroexpand-all`

**Comment by lost22git** [comment]
Thanks a lot, it works nice.
