### ISSUE TITLE
Set omnicomplete more intelligently

### ISSUE THREAD

**Issue by saccarosium** [Olical/conjure#624]
Hi,
I've been playing with this plugin and I've had some issues with the omnicompletion.

### Problem

Conjure seems to set `omnifunc` to `ConjureOmnifunc` regardless of it is already set or even if the client doesn't support completion (it happened with lua)

### Solution

I can make a PR myself but I need some time to understand a bit better how the various fennel parts work.

**Comment by Olical** [comment]
Ah good catch, I've pushed a change to `main` that should only set the omnifunc if the current client supports that part of the client API.

**Comment by saccarosium** [comment]
Works better now, thanks!
