### ISSUE TITLE
Question on evaluating in the log buffer

### ISSUE THREAD

**Issue by thecontinium** [Olical/conjure#63]
In the video it shows >> in red and then editing the log file and evaluate a new expression. 

How do you do this ?

Cheers

**Comment by Olical** [comment]
Ah that arrow is from my linting tool, that's got nothing to do with
Conjure I'm afraid.

Evaluating a new expression in the log works like it does in any Clojure
buffer 😊 it's just another Clojure file that happens to show Conjure
output.

**Comment by thecontinium** [comment]
Cheers

--
The Continium


On 2 October 2019 at 15:03:03, Oliver Caldwell (notifications@github.com<mailto:notifications@github.com>) wrote:

Ah that arrow is from my linting tool, that's got nothing to do with
Conjure I'm afraid.

Evaluating a new expression in the log works like it does in any Clojure
buffer 😊 it's just another Clojure file that happens to show Conjure
output.

**Comment by Olical** [comment]
No problem, I'll close this if that answers your question :smile:
