### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by thecontinium** [Olical/conjure#68]
Hi

Do you have any plans to incorporate a code linter into conjure ?

If so which tool are you considering ?

Cheers

**Comment by Olical** [comment]
I'm afraid not, no. I don't consider that part of Conjure's domain, Conjure is all about inspecting and evaluating your code, linting is a static process that happens outside of the runtime of your project.

I do however highly recommend [ale](https://github.com/dense-analysis/ale) with [clj-kondo](https://github.com/borkdude/clj-kondo) and [joker](https://github.com/candid82/joker). I use this combination of tools and it works great!

My ale config looks like this:

```viml
let g:ale_linters = {
      \ 'javascript': ['standard'],
      \ 'clojure': ['clj-kondo', 'joker']
      \}
```

**Comment by thecontinium** [comment]
Thanks for the steer. I’ll give it a go.

--
The Continium

On 21 October 2019 at 19:11:51, Oliver Caldwell (notifications@github.com<mailto:notifications@github.com>) wrote:

I'm afraid not, no. I don't consider that part of Conjure's domain, Conjure is all about inspecting and evaluating your code, linting is a static process that happens outside of the runtime of your project.

I do however highly recommend ale<https://github.com/dense-analysis/ale> with clj-kondo<https://github.com/borkdude/clj-kondo> and joker<https://github.com/candid82/joker>. I use this combination of tools and it works great!

My ale config looks like this:

let g:ale_linters = {
      \ 'javascript': ['standard'],
      \ 'clojure': ['clj-kondo', 'joker']
      \}

**Comment by mn-dimension** [comment]
for those that use [Neomake](https://github.com/neomake/neomake) here is a simple setup:


```
call neomake#configure#automake('nrw')

let g:neomake_joker_maker = {
		\ 'exe': 'joker',
		\ 'args': ['--lint'],
		\ 'errorformat': '%f:%l:%c: %*[^ ] %t%*[^:]: %m',
		\ }

let g:neomake_cljkondo_maker = {
		\ 'exe': 'clj-kondo',
		\ 'args': ['--lint'],
		\ 'errorformat': '%f:%l:%c:\ Parse\ %t%*[^:]:\ %m,%f:%l:%c:\ %t%*[^:]:\ %m',
		\ }

let g:neomake_clojure_enabled_makers = ['joker', 'cljkondo']
```
