### ISSUE TITLE
*out*: where does it go ?

### ISSUE THREAD

**Issue by thecontinium** [Olical/conjure#69]
Is there a way of seeing output in *out* ?

e.g 
```
(println 10) 
10
nil

```

cheers

**Comment by Olical** [comment]
Hmm, you're not seeing it in the Conjure log buffer? It should be there! :grimacing:

**Comment by thecontinium** [comment]
After a bit more investigation it looks like it only outputs to the log after a linefeed.

eg. for

(print 10)
(print 10)
(println 10)

Results in:

nil
; dev/eval | (print 10)
; dev/ret ⤸
nil
; dev/eval | (print 10)
; dev/ret ⤸
nil
; dev/eval | (println 10)
; dev/out | 101010
; dev/ret ⤸
nil

Also when I evaluated (println 10) after a lot of function evaluations of different (spec/expalin … ) that had output to *out* I got a slew of “buffered” output and then the “10"

Cheers

--
The Continium


On 25 October 2019 at 17:34:31, Oliver Caldwell (notifications@github.com<mailto:notifications@github.com>) wrote:

Hmm, you're not seeing it in the Conjure log buffer? It should be there! 😬

**Comment by thecontinium** [comment]
fyi: (spec/explain-str … ) seems to work without the flush.

--
The Continium


On 25 October 2019 at 18:03:40, Oliver Caldwell (notifications@github.com<mailto:notifications@github.com>) wrote:

Hmm, so it looks like this is an inherent thing in prepls, if you netcat into a prepl port you can see this behaviour.

$ netcat localhost 5678                                                                    ~

(print "foo")

{:tag :ret, :val "nil", :ns "user", :ms 0, :form "(print \"foo\")"}

(print "\n")

{:tag :ret, :val "nil", :ns "user", :ms 0, :form "(print \"\\n\")"}

(newline)

{:tag :ret, :val "nil", :ns "user", :ms 1, :form "(newline)"}

(flush)

{:tag :out, :val "foo\n\n"}

{:tag :ret, :val "nil", :ns "user", :ms 2, :form "(flush)"}

(print "foo")

{:tag :ret, :val "nil", :ns "user", :ms 1, :form "(print \"foo\")"}

(flush)

{:tag :out, :val "foo"}

{:tag :ret, :val "nil", :ns "user", :ms 1, :form "(flush)"}



So maybe each eval of Conjure should also do a (flush)? Although that feels like it could have unintended side effects, like flushing things you didn't want flushed yet in your program?

So your spec/explain wasn't showing in *out* until a flush happened? That's not good and not something I've seen before, maybe flush on every eval is the way to go 🤔 ideally the prepl would do this for us.

**Comment by daveyarwood** [comment]
This is interesting, because for context, if you start a "clojure.main REPL" by running `clj` and evaluate `(print "foo")`, it does immediately show you the `foo` output. `lein repl` and `boot repl` both behave the same.

My guess is that something in the clojure.main REPL (maybe also in nREPL?) is automatically flushing stdout somehow.

In general, I think the expected behavior of printing without a newline is that you may or may not see the output, so I don't think the prepl behavior is wrong, it just doesn't happen to match what the other REPLs are doing.

**Comment by thecontinium** [comment]
Maybe we have an option in conjure to force the more common repl behaviour ?

--
The Continium

On 25 October 2019 at 20:10:22, Dave Yarwood (notifications@github.com<mailto:notifications@github.com>) wrote:

This is interesting, because for context, if you start a "clojure.main REPL" by running clj and evaluate (print "foo"), it does immediately show you the foo output. lein repl and boot repl both behave the same.

My guess is that something in the clojure.main REPL (maybe also in nREPL?) is automatically flushing stdout somehow.

In general, I think the expected behavior of printing without a newline is that you may or may not see the output, so I don't think the prepl behavior is wrong, it just doesn't happen to match what the other REPLs are doing.

**Comment by thecontinium** [comment]
Are you expecting [this](https://github.com/Olical/conjure/issues/69#issue-512346498) to be fixed now ? It still doesn't work for me.

**Comment by martinklepsch** [comment]
@thecontinium note that the commit isn't in `master` but `develop`.

**Comment by thecontinium** [comment]
Ah ok - Will wait for next release and keep you posted.

Cheers
--
The Continium

On 22 November 2019 at 18:57:37, Martin Klepsch (notifications@github.com<mailto:notifications@github.com>) wrote:

@thecontinium<https://github.com/thecontinium> note that the commit isn't in master but develop.

**Comment by thecontinium** [comment]
resolved - thanks
