### ISSUE TITLE
`#slurp-edn` doesn't walk up the tree.

### ISSUE THREAD

**Issue by dharrigan** [Olical/conjure#71]
Hi,

No logs produced!

Anyhoo...

I have this configured as my `conjure.edn` file:

```
{:conns
 {:local {:port 55555}
  :propel {:port #slurp-edn ".prepl-port" :enabled? true :lang :cljs}}}
```

If I launch, at the root of my project folder, something like this:

`clojure -m propel.main -e figwheel --figwheel-build dev -w`

A `.prepl-port` is written to that root folder. However, if I then do this:

`nvim src/cljs/foo/bar/core.cljs`

ConjureUp reports `Skipping :propel - nil port`

If, however, I copy the `.prepl-port` file to the `src/cljs/foo/bar` directory, then it's able to connect successfully. 

I think the same logic which searches for the `conjure.edn` file could also look for the `prepl-port` file if slurping edn.

**Comment by Olical** [comment]
Hmmmmm how to do this. I feel like walking up the tree could lead to very weird circumstances 🤔

And you can't slurp relative to the conjure.edn because then it wouldn't work if you specified your config in your home dir.

HMMMM

Thanks for bringing it up! I'll have a thonk.

**Comment by dharrigan** [comment]
I suppose it's a nice to have, I mean, I could specify a project local `.conjure.edn` file with the `propel` alias in there, instead of the global `conjure.edn` file.

I'll leave it with you - but having a project local alternative is acceptable.

**Comment by dharrigan** [comment]
Actually,

I can't get this to work. I have a local `.conjure.edn` file with this as the contents:

```
{:conns
  {:propel {:port #slurp-edn ".prepl-port" :lang :cljs}}}```

I can confirm that the file `.prepl-port` exists:

```
% cat .prepl-port 
43309%
```

Executing

`nvim src/foo/bar/core.cljs`

I get this:

`conjure/up | Skipping :propel - nil port`

And it starts its own default Conjure JVM.

**Comment by Olical** [comment]
That `%` at the end there, is that just a typo? Or does `.prepl-port` actually contain a `%`?

**Comment by dharrigan** [comment]
Hi,

It's just a copy paste from the terminal, so no % in edn file.

-=david=-

I prefer encrypted and signed messages

Fingerprint: 110AF423364754E2880FADAD1C5285BFB20A22F9

No trees were harmed in the sending of this message, however, a number of
electrons were inconvenienced.

This email is sent without prejudice.

**Comment by Olical** [comment]
I honestly can't reproduce this :thinking: which makes me think it's something local to your Neovim setup? Maybe one of your plugins or a part of your config is messing with your current working directory? Or the file isn't readable by the process? (chown / chmod?)

Maybe I should come find you at re:Clojure and you can show me :stuck_out_tongue:

**Comment by Olical** [comment]
We worked this out to be some other plugin causing the CWD to change if you open a file directly as described in this issue. That's not normal Neovim behaviour as far as I'm aware and there's not much I can do to solve it. I think David is going to try and diagnose the plugin that's causing the issue :slightly_smiling_face:

**Comment by dharrigan** [comment]
I agree. I tend to think it's my config. I'm going to close this issue and reopen a new one if I prove otherwise (highly doubtful :-) ) Thanks Olical for your continued support! :-)
