### ISSUE TITLE
Neovim LSP support?

### ISSUE THREAD

**Issue by ahmedelgabri** [Olical/conjure#72]
Neovim now comes with an LSP support https://neovim.io/doc/user/lsp.html & there are already ongoing work to port lost of LSPs to the nvim lua LSP https://github.com/neovim/nvim-lsp, any plans to support this?

**Comment by Olical** [comment]
None at the moment, I've never used LSP in the context of Clojure, I stick to good old eval, I prefer that to static analysis when it comes to lisps. I probably won't ever experiment with this, I don't see what value I could add that other plugins couldn't.

**Comment by ahmedelgabri** [comment]
LSPs can also provide semantic autocompletion, etc… not just analysis. 

> I don't see what value I could add that other plugins couldn't.

The _native_ LSP support means, that neovim users don't need to install LSP plugins, only the servers + being part of the editor means there some kind of trust that things won't be just randomly abandoned or break for example. 

I'll try my last shot to make you a bit curious, it's written in lua so you can use `aniseed` for it 😄

**Comment by Olical** [comment]
Conjure is purely about getting code to a prepl and displaying the results (which also happens to enable go to definition, completion etc), a LSP server would be an entirely different project in my eyes. I'm sure it'd be handy but it'd have nothing in common with Conjure, I've just got no interest in writing an LSP server right now is all. LSP and REPL are completely orthogonal in my opinion, but two tools (one for each) can be used side by side.
