### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by kujohn** [Olical/conjure#77]
Doesn't seem to compile on 2.1.2. `Post-update hook for conjure ... Exit status: 1` whenever trying to install. And vim shows `Conjure not compiled, please run bin/compile then conjure#init() or restart` Any idea?

**Comment by kujohn** [comment]
Seems like I have existing maven settings that points to internal artifact store. That solved it.

**Comment by Olical** [comment]
Glad you worked it out! :D I was away from my computer last week, sorry for the lack of response!
