### ISSUE TITLE
Key mappings issues

### ISSUE THREAD

**Issue by djblue** [Olical/conjure#81]
I've gotten really use to `cpp` to eval forms from vim-fireplace. It looks like conjure allows you to modify `eval-current-form` in two ways, but only one of them seems to work.

This one doesn't work:

```
ConjureConfig mappings.eval-current-form ["cpp"]
```

This one does work:
```
let g:conjure_config = {"mappings.eval-current-form": ["cpp"]}
```

Not sure what's up, just thought I should let you know. Also, amazing job on 3.0 release 🎉

**Comment by Olical** [comment]
Hmm, odd! Are you running `ConjureConfig` in your Neovim config before you open a Clojure file? Also, if you open up a Clojure file then hit `:e` again, does it work?

**Comment by djblue** [comment]
I was running `ConjureConfig` as a command when with a clojure file open to test out the mapping.

**Comment by djblue** [comment]
If I `:e` the file after I run the `ConjureConfig` command as you suggested, it does work.

**Comment by Olical** [comment]
Yep, I'm afraid changes to mappings won't happen right away, they're set up with an autocmd on filetype. So you need to `:e` after setting them or set them in your Neovim config where you add your plugins etc (the intended place). I'm afraid there's no real way for me to change mappings on the fly once the buffer is open.

**Comment by Olical** [comment]
An action that could come of this could be better documentation that describes this behaviour.

**Comment by Olical** [comment]
I've added a mention about this in `conjure-mappings` help text, hopefully it's enough! You just need to set these things _before_ you open a buffer. If you do it after you'll have to kill the buffer and re-open it for the changes to take full effect.
