### ISSUE TITLE
How to evaluate many files at once

### ISSUE THREAD

**Issue by rafamedina** [Olical/conjure#83]
Hi,

In the new version, 3.0.0
Question: how to evaluate many files at once?
I have to evaluate manually all the dependencies file before to run any test
Regards

**Comment by Olical** [comment]
Hey! Do you have the file paths to hand? Like do you know their paths or namespaces ahead of time?

If so, you could create a mapping or something that uses `:ConjureEval (load-file "...")` to load the things you need? Is that kind of what you mean? Or a specific command that will load a path?

**Comment by rafamedina** [comment]
Hi Olical, 

I have a theory: maybe the files are being evaluated in a wrong sort:

```
; --------------------------------------------------------------------------------
; localhost:56309 (connected)
; --------------------------------------------------------------------------------
; Assumed session: 18617125-8c61-40a9-a653-12ddc72cf751
; --------------------------------------------------------------------------------
; Refreshing changed namespaces
project.adapters.transaction
project.db.datomic.transaction
project.controllers.transaction
project.diplomat.consumer
project.diplomat.producer
project.diplomat.http-out
project.config
project.service
project.db.datomic.config
project.components
integration.aux.init
integration.version-test
project.complexity-test
project.config-test
integration.transaction-settled-test
user
project.service-test
project.server
; Error while reloading project.adapters.transaction
; (err) Syntax error compiling at (project/adapters/transaction.clj:6:1).
; (err) No such var: in.transaction/Transaction
```

If I first evaluate the dependency, it works correctly

**Comment by Olical** [comment]
Hmm, this sounds like it could be an issue with [tools.namespace](https://github.com/clojure/tools.namespace) more than Conjure, that's not my code I'm afraid. I'm just invoking the refresh function via the CIDER middleware.

Maybe you have a cyclic dependency somewhere that's confusing it? I've run into that before with a Clojure project.

**Comment by rafamedina** [comment]
My bad, I was running it using a session shared with spacemacs.
Running it with a "clean" one, no problems
Thanks

**Comment by Olical** [comment]
Ah interesting! I would still expect it to work to be honest. That's quite a weird issue :thinking: I'm glad it's all working now though!
