### ISSUE TITLE
Lua error: attempt to concatenate a userdata value

### ISSUE THREAD

**Issue by daveyarwood** [Olical/conjure#86]
After updating to Conjure 3.1.0, I get this message every time I open a Clojure buffer for the first time after starting Vim:

```
Error executing vim.schedule lua callback: /home/dave/.vim/bundle/conjure//lua/conjure/fs.lua:31: attempt to concatenate a userdata value
```

I get the same error when I press `<localleader>cf` to attempt to connect to my nREPL server.

This happens regardless of whether I have an nREPL server is running. I tried both a Boot project and a tools.deps project with the same result.

**Comment by FongHou** [comment]
I got the same error. @daveyarwood, see https://github.com/Olical/conjure/issues/84#issue-616305361 for quick workaround

Or

export XDG_CONFIG_HOME=$HOME/.config in shell will do also.

**Comment by daveyarwood** [comment]
I can confirm that setting XDG_CONFIG_HOME fixes the issue as a workaround.

When I run:

```bash
vim src/path/to/file.clj
```

I get the error. When I run:

```bash
XDG_CONFIG_HOME=$HOME/.config vim src/path/to/file.clj
```

I don't get the error, and I'm able to connect to my nREPL and eval stuff, etc.

**Comment by Olical** [comment]
This is super weird since I'm handling the lack of these environment variables, this shouldn't happen. The only one I need is `HOME` as a default. It's as if it returns a string but it doesn't like me concatenating with it?

**Comment by daveyarwood** [comment]
Whatever you did on develop just now fixed it, so thanks! :)

Without XDG_CONFIG_HOME set, I can now use Conjure without getting the error above.

**Comment by Olical** [comment]
Yesss, I just made it a little safer, checking the type of the value and if it's empty or not. I think maybe on some setups it was giving me a weird data type, not a string or nil.
