### ISSUE TITLE
ConjureSchool fails unless maplocalleader is explicitly set

### ISSUE THREAD

**Issue by daveyarwood** [Olical/conjure#88]
I use the default localleader, `\`.  When I ran `:ConjureSchool`, I got this error:

```
E5108: Error executing lua ...ome/dave/.vim/bundle/conjure//lua/conjure/school.lua:100: attempt to concatenate field 'maplocalleader' (a nil value)
```

I ran `:let g:maplocalleader='\'` and tried it again, and it worked.

**Comment by Olical** [comment]
Pushed a commit that should address this, it instead shows a warning that your localleader isn't set.

**Comment by daveyarwood** [comment]
It's working now, thanks for the quick fix! :tada: 

ConjureSchool works now, and the comment now reads:

```fennel
;; Let's begin by evaluating the whole buffer using <localleader>eb
;; Your <localleader> isn't set, see :help localleader for more information.
```

And eval-ing still works :+1:
