### ISSUE TITLE
view-source action trigger error on shadow-cljs nrepl server side.

### ISSUE THREAD

**Issue by FongHou** [Olical/conjure#89]
I don't remember seeing this error before v3.1.0. It seems client sending special form ns* (star on the right). Not sure if it has anything to do with recent change on session handling and auto-load? 

```
[2020-05-13 14:53:07.622 - WARNING] :shadow.cljs.devtools.server.worker.impl/repl-error - {:when :shadow.cljs.devtools.server.worker.impl/do-repl-rpc, :command
 :repl-eval, :msg {:type :repl-eval, :session-id "a7abd8a9-3bdf-4b34-a82a-5789ec8013ef", :runtime-id nil, :input {:eof? false, :ns cljapp.ui, :form (clojure.co
re/require (quote clojure.repl)), :source "(clojure.core/require 'clojure.repl)"}, :result-chan #object[clojure.core.async.impl.channels.ManyToManyChannel 0x71
611a04 "clojure.core.async.impl.channels.ManyToManyChannel@71611a04"]}}
ExceptionInfo Failed to process REPL command {:eof? false, :ns cljapp.ui, :form (clojure.core/require (quote clojure.repl)), :source "(clojure.core/require 'cl
ojure.repl)", :tag :shadow.cljs.repl/process-ex}
        shadow.cljs.repl/process-read-result (repl.clj:524)
        shadow.cljs.repl/process-read-result (repl.clj:498)
        shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:879)
        shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:833)
        shadow.cljs.devtools.server.worker.impl/eval20367/fn--20368 (impl.clj:914)
        clojure.lang.MultiFn.invoke (MultiFn.java:234)
        shadow.cljs.devtools.server.util/server-thread/fn--19895/fn--19896/fn--19904 (util.clj:285)
        shadow.cljs.devtools.server.util/server-thread/fn--19895/fn--19896 (util.clj:284)
        shadow.cljs.devtools.server.util/server-thread/fn--19895 (util.clj:257)
        java.lang.Thread.run (Thread.java:748)
Caused by:
ExceptionInfo ns* not supported (require, require-macros, import, import-macros, ... must be part of your ns form) 
```

**Comment by Olical** [comment]
Hmm that's odd, I can reproduce it too. It does seem to work with JVM Clojure still and I haven't changed anything around this so I wonder if it's something shadow specific. I'll try out regular piggieback CLJS too and see if it's reproducible there, if not I'd imagine it'll be a shadow specific issue :thinking:

**Comment by Olical** [comment]
Worked out what it is, I'm doing `clojure.core/require` now, which I thought was safer, but shadow doesn't like it.

**Comment by Olical** [comment]
How's `develop` now?

**Comment by FongHou** [comment]
Works. Thanks!

**Comment by FongHou** [comment]
A different error showed up.

```
[2020-05-13 20:58:59.574 - WARNING] :shadow.cljs.devtools.server.worker.impl/repl-error - {:when :shadow.cljs.devtools.server.worker.impl/do-repl-rpc, :command
 :repl-eval, :msg {:type :repl-eval, :session-id "39cba4e1-7a07-43e3-bd7b-2e442e127db8", :runtime-id nil, :input {:eof? false, :ns cljapp.ui, :form (require (quote clojure.repl)), :source "(require 'clojure.repl)"}, :result-chan #object[clojure.core.async.impl.channels.ManyToManyChannel 0xa4d5940 "clojure.core.async.impl.channels.ManyToManyChannel@a4d5940"]}}                                                                                                                    ExceptionInfo Failed to process REPL command {:eof? false, :ns cljapp.ui, :form (require (quote clojure.repl)), :source "(require 'clojure.repl)", :tag :shadow.cljs.repl/process-ex}                                                                                                                                                 shadow.cljs.repl/process-read-result (repl.clj:528)                                                                                                            shadow.cljs.repl/process-read-result (repl.clj:502)                                                                                                            shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:879)                                                                                             shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:833)                                                                                             shadow.cljs.devtools.server.worker.impl/eval20369/fn--20370 (impl.clj:914)                                                                                     clojure.lang.MultiFn.invoke (MultiFn.java:234)                                                                                                                 shadow.cljs.devtools.server.util/server-thread/fn--19897/fn--19898/fn--19906 (util.clj:285)                                                                    shadow.cljs.devtools.server.util/server-thread/fn--19897/fn--19898 (util.clj:284)
        shadow.cljs.devtools.server.util/server-thread/fn--19897 (util.clj:257)
        java.lang.Thread.run (Thread.java:748)
Caused by:
ExceptionInfo In :require [clojure.repl :refer (clojure.repl)] already used by [cljs.repl :refer (clojure.repl)] 
```

**Comment by FongHou** [comment]
Something strange, I *either* got (js/...) completion and view-source triggering exception, *or* view-source without exception but (js/...) completion stop working. It's fairly random what situation it ended up.

**Comment by thheller** [comment]
@FongHou can you share the ns form of `cljapp.ui`? The error is weird and I can't reproduce it. The error suggests that there is a conflicting `:refer` which is weird?

**Comment by Olical** [comment]
Yeah, seeing the source would be great, I can't reproduce this issue now :thinking: everything in shadow-cljs + Conjure land is working well for me.

**Comment by FongHou** [comment]
I have a conjure session now without js completion.

![image](https://user-images.githubusercontent.com/13973254/81951590-5b435980-95d3-11ea-9bc4-576126d0df45.png)

On the left you can see ns form, and js/w does not trigger completion.

On the right you can conjure session is Clojurescript (though the comment line says "Couldn't determine session type", which is confusing). Eval (ns ...) form result success. 

I'm using 

conjure develop branch commit 1da0f78af549e5f66c23f603e193ece30d646107
[thheller/shadow-cljs "2.9.3"]
[org.clojure/clojurescript "1.10.758"]

**Comment by Olical** [comment]
Oh, managed to get this which is fun.

```
; source (word): xyz
; (err) [1;31m------ REPL Error while processing ---------------------------------------------[0m
; (err) (require 'clojure.repl)
; (err) In :require [clojure.repl :refer (clojure.repl)] already used by [cljs.repl :refer (clojure.repl)]
; (out) (defn xyz []
; (out)   (println "This is a ClojureScript file!"))
```

**Comment by Olical** [comment]
I've wrapped some code up in a do and it seems a _lot_ happier now, what do you think? (`develop` again)

Doc, source, go to def, completion, test namespace, test all, test current under cursor all seem to work well for me in JVM Clojure and shadow-cljs via browser.

**Comment by FongHou** [comment]
Yes, I can confirm everything works well now.

A few ideas for refinement:

1. Could select-session-interactive and display-sessions list include session-type along side of session uuid? This would make it clear when switching sessions.

2. Does conjure automatically switch session-type base on current buffer's file type (*.clj vs. *.cljs)? I don't see this happens currently. I think this should be pre-condition in order for auto-require to work reliably. 

3. Would recent changes on conjure side change the behavior of coc-conjure? One strange thing happened in the middle, now I have to type C-X C-O to trigger conjure completion menu. It used to just showing up without.

Thanks again for your excellent work on the project! 

Cheers!

**Comment by Olical** [comment]
Glad to hear it! I'll get the current develop tagged soon to provide a stable version.

Displaying the session type beside the UUID is on my todo list (I also have an item to make those UUIDs human readable somehow) but it's kind of tricky. Conjure and nREPL have no concept of "session type", it's a term I've made up for what gets returned by the following:

```clojure
#?(:clj 'Clojure :cljs 'ClojureScript :cljr 'ClojureCLR :default 'Unknown)
```

So the type depends on what reader conditional flags are set in the current evaluation environment of the session. So to display the "type" next to each session I need to fire off an eval into each session as I generate the list. Not the end of the world but a little bit tricky.

All evaluations will happen in your current session which will be Clojure or ClojureScript. Conjure is not the one that decides how something should be evaluated, that's down to your nREPL session, I just query it to display the "type" for you.
