### ISSUE TITLE
Opening the command line window while having the HUD open triggers an error

### ISSUE THREAD

**Issue by adz5a** [Olical/conjure#90]
Hello,
Having opening the command line window while having the hud on (after eval a form for instance) seems to trigger an error because it tries to close the wrong window on cursor move:

```
Error detected while processing CursorMoved Autocommands for "*":
E5105: Error while calling lua chunk: ...onfig/nvim/pack/minpac/start/conjure/lua/conjure/log.lua:72: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
```

version: 3.1.2

When you close the HUB beforehand no problem / errors.

PS: i tried conjure with shadow-cljs and it worked well, conjure looks amazing congrats :)

**Comment by Olical** [comment]
Hey, thanks for the report! This should be an easy fix, I guess you can't issue "close window" function calls from within the command line window! You learn something new every day, I'll get this patched out! Sorry about the error :grimacing: (I rarely if ever use the command-line window so I hadn't thought of this one)

I'm glad to hear that it's working well! :tada: feel free to drop feedback into the Slack or something if there's something really getting on your nerves. I have a very finite amount of time so I need to prioritise features, but feelings and ideas are always neat to discuss :smile:

**Comment by Olical** [comment]
I've pushed a fix for this to `develop`, I hope that looks good to you!

**Comment by adz5a** [comment]
Hello,

It seems to work with your fix, thanks!
