### ISSUE TITLE
Extending conjure with new languages

### ISSUE THREAD

**Issue by wbthomason** [Olical/conjure#92]
(More of a question than a bug report/feature request)

At a high level, what's required to add support for a new language to `conjure`? For example, let's say I wanted to add support for Common Lisp via SBCL/some Scheme. Is this a reasonably standard process per language, or does it usually require adding some bespoke/deep changes?

**Comment by Olical** [comment]
Hey! Adding support for more languages is extremely encouraged (either as your own repo / plugin or a PR to this project), the framework for language support is completely separate from the outer shell of Conjure's UX to enable this. Conjure should be seen as a platform for implementing language support that handles a huge amount of UI / UX / mapping / config infrastructure for you.

A Conjure language client is just a Lua module (which you can compile from Fennel if you so choose) that contains a few functions and values. Information on the required and optional fields of your module can be found in [`:h conjure`](https://github.com/Olical/conjure/blob/48b7820292ff639e2d950f331c4f96758a344379/doc/conjure.txt#L377).

So you could either PR it into this project following the formula of the [existing clients](https://github.com/Olical/conjure/tree/master/fnl/conjure/client) or even write your own plugin that people can depend on separately. I suppose that gives you more freedom? Maybe that's the best bet until you're happy that it's stable and it can be incorporated into the core plugin?

**Comment by wbthomason** [comment]
Great, thanks for the information! I'll poke around some of the existing client code more.
