### ISSUE TITLE
Switching back to the Clojure repl in shadow cljs

### ISSUE THREAD

**Issue by adz5a** [Olical/conjure#94]
I would like to know if there is a mechanism currently in conjure to switch back to the Clojure repl in shadow-cljs: after using `ConjureShadowSelect` there is no way to go back "automatically" to the Clojure one, except by evaluating `:cljs/quit` (from the log buffer for instance).

I guess one could use an autocommand or something to implement a custom behaviour but I was wondering: is there currently a way around this in conjure that I may have overlooked ?

**Comment by Olical** [comment]
You're right in that there's nothing built into Conjure for this, but a mapping to `:ConjureEval :cljs/quit` will do the trick :smile: I'm not sure about adding a specific mapping for it since it's quite specific to using shadow or piggieback, I'd have to potentially disable the mapping depending on your REPL type and that's just a whole can of worms.

**Comment by Olical** [comment]
Oh, another thing you can do, hit `,sf` to create a fresh Clojure session and then use `,ss` or `,sn` etc to cycle between Clojure and ClojureScript.

**Comment by adz5a** [comment]
awesome that was exactly what i wanted :)
thanks

**Comment by Olical** [comment]
Sweet! I'll close this one since I don't think I want to add a specific mapping for sending `:cljs/quit` right now.

**Comment by stelcodes** [comment]
> Oh, another thing you can do, hit `,sf` to create a fresh Clojure session and then use `,ss` or `,sn` etc to cycle between Clojure and ClojureScript.

Just a note for future readers, this keybinding is `<localleader>sf`, etc

**Comment by hoclun-rigsep** [comment]
Is the current recommendation still to write some autocommands to switch between repl sessions when I switch among `.clj` and `.cljs` buffers?

**Comment by Olical** [comment]
Yep! There's a wiki page that had an example auto command to do this. I
spoke to a few people at Heart of Clojure about this and an idea that
started to float around was a feature for the Clojure client that does this
for you in a limited way that only works with SOME projects and can be
turned on with a Boolean option.

It would be off by default. It would not work for every scenario and every
user, but maybe we can have something that works 80% of the time.

What do you think? And how would you expect such a "semi automatic, lots of
assumptions" system to work?

**Comment by hoclun-rigsep** [comment]
I can offer my experience with vim-fireplace as a point of information.

My experience is limited to using shadow-cljs with fireplace; it goes
like this:

1.  Start a repl, e.g. `clojure -M:shadow-cljs:repl/headless`
2.  Open nvim and connect to the repl
3.  Serve the cljs, whether with custom server code or with the shadow-cljs dev server. I do the former when I have the frontend and     backend in the same project but it shouldn't matter.
4.  Call `shadow/watch`
5.  Start a cljs repl: `:CljEval (shadow/repl :frontend)`
    `:CljEval` "Always use\[s\] the user namespace and Clojure Platform," so the `shadow` namespace is available
6.  Load the cljs in the browser.
7.  Open a cljc or cljs bufffer: any evaluation commands will now be sent to the cljs repl
8.  Open/switch to a clj buffer: any evaluation commands will now be sent to the clj repl
9. et cetera

Step 1 could have been `npx shadow-cljs watch frontend`, which would have obviated steps 3 and 4.

Fireplace docs suggest that this would work the same with configurations other than shadow-cljs (figwheel, etc) as long as they play nice with piggieback. I don't know whether fireplace uses piggieback in the situation I outlined above—shadow-cljs "does not use piggieback" but apparently has some kind of shim for it, but I don't know what any of that means.

Right now I can do all this in conjure, but steps 7-9 are manual. From my perspective they should be automatic. A lot of 1-6 could for good reason happen at different times and in different ways,[^1]—but I can't think of a scenario where one would want to evaluate a form in a clj buffer using the cljs repl, or vice versa, and if one needed to there's still `:ConjureCljSessionSelect` and so on. It might be nice to have commands like fireplace's `:CljEval` and `:CljsEval`, that always use the right repl and the `main`/`cljs.main` namespace.

[^1]: Such as not using shadow-cljs at all, and/or using not the browser but a node repl, etc.
