### ISSUE TITLE
eval doesn't show result for babashka

### ISSUE THREAD

**Issue by FongHou** [Olical/conjure#95]
Hi, this happens in develop branch.

![image](https://user-images.githubusercontent.com/13973254/82696537-2bc8c880-9c35-11ea-8ee4-c983f21e5cd0.png)

**Comment by Olical** [comment]
Oh that's really odd! I'm sorry about that, it looks like you don't have a session. Could you try hitting `,sf` to create a fresh session and then evaluating?

It seems like it's just the initial session creation that's failing on connection. That's preventing evaluations.

**Comment by FongHou** [comment]
Yes, that resolved it.

**Comment by Olical** [comment]
I'll have a look into it though, sounds like a bug to me!

**Comment by Olical** [comment]
Tried this myself and I can't reproduce it. It worked fine, maybe it's a
timing issue, I'll keep an eye on it!

**Comment by FongHou** [comment]
No worries. I haven't reproduced it either. Thanks for looking into it!
